/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401AssignedAddOnCreateIncomingPhoneNumberAssignedAddOn } from "../funcs/api20100401AssignedAddOnCreateIncomingPhoneNumberAssignedAddOn.js";
import { api20100401AssignedAddOnDeleteIncomingPhoneNumberAssignedAddOn } from "../funcs/api20100401AssignedAddOnDeleteIncomingPhoneNumberAssignedAddOn.js";
import { api20100401AssignedAddOnFetchIncomingPhoneNumberAssignedAddOn } from "../funcs/api20100401AssignedAddOnFetchIncomingPhoneNumberAssignedAddOn.js";
import { api20100401AssignedAddOnListIncomingPhoneNumberAssignedAddOn } from "../funcs/api20100401AssignedAddOnListIncomingPhoneNumberAssignedAddOn.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401AssignedAddOn extends ClientSDK {
  /**
   * Fetch an instance of an Add-on installation currently assigned to this Number.
   */
  async fetchIncomingPhoneNumberAssignedAddOn(
    request: operations.FetchIncomingPhoneNumberAssignedAddOnRequest,
    options?: RequestOptions,
  ): Promise<operations.FetchIncomingPhoneNumberAssignedAddOnResponse> {
    return unwrapAsync(
      api20100401AssignedAddOnFetchIncomingPhoneNumberAssignedAddOn(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Remove the assignment of an Add-on installation from the Number specified.
   */
  async deleteIncomingPhoneNumberAssignedAddOn(
    request: operations.DeleteIncomingPhoneNumberAssignedAddOnRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      api20100401AssignedAddOnDeleteIncomingPhoneNumberAssignedAddOn(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Retrieve a list of Add-on installations currently assigned to this Number.
   */
  async listIncomingPhoneNumberAssignedAddOn(
    request: operations.ListIncomingPhoneNumberAssignedAddOnRequest,
    options?: RequestOptions,
  ): Promise<operations.ListIncomingPhoneNumberAssignedAddOnResponse> {
    return unwrapAsync(
      api20100401AssignedAddOnListIncomingPhoneNumberAssignedAddOn(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Assign an Add-on installation to the Number specified.
   */
  async createIncomingPhoneNumberAssignedAddOn(
    request: operations.CreateIncomingPhoneNumberAssignedAddOnRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateIncomingPhoneNumberAssignedAddOnResponse> {
    return unwrapAsync(
      api20100401AssignedAddOnCreateIncomingPhoneNumberAssignedAddOn(
        this,
        request,
        options,
      ),
    );
  }
}
