/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401IpAccessControlListMappingCreateSipIpAccessControlListMapping } from "../funcs/api20100401IpAccessControlListMappingCreateSipIpAccessControlListMapping.js";
import { api20100401IpAccessControlListMappingDeleteSipIpAccessControlListMapping } from "../funcs/api20100401IpAccessControlListMappingDeleteSipIpAccessControlListMapping.js";
import { api20100401IpAccessControlListMappingFetchSipIpAccessControlListMapping } from "../funcs/api20100401IpAccessControlListMappingFetchSipIpAccessControlListMapping.js";
import { api20100401IpAccessControlListMappingListSipIpAccessControlListMapping } from "../funcs/api20100401IpAccessControlListMappingListSipIpAccessControlListMapping.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401IpAccessControlListMapping extends ClientSDK {
  /**
   * Fetch an IpAccessControlListMapping resource.
   */
  async fetchSipIpAccessControlListMapping(
    request: operations.FetchSipIpAccessControlListMappingRequest,
    options?: RequestOptions,
  ): Promise<operations.FetchSipIpAccessControlListMappingResponse> {
    return unwrapAsync(
      api20100401IpAccessControlListMappingFetchSipIpAccessControlListMapping(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Delete an IpAccessControlListMapping resource.
   */
  async deleteSipIpAccessControlListMapping(
    request: operations.DeleteSipIpAccessControlListMappingRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      api20100401IpAccessControlListMappingDeleteSipIpAccessControlListMapping(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Create a new IpAccessControlListMapping resource.
   */
  async createSipIpAccessControlListMapping(
    request: operations.CreateSipIpAccessControlListMappingRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateSipIpAccessControlListMappingResponse> {
    return unwrapAsync(
      api20100401IpAccessControlListMappingCreateSipIpAccessControlListMapping(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Retrieve a list of IpAccessControlListMapping resources.
   */
  async listSipIpAccessControlListMapping(
    request: operations.ListSipIpAccessControlListMappingRequest,
    options?: RequestOptions,
  ): Promise<operations.ListSipIpAccessControlListMappingResponse> {
    return unwrapAsync(
      api20100401IpAccessControlListMappingListSipIpAccessControlListMapping(
        this,
        request,
        options,
      ),
    );
  }
}
