/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401IpAccessControlListCreateSipIpAccessControlList } from "../funcs/api20100401IpAccessControlListCreateSipIpAccessControlList.js";
import { api20100401IpAccessControlListDeleteSipIpAccessControlList } from "../funcs/api20100401IpAccessControlListDeleteSipIpAccessControlList.js";
import { api20100401IpAccessControlListFetchSipIpAccessControlList } from "../funcs/api20100401IpAccessControlListFetchSipIpAccessControlList.js";
import { api20100401IpAccessControlListListSipIpAccessControlList } from "../funcs/api20100401IpAccessControlListListSipIpAccessControlList.js";
import { api20100401IpAccessControlListUpdateSipIpAccessControlList } from "../funcs/api20100401IpAccessControlListUpdateSipIpAccessControlList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401IpAccessControlList extends ClientSDK {
  /**
   * Retrieve a list of IpAccessControlLists that belong to the account used to make the request
   */
  async listSipIpAccessControlList(
    request: operations.ListSipIpAccessControlListRequest,
    options?: RequestOptions,
  ): Promise<operations.ListSipIpAccessControlListResponse> {
    return unwrapAsync(api20100401IpAccessControlListListSipIpAccessControlList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new IpAccessControlList resource
   */
  async createSipIpAccessControlList(
    request: operations.CreateSipIpAccessControlListRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateSipIpAccessControlListResponse> {
    return unwrapAsync(
      api20100401IpAccessControlListCreateSipIpAccessControlList(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Fetch a specific instance of an IpAccessControlList
   */
  async fetchSipIpAccessControlList(
    request: operations.FetchSipIpAccessControlListRequest,
    options?: RequestOptions,
  ): Promise<operations.FetchSipIpAccessControlListResponse> {
    return unwrapAsync(
      api20100401IpAccessControlListFetchSipIpAccessControlList(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Rename an IpAccessControlList
   */
  async updateSipIpAccessControlList(
    request: operations.UpdateSipIpAccessControlListRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateSipIpAccessControlListResponse> {
    return unwrapAsync(
      api20100401IpAccessControlListUpdateSipIpAccessControlList(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * Delete an IpAccessControlList from the requested account
   */
  async deleteSipIpAccessControlList(
    request: operations.DeleteSipIpAccessControlListRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(
      api20100401IpAccessControlListDeleteSipIpAccessControlList(
        this,
        request,
        options,
      ),
    );
  }
}
