/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401FeedbackCreateMessageFeedback } from "../funcs/api20100401FeedbackCreateMessageFeedback.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401Feedback extends ClientSDK {
  /**
   * Create Message Feedback to confirm a tracked user action was performed by the recipient of the associated Message
   */
  async createMessageFeedback(
    request: operations.CreateMessageFeedbackRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateMessageFeedbackResponse> {
    return unwrapAsync(api20100401FeedbackCreateMessageFeedback(
      this,
      request,
      options,
    ));
  }
}
