/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401ThisMonthListUsageRecordThisMonth } from "../funcs/api20100401ThisMonthListUsageRecordThisMonth.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401ThisMonth extends ClientSDK {
  async listUsageRecordThisMonth(
    request: operations.ListUsageRecordThisMonthRequest,
    options?: RequestOptions,
  ): Promise<operations.ListUsageRecordThisMonthResponse> {
    return unwrapAsync(api20100401ThisMonthListUsageRecordThisMonth(
      this,
      request,
      options,
    ));
  }
}
