/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401IncomingPhoneNumberTollFreeCreateIncomingPhoneNumberTollFree } from "../funcs/api20100401IncomingPhoneNumberTollFreeCreateIncomingPhoneNumberTollFree.js";
import { api20100401IncomingPhoneNumberTollFreeListIncomingPhoneNumberTollFree } from "../funcs/api20100401IncomingPhoneNumberTollFreeListIncomingPhoneNumberTollFree.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401IncomingPhoneNumberTollFree extends ClientSDK {
  async listIncomingPhoneNumberTollFree(
    request: operations.ListIncomingPhoneNumberTollFreeRequest,
    options?: RequestOptions,
  ): Promise<operations.ListIncomingPhoneNumberTollFreeResponse> {
    return unwrapAsync(
      api20100401IncomingPhoneNumberTollFreeListIncomingPhoneNumberTollFree(
        this,
        request,
        options,
      ),
    );
  }

  async createIncomingPhoneNumberTollFree(
    request: operations.CreateIncomingPhoneNumberTollFreeRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateIncomingPhoneNumberTollFreeResponse> {
    return unwrapAsync(
      api20100401IncomingPhoneNumberTollFreeCreateIncomingPhoneNumberTollFree(
        this,
        request,
        options,
      ),
    );
  }
}
