/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401NotificationFetchNotification } from "../funcs/api20100401NotificationFetchNotification.js";
import { api20100401NotificationListNotification } from "../funcs/api20100401NotificationListNotification.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401Notification extends ClientSDK {
  /**
   * Fetch a notification belonging to the account used to make the request
   */
  async fetchNotification(
    request: operations.FetchNotificationRequest,
    options?: RequestOptions,
  ): Promise<operations.FetchNotificationResponse> {
    return unwrapAsync(api20100401NotificationFetchNotification(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a list of notifications belonging to the account used to make the request
   */
  async listNotification(
    request: operations.ListNotificationRequest,
    options?: RequestOptions,
  ): Promise<operations.ListNotificationResponse> {
    return unwrapAsync(api20100401NotificationListNotification(
      this,
      request,
      options,
    ));
  }
}
