/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401YearlyListUsageRecordYearly } from "../funcs/api20100401YearlyListUsageRecordYearly.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401Yearly extends ClientSDK {
  async listUsageRecordYearly(
    request: operations.ListUsageRecordYearlyRequest,
    options?: RequestOptions,
  ): Promise<operations.ListUsageRecordYearlyResponse> {
    return unwrapAsync(api20100401YearlyListUsageRecordYearly(
      this,
      request,
      options,
    ));
  }
}
