/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401NewSigningKeyCreateNewSigningKey } from "../funcs/api20100401NewSigningKeyCreateNewSigningKey.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401NewSigningKey extends ClientSDK {
  /**
   * Create a new Signing Key for the account making the request.
   */
  async createNewSigningKey(
    request: operations.CreateNewSigningKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateNewSigningKeyResponse> {
    return unwrapAsync(api20100401NewSigningKeyCreateNewSigningKey(
      this,
      request,
      options,
    ));
  }
}
