/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401CallCreateCall } from "../funcs/api20100401CallCreateCall.js";
import { api20100401CallDeleteCall } from "../funcs/api20100401CallDeleteCall.js";
import { api20100401CallFetchCall } from "../funcs/api20100401CallFetchCall.js";
import { api20100401CallListCall } from "../funcs/api20100401CallListCall.js";
import { api20100401CallUpdateCall } from "../funcs/api20100401CallUpdateCall.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401Call extends ClientSDK {
  /**
   * Create a new outgoing call to phones, SIP-enabled endpoints or Twilio Client connections
   */
  async createCall(
    request: operations.CreateCallRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateCallResponse> {
    return unwrapAsync(api20100401CallCreateCall(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieves a collection of calls made to and from your account
   */
  async listCall(
    request: operations.ListCallRequest,
    options?: RequestOptions,
  ): Promise<operations.ListCallResponse> {
    return unwrapAsync(api20100401CallListCall(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a Call record from your account. Once the record is deleted, it will no longer appear in the API and Account Portal logs.
   */
  async deleteCall(
    request: operations.DeleteCallRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(api20100401CallDeleteCall(
      this,
      request,
      options,
    ));
  }

  /**
   * Fetch the call specified by the provided Call SID
   */
  async fetchCall(
    request: operations.FetchCallRequest,
    options?: RequestOptions,
  ): Promise<operations.FetchCallResponse> {
    return unwrapAsync(api20100401CallFetchCall(
      this,
      request,
      options,
    ));
  }

  /**
   * Initiates a call redirect or terminates a call
   */
  async updateCall(
    request: operations.UpdateCallRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateCallResponse> {
    return unwrapAsync(api20100401CallUpdateCall(
      this,
      request,
      options,
    ));
  }
}
