/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401AuthorizedConnectAppFetchAuthorizedConnectApp } from "../funcs/api20100401AuthorizedConnectAppFetchAuthorizedConnectApp.js";
import { api20100401AuthorizedConnectAppListAuthorizedConnectApp } from "../funcs/api20100401AuthorizedConnectAppListAuthorizedConnectApp.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401AuthorizedConnectApp extends ClientSDK {
  /**
   * Fetch an instance of an authorized-connect-app
   */
  async fetchAuthorizedConnectApp(
    request: operations.FetchAuthorizedConnectAppRequest,
    options?: RequestOptions,
  ): Promise<operations.FetchAuthorizedConnectAppResponse> {
    return unwrapAsync(api20100401AuthorizedConnectAppFetchAuthorizedConnectApp(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a list of authorized-connect-apps belonging to the account used to make the request
   */
  async listAuthorizedConnectApp(
    request: operations.ListAuthorizedConnectAppRequest,
    options?: RequestOptions,
  ): Promise<operations.ListAuthorizedConnectAppResponse> {
    return unwrapAsync(api20100401AuthorizedConnectAppListAuthorizedConnectApp(
      this,
      request,
      options,
    ));
  }
}
