/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401QueueCreateQueue } from "../funcs/api20100401QueueCreateQueue.js";
import { api20100401QueueDeleteQueue } from "../funcs/api20100401QueueDeleteQueue.js";
import { api20100401QueueFetchQueue } from "../funcs/api20100401QueueFetchQueue.js";
import { api20100401QueueListQueue } from "../funcs/api20100401QueueListQueue.js";
import { api20100401QueueUpdateQueue } from "../funcs/api20100401QueueUpdateQueue.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401Queue extends ClientSDK {
  /**
   * Fetch an instance of a queue identified by the QueueSid
   */
  async fetchQueue(
    request: operations.FetchQueueRequest,
    options?: RequestOptions,
  ): Promise<operations.FetchQueueResponse> {
    return unwrapAsync(api20100401QueueFetchQueue(
      this,
      request,
      options,
    ));
  }

  /**
   * Update the queue with the new parameters
   */
  async updateQueue(
    request: operations.UpdateQueueRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateQueueResponse> {
    return unwrapAsync(api20100401QueueUpdateQueue(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove an empty queue
   */
  async deleteQueue(
    request: operations.DeleteQueueRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(api20100401QueueDeleteQueue(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a list of queues belonging to the account used to make the request
   */
  async listQueue(
    request: operations.ListQueueRequest,
    options?: RequestOptions,
  ): Promise<operations.ListQueueResponse> {
    return unwrapAsync(api20100401QueueListQueue(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a queue
   */
  async createQueue(
    request: operations.CreateQueueRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateQueueResponse> {
    return unwrapAsync(api20100401QueueCreateQueue(
      this,
      request,
      options,
    ));
  }
}
