/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { api20100401TodayListUsageRecordToday } from "../funcs/api20100401TodayListUsageRecordToday.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Api20100401Today extends ClientSDK {
  async listUsageRecordToday(
    request: operations.ListUsageRecordTodayRequest,
    options?: RequestOptions,
  ): Promise<operations.ListUsageRecordTodayResponse> {
    return unwrapAsync(api20100401TodayListUsageRecordToday(
      this,
      request,
      options,
    ));
  }
}
