/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateSipCredentialListMappingServerList = [
  "https://api.twilio.com",
] as const;

export type CreateSipCredentialListMappingCreateSipCredentialListMappingRequest =
  {
    /**
     * A 34 character string that uniquely identifies the CredentialList resource to map to the SIP domain.
     */
    credentialListSid: string;
  };

export type CreateSipCredentialListMappingRequest = {
  /**
   * The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
   */
  accountSid: string;
  /**
   * A 34 character string that uniquely identifies the SIP Domain for which the CredentialList resource will be mapped.
   */
  domainSid: string;
  requestBody?:
    | CreateSipCredentialListMappingCreateSipCredentialListMappingRequest
    | undefined;
};

export type CreateSipCredentialListMappingResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountSipSipDomainSipCredentialListMapping;
};

/** @internal */
export const CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$inboundSchema:
  z.ZodType<
    CreateSipCredentialListMappingCreateSipCredentialListMappingRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    CredentialListSid: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "CredentialListSid": "credentialListSid",
    });
  });

/** @internal */
export type CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$Outbound =
  {
    CredentialListSid: string;
  };

/** @internal */
export const CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$outboundSchema:
  z.ZodType<
    CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$Outbound,
    z.ZodTypeDef,
    CreateSipCredentialListMappingCreateSipCredentialListMappingRequest
  > = z.object({
    credentialListSid: z.string(),
  }).transform((v) => {
    return remap$(v, {
      credentialListSid: "CredentialListSid",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$ {
  /** @deprecated use `CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$inboundSchema` instead. */
  export const inboundSchema =
    CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$inboundSchema;
  /** @deprecated use `CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$outboundSchema;
  /** @deprecated use `CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$Outbound` instead. */
  export type Outbound =
    CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$Outbound;
}

export function createSipCredentialListMappingCreateSipCredentialListMappingRequestToJSON(
  createSipCredentialListMappingCreateSipCredentialListMappingRequest:
    CreateSipCredentialListMappingCreateSipCredentialListMappingRequest,
): string {
  return JSON.stringify(
    CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$outboundSchema
      .parse(
        createSipCredentialListMappingCreateSipCredentialListMappingRequest,
      ),
  );
}

export function createSipCredentialListMappingCreateSipCredentialListMappingRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateSipCredentialListMappingCreateSipCredentialListMappingRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreateSipCredentialListMappingCreateSipCredentialListMappingRequest' from JSON`,
  );
}

/** @internal */
export const CreateSipCredentialListMappingRequest$inboundSchema: z.ZodType<
  CreateSipCredentialListMappingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  DomainSid: z.string(),
  RequestBody: z.lazy(() =>
    CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "DomainSid": "domainSid",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type CreateSipCredentialListMappingRequest$Outbound = {
  AccountSid: string;
  DomainSid: string;
  RequestBody?:
    | CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$Outbound
    | undefined;
};

/** @internal */
export const CreateSipCredentialListMappingRequest$outboundSchema: z.ZodType<
  CreateSipCredentialListMappingRequest$Outbound,
  z.ZodTypeDef,
  CreateSipCredentialListMappingRequest
> = z.object({
  accountSid: z.string(),
  domainSid: z.string(),
  requestBody: z.lazy(() =>
    CreateSipCredentialListMappingCreateSipCredentialListMappingRequest$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    domainSid: "DomainSid",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSipCredentialListMappingRequest$ {
  /** @deprecated use `CreateSipCredentialListMappingRequest$inboundSchema` instead. */
  export const inboundSchema =
    CreateSipCredentialListMappingRequest$inboundSchema;
  /** @deprecated use `CreateSipCredentialListMappingRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateSipCredentialListMappingRequest$outboundSchema;
  /** @deprecated use `CreateSipCredentialListMappingRequest$Outbound` instead. */
  export type Outbound = CreateSipCredentialListMappingRequest$Outbound;
}

export function createSipCredentialListMappingRequestToJSON(
  createSipCredentialListMappingRequest: CreateSipCredentialListMappingRequest,
): string {
  return JSON.stringify(
    CreateSipCredentialListMappingRequest$outboundSchema.parse(
      createSipCredentialListMappingRequest,
    ),
  );
}

export function createSipCredentialListMappingRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateSipCredentialListMappingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateSipCredentialListMappingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSipCredentialListMappingRequest' from JSON`,
  );
}

/** @internal */
export const CreateSipCredentialListMappingResponse$inboundSchema: z.ZodType<
  CreateSipCredentialListMappingResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result:
    components
      .ApiV2010AccountSipSipDomainSipCredentialListMapping$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateSipCredentialListMappingResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    components.ApiV2010AccountSipSipDomainSipCredentialListMapping$Outbound;
};

/** @internal */
export const CreateSipCredentialListMappingResponse$outboundSchema: z.ZodType<
  CreateSipCredentialListMappingResponse$Outbound,
  z.ZodTypeDef,
  CreateSipCredentialListMappingResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result:
    components
      .ApiV2010AccountSipSipDomainSipCredentialListMapping$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSipCredentialListMappingResponse$ {
  /** @deprecated use `CreateSipCredentialListMappingResponse$inboundSchema` instead. */
  export const inboundSchema =
    CreateSipCredentialListMappingResponse$inboundSchema;
  /** @deprecated use `CreateSipCredentialListMappingResponse$outboundSchema` instead. */
  export const outboundSchema =
    CreateSipCredentialListMappingResponse$outboundSchema;
  /** @deprecated use `CreateSipCredentialListMappingResponse$Outbound` instead. */
  export type Outbound = CreateSipCredentialListMappingResponse$Outbound;
}

export function createSipCredentialListMappingResponseToJSON(
  createSipCredentialListMappingResponse:
    CreateSipCredentialListMappingResponse,
): string {
  return JSON.stringify(
    CreateSipCredentialListMappingResponse$outboundSchema.parse(
      createSipCredentialListMappingResponse,
    ),
  );
}

export function createSipCredentialListMappingResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSipCredentialListMappingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateSipCredentialListMappingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSipCredentialListMappingResponse' from JSON`,
  );
}
