/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateAccountServerList = [
  "https://api.twilio.com",
] as const;

export type CreateAccountCreateAccountRequest = {
  /**
   * A human readable description of the account to create, defaults to `SubAccount Created at {YYYY-MM-DD HH:MM meridian}`
   */
  friendlyName?: string | undefined;
};

export type CreateAccountResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010Account;
};

/** @internal */
export const CreateAccountCreateAccountRequest$inboundSchema: z.ZodType<
  CreateAccountCreateAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  FriendlyName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "FriendlyName": "friendlyName",
  });
});

/** @internal */
export type CreateAccountCreateAccountRequest$Outbound = {
  FriendlyName?: string | undefined;
};

/** @internal */
export const CreateAccountCreateAccountRequest$outboundSchema: z.ZodType<
  CreateAccountCreateAccountRequest$Outbound,
  z.ZodTypeDef,
  CreateAccountCreateAccountRequest
> = z.object({
  friendlyName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    friendlyName: "FriendlyName",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateAccountCreateAccountRequest$ {
  /** @deprecated use `CreateAccountCreateAccountRequest$inboundSchema` instead. */
  export const inboundSchema = CreateAccountCreateAccountRequest$inboundSchema;
  /** @deprecated use `CreateAccountCreateAccountRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateAccountCreateAccountRequest$outboundSchema;
  /** @deprecated use `CreateAccountCreateAccountRequest$Outbound` instead. */
  export type Outbound = CreateAccountCreateAccountRequest$Outbound;
}

export function createAccountCreateAccountRequestToJSON(
  createAccountCreateAccountRequest: CreateAccountCreateAccountRequest,
): string {
  return JSON.stringify(
    CreateAccountCreateAccountRequest$outboundSchema.parse(
      createAccountCreateAccountRequest,
    ),
  );
}

export function createAccountCreateAccountRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateAccountCreateAccountRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAccountCreateAccountRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAccountCreateAccountRequest' from JSON`,
  );
}

/** @internal */
export const CreateAccountResponse$inboundSchema: z.ZodType<
  CreateAccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010Account$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateAccountResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010Account$Outbound;
};

/** @internal */
export const CreateAccountResponse$outboundSchema: z.ZodType<
  CreateAccountResponse$Outbound,
  z.ZodTypeDef,
  CreateAccountResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010Account$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateAccountResponse$ {
  /** @deprecated use `CreateAccountResponse$inboundSchema` instead. */
  export const inboundSchema = CreateAccountResponse$inboundSchema;
  /** @deprecated use `CreateAccountResponse$outboundSchema` instead. */
  export const outboundSchema = CreateAccountResponse$outboundSchema;
  /** @deprecated use `CreateAccountResponse$Outbound` instead. */
  export type Outbound = CreateAccountResponse$Outbound;
}

export function createAccountResponseToJSON(
  createAccountResponse: CreateAccountResponse,
): string {
  return JSON.stringify(
    CreateAccountResponse$outboundSchema.parse(createAccountResponse),
  );
}

export function createAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAccountResponse' from JSON`,
  );
}
