/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateIncomingPhoneNumberLocalServerList = [
  "https://api.twilio.com",
] as const;

/**
 * The HTTP method that we should use to call `sms_fallback_url`. Can be: `GET` or `POST` and defaults to `POST`.
 */
export const CreateIncomingPhoneNumberLocalSmsFallbackMethod = {
  Get: "GET",
  Post: "POST",
} as const;
/**
 * The HTTP method that we should use to call `sms_fallback_url`. Can be: `GET` or `POST` and defaults to `POST`.
 */
export type CreateIncomingPhoneNumberLocalSmsFallbackMethod = ClosedEnum<
  typeof CreateIncomingPhoneNumberLocalSmsFallbackMethod
>;

/**
 * The HTTP method that we should use to call `sms_url`. Can be: `GET` or `POST` and defaults to `POST`.
 */
export const CreateIncomingPhoneNumberLocalSmsMethod = {
  Get: "GET",
  Post: "POST",
} as const;
/**
 * The HTTP method that we should use to call `sms_url`. Can be: `GET` or `POST` and defaults to `POST`.
 */
export type CreateIncomingPhoneNumberLocalSmsMethod = ClosedEnum<
  typeof CreateIncomingPhoneNumberLocalSmsMethod
>;

/**
 * The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST` and defaults to `POST`.
 */
export const CreateIncomingPhoneNumberLocalStatusCallbackMethod = {
  Get: "GET",
  Post: "POST",
} as const;
/**
 * The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST` and defaults to `POST`.
 */
export type CreateIncomingPhoneNumberLocalStatusCallbackMethod = ClosedEnum<
  typeof CreateIncomingPhoneNumberLocalStatusCallbackMethod
>;

/**
 * The HTTP method that we should use to call `voice_fallback_url`. Can be: `GET` or `POST` and defaults to `POST`.
 */
export const CreateIncomingPhoneNumberLocalVoiceFallbackMethod = {
  Get: "GET",
  Post: "POST",
} as const;
/**
 * The HTTP method that we should use to call `voice_fallback_url`. Can be: `GET` or `POST` and defaults to `POST`.
 */
export type CreateIncomingPhoneNumberLocalVoiceFallbackMethod = ClosedEnum<
  typeof CreateIncomingPhoneNumberLocalVoiceFallbackMethod
>;

/**
 * The HTTP method that we should use to call `voice_url`. Can be: `GET` or `POST` and defaults to `POST`.
 */
export const CreateIncomingPhoneNumberLocalVoiceMethod = {
  Get: "GET",
  Post: "POST",
} as const;
/**
 * The HTTP method that we should use to call `voice_url`. Can be: `GET` or `POST` and defaults to `POST`.
 */
export type CreateIncomingPhoneNumberLocalVoiceMethod = ClosedEnum<
  typeof CreateIncomingPhoneNumberLocalVoiceMethod
>;

export type CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest =
  {
    /**
     * The phone number to purchase specified in [E.164](https://www.twilio.com/docs/glossary/what-e164) format.  E.164 phone numbers consist of a + followed by the country code and subscriber number without punctuation characters. For example, +14155551234.
     */
    phoneNumber: string;
    /**
     * The API version to use for incoming calls made to the new phone number. The default is `2010-04-01`.
     */
    apiVersion?: string | undefined;
    /**
     * A descriptive string that you created to describe the new phone number. It can be up to 64 characters long. By default, this is a formatted version of the phone number.
     */
    friendlyName?: string | undefined;
    /**
     * The SID of the application that should handle SMS messages sent to the new phone number. If an `sms_application_sid` is present, we ignore all of the `sms_*_url` urls and use those set on the application.
     */
    smsApplicationSid?: string | undefined;
    /**
     * The HTTP method that we should use to call `sms_fallback_url`. Can be: `GET` or `POST` and defaults to `POST`.
     */
    smsFallbackMethod?:
      | CreateIncomingPhoneNumberLocalSmsFallbackMethod
      | undefined;
    /**
     * The URL that we should call when an error occurs while requesting or executing the TwiML defined by `sms_url`.
     */
    smsFallbackUrl?: string | undefined;
    /**
     * The HTTP method that we should use to call `sms_url`. Can be: `GET` or `POST` and defaults to `POST`.
     */
    smsMethod?: CreateIncomingPhoneNumberLocalSmsMethod | undefined;
    /**
     * The URL we should call when the new phone number receives an incoming SMS message.
     */
    smsUrl?: string | undefined;
    /**
     * The URL we should call using the `status_callback_method` to send status information to your application.
     */
    statusCallback?: string | undefined;
    /**
     * The HTTP method we should use to call `status_callback`. Can be: `GET` or `POST` and defaults to `POST`.
     */
    statusCallbackMethod?:
      | CreateIncomingPhoneNumberLocalStatusCallbackMethod
      | undefined;
    /**
     * The SID of the application we should use to handle calls to the new phone number. If a `voice_application_sid` is present, we ignore all of the voice urls and use only those set on the application. Setting a `voice_application_sid` will automatically delete your `trunk_sid` and vice versa.
     */
    voiceApplicationSid?: string | undefined;
    /**
     * Whether to lookup the caller's name from the CNAM database and post it to your app. Can be: `true` or `false` and defaults to `false`.
     */
    voiceCallerIdLookup?: boolean | undefined;
    /**
     * The HTTP method that we should use to call `voice_fallback_url`. Can be: `GET` or `POST` and defaults to `POST`.
     */
    voiceFallbackMethod?:
      | CreateIncomingPhoneNumberLocalVoiceFallbackMethod
      | undefined;
    /**
     * The URL that we should call when an error occurs retrieving or executing the TwiML requested by `url`.
     */
    voiceFallbackUrl?: string | undefined;
    /**
     * The HTTP method that we should use to call `voice_url`. Can be: `GET` or `POST` and defaults to `POST`.
     */
    voiceMethod?: CreateIncomingPhoneNumberLocalVoiceMethod | undefined;
    /**
     * The URL that we should call to answer a call to the new phone number. The `voice_url` will not be called if a `voice_application_sid` or a `trunk_sid` is set.
     */
    voiceUrl?: string | undefined;
    /**
     * The SID of the Identity resource that we should associate with the new phone number. Some regions require an identity to meet local regulations.
     */
    identitySid?: string | undefined;
    /**
     * The SID of the Address resource we should associate with the new phone number. Some regions require addresses to meet local regulations.
     */
    addressSid?: string | undefined;
    emergencyStatus?:
      | components.IncomingPhoneNumberLocalEnumEmergencyStatus
      | undefined;
    /**
     * The SID of the emergency address configuration to use for emergency calling from the new phone number.
     */
    emergencyAddressSid?: string | undefined;
    /**
     * The SID of the Trunk we should use to handle calls to the new phone number. If a `trunk_sid` is present, we ignore all of the voice urls and voice applications and use only those set on the Trunk. Setting a `trunk_sid` will automatically delete your `voice_application_sid` and vice versa.
     */
    trunkSid?: string | undefined;
    voiceReceiveMode?:
      | components.IncomingPhoneNumberLocalEnumVoiceReceiveMode
      | undefined;
    /**
     * The SID of the Bundle resource that you associate with the phone number. Some regions require a Bundle to meet local Regulations.
     */
    bundleSid?: string | undefined;
  };

export type CreateIncomingPhoneNumberLocalRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
   */
  accountSid: string;
  requestBody?:
    | CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest
    | undefined;
};

export type CreateIncomingPhoneNumberLocalResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberLocal;
};

/** @internal */
export const CreateIncomingPhoneNumberLocalSmsFallbackMethod$inboundSchema:
  z.ZodNativeEnum<typeof CreateIncomingPhoneNumberLocalSmsFallbackMethod> = z
    .nativeEnum(CreateIncomingPhoneNumberLocalSmsFallbackMethod);

/** @internal */
export const CreateIncomingPhoneNumberLocalSmsFallbackMethod$outboundSchema:
  z.ZodNativeEnum<typeof CreateIncomingPhoneNumberLocalSmsFallbackMethod> =
    CreateIncomingPhoneNumberLocalSmsFallbackMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateIncomingPhoneNumberLocalSmsFallbackMethod$ {
  /** @deprecated use `CreateIncomingPhoneNumberLocalSmsFallbackMethod$inboundSchema` instead. */
  export const inboundSchema =
    CreateIncomingPhoneNumberLocalSmsFallbackMethod$inboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalSmsFallbackMethod$outboundSchema` instead. */
  export const outboundSchema =
    CreateIncomingPhoneNumberLocalSmsFallbackMethod$outboundSchema;
}

/** @internal */
export const CreateIncomingPhoneNumberLocalSmsMethod$inboundSchema:
  z.ZodNativeEnum<typeof CreateIncomingPhoneNumberLocalSmsMethod> = z
    .nativeEnum(CreateIncomingPhoneNumberLocalSmsMethod);

/** @internal */
export const CreateIncomingPhoneNumberLocalSmsMethod$outboundSchema:
  z.ZodNativeEnum<typeof CreateIncomingPhoneNumberLocalSmsMethod> =
    CreateIncomingPhoneNumberLocalSmsMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateIncomingPhoneNumberLocalSmsMethod$ {
  /** @deprecated use `CreateIncomingPhoneNumberLocalSmsMethod$inboundSchema` instead. */
  export const inboundSchema =
    CreateIncomingPhoneNumberLocalSmsMethod$inboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalSmsMethod$outboundSchema` instead. */
  export const outboundSchema =
    CreateIncomingPhoneNumberLocalSmsMethod$outboundSchema;
}

/** @internal */
export const CreateIncomingPhoneNumberLocalStatusCallbackMethod$inboundSchema:
  z.ZodNativeEnum<typeof CreateIncomingPhoneNumberLocalStatusCallbackMethod> = z
    .nativeEnum(CreateIncomingPhoneNumberLocalStatusCallbackMethod);

/** @internal */
export const CreateIncomingPhoneNumberLocalStatusCallbackMethod$outboundSchema:
  z.ZodNativeEnum<typeof CreateIncomingPhoneNumberLocalStatusCallbackMethod> =
    CreateIncomingPhoneNumberLocalStatusCallbackMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateIncomingPhoneNumberLocalStatusCallbackMethod$ {
  /** @deprecated use `CreateIncomingPhoneNumberLocalStatusCallbackMethod$inboundSchema` instead. */
  export const inboundSchema =
    CreateIncomingPhoneNumberLocalStatusCallbackMethod$inboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalStatusCallbackMethod$outboundSchema` instead. */
  export const outboundSchema =
    CreateIncomingPhoneNumberLocalStatusCallbackMethod$outboundSchema;
}

/** @internal */
export const CreateIncomingPhoneNumberLocalVoiceFallbackMethod$inboundSchema:
  z.ZodNativeEnum<typeof CreateIncomingPhoneNumberLocalVoiceFallbackMethod> = z
    .nativeEnum(CreateIncomingPhoneNumberLocalVoiceFallbackMethod);

/** @internal */
export const CreateIncomingPhoneNumberLocalVoiceFallbackMethod$outboundSchema:
  z.ZodNativeEnum<typeof CreateIncomingPhoneNumberLocalVoiceFallbackMethod> =
    CreateIncomingPhoneNumberLocalVoiceFallbackMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateIncomingPhoneNumberLocalVoiceFallbackMethod$ {
  /** @deprecated use `CreateIncomingPhoneNumberLocalVoiceFallbackMethod$inboundSchema` instead. */
  export const inboundSchema =
    CreateIncomingPhoneNumberLocalVoiceFallbackMethod$inboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalVoiceFallbackMethod$outboundSchema` instead. */
  export const outboundSchema =
    CreateIncomingPhoneNumberLocalVoiceFallbackMethod$outboundSchema;
}

/** @internal */
export const CreateIncomingPhoneNumberLocalVoiceMethod$inboundSchema:
  z.ZodNativeEnum<typeof CreateIncomingPhoneNumberLocalVoiceMethod> = z
    .nativeEnum(CreateIncomingPhoneNumberLocalVoiceMethod);

/** @internal */
export const CreateIncomingPhoneNumberLocalVoiceMethod$outboundSchema:
  z.ZodNativeEnum<typeof CreateIncomingPhoneNumberLocalVoiceMethod> =
    CreateIncomingPhoneNumberLocalVoiceMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateIncomingPhoneNumberLocalVoiceMethod$ {
  /** @deprecated use `CreateIncomingPhoneNumberLocalVoiceMethod$inboundSchema` instead. */
  export const inboundSchema =
    CreateIncomingPhoneNumberLocalVoiceMethod$inboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalVoiceMethod$outboundSchema` instead. */
  export const outboundSchema =
    CreateIncomingPhoneNumberLocalVoiceMethod$outboundSchema;
}

/** @internal */
export const CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$inboundSchema:
  z.ZodType<
    CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    PhoneNumber: z.string(),
    ApiVersion: z.string().optional(),
    FriendlyName: z.string().optional(),
    SmsApplicationSid: z.string().optional(),
    SmsFallbackMethod:
      CreateIncomingPhoneNumberLocalSmsFallbackMethod$inboundSchema.optional(),
    SmsFallbackUrl: z.string().optional(),
    SmsMethod: CreateIncomingPhoneNumberLocalSmsMethod$inboundSchema.optional(),
    SmsUrl: z.string().optional(),
    StatusCallback: z.string().optional(),
    StatusCallbackMethod:
      CreateIncomingPhoneNumberLocalStatusCallbackMethod$inboundSchema
        .optional(),
    VoiceApplicationSid: z.string().optional(),
    VoiceCallerIdLookup: z.boolean().optional(),
    VoiceFallbackMethod:
      CreateIncomingPhoneNumberLocalVoiceFallbackMethod$inboundSchema
        .optional(),
    VoiceFallbackUrl: z.string().optional(),
    VoiceMethod: CreateIncomingPhoneNumberLocalVoiceMethod$inboundSchema
      .optional(),
    VoiceUrl: z.string().optional(),
    IdentitySid: z.string().optional(),
    AddressSid: z.string().optional(),
    EmergencyStatus: components
      .IncomingPhoneNumberLocalEnumEmergencyStatus$inboundSchema.optional(),
    EmergencyAddressSid: z.string().optional(),
    TrunkSid: z.string().optional(),
    VoiceReceiveMode: components
      .IncomingPhoneNumberLocalEnumVoiceReceiveMode$inboundSchema.optional(),
    BundleSid: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "PhoneNumber": "phoneNumber",
      "ApiVersion": "apiVersion",
      "FriendlyName": "friendlyName",
      "SmsApplicationSid": "smsApplicationSid",
      "SmsFallbackMethod": "smsFallbackMethod",
      "SmsFallbackUrl": "smsFallbackUrl",
      "SmsMethod": "smsMethod",
      "SmsUrl": "smsUrl",
      "StatusCallback": "statusCallback",
      "StatusCallbackMethod": "statusCallbackMethod",
      "VoiceApplicationSid": "voiceApplicationSid",
      "VoiceCallerIdLookup": "voiceCallerIdLookup",
      "VoiceFallbackMethod": "voiceFallbackMethod",
      "VoiceFallbackUrl": "voiceFallbackUrl",
      "VoiceMethod": "voiceMethod",
      "VoiceUrl": "voiceUrl",
      "IdentitySid": "identitySid",
      "AddressSid": "addressSid",
      "EmergencyStatus": "emergencyStatus",
      "EmergencyAddressSid": "emergencyAddressSid",
      "TrunkSid": "trunkSid",
      "VoiceReceiveMode": "voiceReceiveMode",
      "BundleSid": "bundleSid",
    });
  });

/** @internal */
export type CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$Outbound =
  {
    PhoneNumber: string;
    ApiVersion?: string | undefined;
    FriendlyName?: string | undefined;
    SmsApplicationSid?: string | undefined;
    SmsFallbackMethod?: string | undefined;
    SmsFallbackUrl?: string | undefined;
    SmsMethod?: string | undefined;
    SmsUrl?: string | undefined;
    StatusCallback?: string | undefined;
    StatusCallbackMethod?: string | undefined;
    VoiceApplicationSid?: string | undefined;
    VoiceCallerIdLookup?: boolean | undefined;
    VoiceFallbackMethod?: string | undefined;
    VoiceFallbackUrl?: string | undefined;
    VoiceMethod?: string | undefined;
    VoiceUrl?: string | undefined;
    IdentitySid?: string | undefined;
    AddressSid?: string | undefined;
    EmergencyStatus?: string | undefined;
    EmergencyAddressSid?: string | undefined;
    TrunkSid?: string | undefined;
    VoiceReceiveMode?: string | undefined;
    BundleSid?: string | undefined;
  };

/** @internal */
export const CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$outboundSchema:
  z.ZodType<
    CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$Outbound,
    z.ZodTypeDef,
    CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest
  > = z.object({
    phoneNumber: z.string(),
    apiVersion: z.string().optional(),
    friendlyName: z.string().optional(),
    smsApplicationSid: z.string().optional(),
    smsFallbackMethod:
      CreateIncomingPhoneNumberLocalSmsFallbackMethod$outboundSchema.optional(),
    smsFallbackUrl: z.string().optional(),
    smsMethod: CreateIncomingPhoneNumberLocalSmsMethod$outboundSchema
      .optional(),
    smsUrl: z.string().optional(),
    statusCallback: z.string().optional(),
    statusCallbackMethod:
      CreateIncomingPhoneNumberLocalStatusCallbackMethod$outboundSchema
        .optional(),
    voiceApplicationSid: z.string().optional(),
    voiceCallerIdLookup: z.boolean().optional(),
    voiceFallbackMethod:
      CreateIncomingPhoneNumberLocalVoiceFallbackMethod$outboundSchema
        .optional(),
    voiceFallbackUrl: z.string().optional(),
    voiceMethod: CreateIncomingPhoneNumberLocalVoiceMethod$outboundSchema
      .optional(),
    voiceUrl: z.string().optional(),
    identitySid: z.string().optional(),
    addressSid: z.string().optional(),
    emergencyStatus: components
      .IncomingPhoneNumberLocalEnumEmergencyStatus$outboundSchema.optional(),
    emergencyAddressSid: z.string().optional(),
    trunkSid: z.string().optional(),
    voiceReceiveMode: components
      .IncomingPhoneNumberLocalEnumVoiceReceiveMode$outboundSchema.optional(),
    bundleSid: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      phoneNumber: "PhoneNumber",
      apiVersion: "ApiVersion",
      friendlyName: "FriendlyName",
      smsApplicationSid: "SmsApplicationSid",
      smsFallbackMethod: "SmsFallbackMethod",
      smsFallbackUrl: "SmsFallbackUrl",
      smsMethod: "SmsMethod",
      smsUrl: "SmsUrl",
      statusCallback: "StatusCallback",
      statusCallbackMethod: "StatusCallbackMethod",
      voiceApplicationSid: "VoiceApplicationSid",
      voiceCallerIdLookup: "VoiceCallerIdLookup",
      voiceFallbackMethod: "VoiceFallbackMethod",
      voiceFallbackUrl: "VoiceFallbackUrl",
      voiceMethod: "VoiceMethod",
      voiceUrl: "VoiceUrl",
      identitySid: "IdentitySid",
      addressSid: "AddressSid",
      emergencyStatus: "EmergencyStatus",
      emergencyAddressSid: "EmergencyAddressSid",
      trunkSid: "TrunkSid",
      voiceReceiveMode: "VoiceReceiveMode",
      bundleSid: "BundleSid",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$ {
  /** @deprecated use `CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$inboundSchema` instead. */
  export const inboundSchema =
    CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$inboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$outboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$Outbound` instead. */
  export type Outbound =
    CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$Outbound;
}

export function createIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequestToJSON(
  createIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest:
    CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest,
): string {
  return JSON.stringify(
    CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$outboundSchema
      .parse(
        createIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest,
      ),
  );
}

export function createIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest' from JSON`,
  );
}

/** @internal */
export const CreateIncomingPhoneNumberLocalRequest$inboundSchema: z.ZodType<
  CreateIncomingPhoneNumberLocalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  RequestBody: z.lazy(() =>
    CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type CreateIncomingPhoneNumberLocalRequest$Outbound = {
  AccountSid: string;
  RequestBody?:
    | CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$Outbound
    | undefined;
};

/** @internal */
export const CreateIncomingPhoneNumberLocalRequest$outboundSchema: z.ZodType<
  CreateIncomingPhoneNumberLocalRequest$Outbound,
  z.ZodTypeDef,
  CreateIncomingPhoneNumberLocalRequest
> = z.object({
  accountSid: z.string(),
  requestBody: z.lazy(() =>
    CreateIncomingPhoneNumberLocalCreateIncomingPhoneNumberLocalRequest$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateIncomingPhoneNumberLocalRequest$ {
  /** @deprecated use `CreateIncomingPhoneNumberLocalRequest$inboundSchema` instead. */
  export const inboundSchema =
    CreateIncomingPhoneNumberLocalRequest$inboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateIncomingPhoneNumberLocalRequest$outboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalRequest$Outbound` instead. */
  export type Outbound = CreateIncomingPhoneNumberLocalRequest$Outbound;
}

export function createIncomingPhoneNumberLocalRequestToJSON(
  createIncomingPhoneNumberLocalRequest: CreateIncomingPhoneNumberLocalRequest,
): string {
  return JSON.stringify(
    CreateIncomingPhoneNumberLocalRequest$outboundSchema.parse(
      createIncomingPhoneNumberLocalRequest,
    ),
  );
}

export function createIncomingPhoneNumberLocalRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateIncomingPhoneNumberLocalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateIncomingPhoneNumberLocalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateIncomingPhoneNumberLocalRequest' from JSON`,
  );
}

/** @internal */
export const CreateIncomingPhoneNumberLocalResponse$inboundSchema: z.ZodType<
  CreateIncomingPhoneNumberLocalResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result:
    components
      .ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberLocal$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateIncomingPhoneNumberLocalResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    components.ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberLocal$Outbound;
};

/** @internal */
export const CreateIncomingPhoneNumberLocalResponse$outboundSchema: z.ZodType<
  CreateIncomingPhoneNumberLocalResponse$Outbound,
  z.ZodTypeDef,
  CreateIncomingPhoneNumberLocalResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result:
    components
      .ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberLocal$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateIncomingPhoneNumberLocalResponse$ {
  /** @deprecated use `CreateIncomingPhoneNumberLocalResponse$inboundSchema` instead. */
  export const inboundSchema =
    CreateIncomingPhoneNumberLocalResponse$inboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalResponse$outboundSchema` instead. */
  export const outboundSchema =
    CreateIncomingPhoneNumberLocalResponse$outboundSchema;
  /** @deprecated use `CreateIncomingPhoneNumberLocalResponse$Outbound` instead. */
  export type Outbound = CreateIncomingPhoneNumberLocalResponse$Outbound;
}

export function createIncomingPhoneNumberLocalResponseToJSON(
  createIncomingPhoneNumberLocalResponse:
    CreateIncomingPhoneNumberLocalResponse,
): string {
  return JSON.stringify(
    CreateIncomingPhoneNumberLocalResponse$outboundSchema.parse(
      createIncomingPhoneNumberLocalResponse,
    ),
  );
}

export function createIncomingPhoneNumberLocalResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateIncomingPhoneNumberLocalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateIncomingPhoneNumberLocalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateIncomingPhoneNumberLocalResponse' from JSON`,
  );
}
