/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateSipIpAccessControlListServerList = [
  "https://api.twilio.com",
] as const;

export type CreateSipIpAccessControlListCreateSipIpAccessControlListRequest = {
  /**
   * A human readable descriptive text that describes the IpAccessControlList, up to 255 characters long.
   */
  friendlyName: string;
};

export type CreateSipIpAccessControlListRequest = {
  /**
   * The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
   */
  accountSid: string;
  requestBody?:
    | CreateSipIpAccessControlListCreateSipIpAccessControlListRequest
    | undefined;
};

export type CreateSipIpAccessControlListResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountSipSipIpAccessControlList;
};

/** @internal */
export const CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$inboundSchema:
  z.ZodType<
    CreateSipIpAccessControlListCreateSipIpAccessControlListRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    FriendlyName: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "FriendlyName": "friendlyName",
    });
  });

/** @internal */
export type CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$Outbound =
  {
    FriendlyName: string;
  };

/** @internal */
export const CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$outboundSchema:
  z.ZodType<
    CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$Outbound,
    z.ZodTypeDef,
    CreateSipIpAccessControlListCreateSipIpAccessControlListRequest
  > = z.object({
    friendlyName: z.string(),
  }).transform((v) => {
    return remap$(v, {
      friendlyName: "FriendlyName",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$ {
  /** @deprecated use `CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$inboundSchema` instead. */
  export const inboundSchema =
    CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$inboundSchema;
  /** @deprecated use `CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$outboundSchema;
  /** @deprecated use `CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$Outbound` instead. */
  export type Outbound =
    CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$Outbound;
}

export function createSipIpAccessControlListCreateSipIpAccessControlListRequestToJSON(
  createSipIpAccessControlListCreateSipIpAccessControlListRequest:
    CreateSipIpAccessControlListCreateSipIpAccessControlListRequest,
): string {
  return JSON.stringify(
    CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$outboundSchema
      .parse(createSipIpAccessControlListCreateSipIpAccessControlListRequest),
  );
}

export function createSipIpAccessControlListCreateSipIpAccessControlListRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateSipIpAccessControlListCreateSipIpAccessControlListRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreateSipIpAccessControlListCreateSipIpAccessControlListRequest' from JSON`,
  );
}

/** @internal */
export const CreateSipIpAccessControlListRequest$inboundSchema: z.ZodType<
  CreateSipIpAccessControlListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  RequestBody: z.lazy(() =>
    CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type CreateSipIpAccessControlListRequest$Outbound = {
  AccountSid: string;
  RequestBody?:
    | CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$Outbound
    | undefined;
};

/** @internal */
export const CreateSipIpAccessControlListRequest$outboundSchema: z.ZodType<
  CreateSipIpAccessControlListRequest$Outbound,
  z.ZodTypeDef,
  CreateSipIpAccessControlListRequest
> = z.object({
  accountSid: z.string(),
  requestBody: z.lazy(() =>
    CreateSipIpAccessControlListCreateSipIpAccessControlListRequest$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSipIpAccessControlListRequest$ {
  /** @deprecated use `CreateSipIpAccessControlListRequest$inboundSchema` instead. */
  export const inboundSchema =
    CreateSipIpAccessControlListRequest$inboundSchema;
  /** @deprecated use `CreateSipIpAccessControlListRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateSipIpAccessControlListRequest$outboundSchema;
  /** @deprecated use `CreateSipIpAccessControlListRequest$Outbound` instead. */
  export type Outbound = CreateSipIpAccessControlListRequest$Outbound;
}

export function createSipIpAccessControlListRequestToJSON(
  createSipIpAccessControlListRequest: CreateSipIpAccessControlListRequest,
): string {
  return JSON.stringify(
    CreateSipIpAccessControlListRequest$outboundSchema.parse(
      createSipIpAccessControlListRequest,
    ),
  );
}

export function createSipIpAccessControlListRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateSipIpAccessControlListRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateSipIpAccessControlListRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSipIpAccessControlListRequest' from JSON`,
  );
}

/** @internal */
export const CreateSipIpAccessControlListResponse$inboundSchema: z.ZodType<
  CreateSipIpAccessControlListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountSipSipIpAccessControlList$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type CreateSipIpAccessControlListResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountSipSipIpAccessControlList$Outbound;
};

/** @internal */
export const CreateSipIpAccessControlListResponse$outboundSchema: z.ZodType<
  CreateSipIpAccessControlListResponse$Outbound,
  z.ZodTypeDef,
  CreateSipIpAccessControlListResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountSipSipIpAccessControlList$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSipIpAccessControlListResponse$ {
  /** @deprecated use `CreateSipIpAccessControlListResponse$inboundSchema` instead. */
  export const inboundSchema =
    CreateSipIpAccessControlListResponse$inboundSchema;
  /** @deprecated use `CreateSipIpAccessControlListResponse$outboundSchema` instead. */
  export const outboundSchema =
    CreateSipIpAccessControlListResponse$outboundSchema;
  /** @deprecated use `CreateSipIpAccessControlListResponse$Outbound` instead. */
  export type Outbound = CreateSipIpAccessControlListResponse$Outbound;
}

export function createSipIpAccessControlListResponseToJSON(
  createSipIpAccessControlListResponse: CreateSipIpAccessControlListResponse,
): string {
  return JSON.stringify(
    CreateSipIpAccessControlListResponse$outboundSchema.parse(
      createSipIpAccessControlListResponse,
    ),
  );
}

export function createSipIpAccessControlListResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSipIpAccessControlListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateSipIpAccessControlListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSipIpAccessControlListResponse' from JSON`,
  );
}
