/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DeleteSipAuthCallsCredentialListMappingServerList = [
  "https://api.twilio.com",
] as const;

export type DeleteSipAuthCallsCredentialListMappingRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the CredentialListMapping resources to delete.
   */
  accountSid: string;
  /**
   * The SID of the SIP domain that contains the resource to delete.
   */
  domainSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the CredentialListMapping resource to delete.
   */
  sid: string;
};

/** @internal */
export const DeleteSipAuthCallsCredentialListMappingRequest$inboundSchema:
  z.ZodType<
    DeleteSipAuthCallsCredentialListMappingRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    AccountSid: z.string(),
    DomainSid: z.string(),
    Sid: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "AccountSid": "accountSid",
      "DomainSid": "domainSid",
      "Sid": "sid",
    });
  });

/** @internal */
export type DeleteSipAuthCallsCredentialListMappingRequest$Outbound = {
  AccountSid: string;
  DomainSid: string;
  Sid: string;
};

/** @internal */
export const DeleteSipAuthCallsCredentialListMappingRequest$outboundSchema:
  z.ZodType<
    DeleteSipAuthCallsCredentialListMappingRequest$Outbound,
    z.ZodTypeDef,
    DeleteSipAuthCallsCredentialListMappingRequest
  > = z.object({
    accountSid: z.string(),
    domainSid: z.string(),
    sid: z.string(),
  }).transform((v) => {
    return remap$(v, {
      accountSid: "AccountSid",
      domainSid: "DomainSid",
      sid: "Sid",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteSipAuthCallsCredentialListMappingRequest$ {
  /** @deprecated use `DeleteSipAuthCallsCredentialListMappingRequest$inboundSchema` instead. */
  export const inboundSchema =
    DeleteSipAuthCallsCredentialListMappingRequest$inboundSchema;
  /** @deprecated use `DeleteSipAuthCallsCredentialListMappingRequest$outboundSchema` instead. */
  export const outboundSchema =
    DeleteSipAuthCallsCredentialListMappingRequest$outboundSchema;
  /** @deprecated use `DeleteSipAuthCallsCredentialListMappingRequest$Outbound` instead. */
  export type Outbound =
    DeleteSipAuthCallsCredentialListMappingRequest$Outbound;
}

export function deleteSipAuthCallsCredentialListMappingRequestToJSON(
  deleteSipAuthCallsCredentialListMappingRequest:
    DeleteSipAuthCallsCredentialListMappingRequest,
): string {
  return JSON.stringify(
    DeleteSipAuthCallsCredentialListMappingRequest$outboundSchema.parse(
      deleteSipAuthCallsCredentialListMappingRequest,
    ),
  );
}

export function deleteSipAuthCallsCredentialListMappingRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteSipAuthCallsCredentialListMappingRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSipAuthCallsCredentialListMappingRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteSipAuthCallsCredentialListMappingRequest' from JSON`,
  );
}
