/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DeleteSipCredentialListMappingServerList = [
  "https://api.twilio.com",
] as const;

export type DeleteSipCredentialListMappingRequest = {
  /**
   * The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
   */
  accountSid: string;
  /**
   * A 34 character string that uniquely identifies the SIP Domain that includes the resource to delete.
   */
  domainSid: string;
  /**
   * A 34 character string that uniquely identifies the resource to delete.
   */
  sid: string;
};

/** @internal */
export const DeleteSipCredentialListMappingRequest$inboundSchema: z.ZodType<
  DeleteSipCredentialListMappingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  DomainSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "DomainSid": "domainSid",
    "Sid": "sid",
  });
});

/** @internal */
export type DeleteSipCredentialListMappingRequest$Outbound = {
  AccountSid: string;
  DomainSid: string;
  Sid: string;
};

/** @internal */
export const DeleteSipCredentialListMappingRequest$outboundSchema: z.ZodType<
  DeleteSipCredentialListMappingRequest$Outbound,
  z.ZodTypeDef,
  DeleteSipCredentialListMappingRequest
> = z.object({
  accountSid: z.string(),
  domainSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    domainSid: "DomainSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteSipCredentialListMappingRequest$ {
  /** @deprecated use `DeleteSipCredentialListMappingRequest$inboundSchema` instead. */
  export const inboundSchema =
    DeleteSipCredentialListMappingRequest$inboundSchema;
  /** @deprecated use `DeleteSipCredentialListMappingRequest$outboundSchema` instead. */
  export const outboundSchema =
    DeleteSipCredentialListMappingRequest$outboundSchema;
  /** @deprecated use `DeleteSipCredentialListMappingRequest$Outbound` instead. */
  export type Outbound = DeleteSipCredentialListMappingRequest$Outbound;
}

export function deleteSipCredentialListMappingRequestToJSON(
  deleteSipCredentialListMappingRequest: DeleteSipCredentialListMappingRequest,
): string {
  return JSON.stringify(
    DeleteSipCredentialListMappingRequest$outboundSchema.parse(
      deleteSipCredentialListMappingRequest,
    ),
  );
}

export function deleteSipCredentialListMappingRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSipCredentialListMappingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSipCredentialListMappingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSipCredentialListMappingRequest' from JSON`,
  );
}
