/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DeleteKeyServerList = [
  "https://api.twilio.com",
] as const;

export type DeleteKeyRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Key resources to delete.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the Key resource to delete.
   */
  sid: string;
};

/** @internal */
export const DeleteKeyRequest$inboundSchema: z.ZodType<
  DeleteKeyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
  });
});

/** @internal */
export type DeleteKeyRequest$Outbound = {
  AccountSid: string;
  Sid: string;
};

/** @internal */
export const DeleteKeyRequest$outboundSchema: z.ZodType<
  DeleteKeyRequest$Outbound,
  z.ZodTypeDef,
  DeleteKeyRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteKeyRequest$ {
  /** @deprecated use `DeleteKeyRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteKeyRequest$inboundSchema;
  /** @deprecated use `DeleteKeyRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteKeyRequest$outboundSchema;
  /** @deprecated use `DeleteKeyRequest$Outbound` instead. */
  export type Outbound = DeleteKeyRequest$Outbound;
}

export function deleteKeyRequestToJSON(
  deleteKeyRequest: DeleteKeyRequest,
): string {
  return JSON.stringify(
    DeleteKeyRequest$outboundSchema.parse(deleteKeyRequest),
  );
}

export function deleteKeyRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteKeyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteKeyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteKeyRequest' from JSON`,
  );
}
