/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DeleteRecordingTranscriptionServerList = [
  "https://api.twilio.com",
] as const;

export type DeleteRecordingTranscriptionRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Transcription resources to delete.
   */
  accountSid: string;
  /**
   * The SID of the [Recording](https://www.twilio.com/docs/voice/api/recording) that created the transcription to delete.
   */
  recordingSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the Transcription resource to delete.
   */
  sid: string;
};

/** @internal */
export const DeleteRecordingTranscriptionRequest$inboundSchema: z.ZodType<
  DeleteRecordingTranscriptionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  RecordingSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "RecordingSid": "recordingSid",
    "Sid": "sid",
  });
});

/** @internal */
export type DeleteRecordingTranscriptionRequest$Outbound = {
  AccountSid: string;
  RecordingSid: string;
  Sid: string;
};

/** @internal */
export const DeleteRecordingTranscriptionRequest$outboundSchema: z.ZodType<
  DeleteRecordingTranscriptionRequest$Outbound,
  z.ZodTypeDef,
  DeleteRecordingTranscriptionRequest
> = z.object({
  accountSid: z.string(),
  recordingSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    recordingSid: "RecordingSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteRecordingTranscriptionRequest$ {
  /** @deprecated use `DeleteRecordingTranscriptionRequest$inboundSchema` instead. */
  export const inboundSchema =
    DeleteRecordingTranscriptionRequest$inboundSchema;
  /** @deprecated use `DeleteRecordingTranscriptionRequest$outboundSchema` instead. */
  export const outboundSchema =
    DeleteRecordingTranscriptionRequest$outboundSchema;
  /** @deprecated use `DeleteRecordingTranscriptionRequest$Outbound` instead. */
  export type Outbound = DeleteRecordingTranscriptionRequest$Outbound;
}

export function deleteRecordingTranscriptionRequestToJSON(
  deleteRecordingTranscriptionRequest: DeleteRecordingTranscriptionRequest,
): string {
  return JSON.stringify(
    DeleteRecordingTranscriptionRequest$outboundSchema.parse(
      deleteRecordingTranscriptionRequest,
    ),
  );
}

export function deleteRecordingTranscriptionRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteRecordingTranscriptionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteRecordingTranscriptionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteRecordingTranscriptionRequest' from JSON`,
  );
}
