/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DeleteIncomingPhoneNumberServerList = [
  "https://api.twilio.com",
] as const;

export type DeleteIncomingPhoneNumberRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IncomingPhoneNumber resources to delete.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the IncomingPhoneNumber resource to delete.
   */
  sid: string;
};

/** @internal */
export const DeleteIncomingPhoneNumberRequest$inboundSchema: z.ZodType<
  DeleteIncomingPhoneNumberRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
  });
});

/** @internal */
export type DeleteIncomingPhoneNumberRequest$Outbound = {
  AccountSid: string;
  Sid: string;
};

/** @internal */
export const DeleteIncomingPhoneNumberRequest$outboundSchema: z.ZodType<
  DeleteIncomingPhoneNumberRequest$Outbound,
  z.ZodTypeDef,
  DeleteIncomingPhoneNumberRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteIncomingPhoneNumberRequest$ {
  /** @deprecated use `DeleteIncomingPhoneNumberRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteIncomingPhoneNumberRequest$inboundSchema;
  /** @deprecated use `DeleteIncomingPhoneNumberRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteIncomingPhoneNumberRequest$outboundSchema;
  /** @deprecated use `DeleteIncomingPhoneNumberRequest$Outbound` instead. */
  export type Outbound = DeleteIncomingPhoneNumberRequest$Outbound;
}

export function deleteIncomingPhoneNumberRequestToJSON(
  deleteIncomingPhoneNumberRequest: DeleteIncomingPhoneNumberRequest,
): string {
  return JSON.stringify(
    DeleteIncomingPhoneNumberRequest$outboundSchema.parse(
      deleteIncomingPhoneNumberRequest,
    ),
  );
}

export function deleteIncomingPhoneNumberRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteIncomingPhoneNumberRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteIncomingPhoneNumberRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteIncomingPhoneNumberRequest' from JSON`,
  );
}
