/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DeleteConnectAppServerList = [
  "https://api.twilio.com",
] as const;

export type DeleteConnectAppRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ConnectApp resource to fetch.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the ConnectApp resource to fetch.
   */
  sid: string;
};

/** @internal */
export const DeleteConnectAppRequest$inboundSchema: z.ZodType<
  DeleteConnectAppRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
  });
});

/** @internal */
export type DeleteConnectAppRequest$Outbound = {
  AccountSid: string;
  Sid: string;
};

/** @internal */
export const DeleteConnectAppRequest$outboundSchema: z.ZodType<
  DeleteConnectAppRequest$Outbound,
  z.ZodTypeDef,
  DeleteConnectAppRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteConnectAppRequest$ {
  /** @deprecated use `DeleteConnectAppRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteConnectAppRequest$inboundSchema;
  /** @deprecated use `DeleteConnectAppRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteConnectAppRequest$outboundSchema;
  /** @deprecated use `DeleteConnectAppRequest$Outbound` instead. */
  export type Outbound = DeleteConnectAppRequest$Outbound;
}

export function deleteConnectAppRequestToJSON(
  deleteConnectAppRequest: DeleteConnectAppRequest,
): string {
  return JSON.stringify(
    DeleteConnectAppRequest$outboundSchema.parse(deleteConnectAppRequest),
  );
}

export function deleteConnectAppRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteConnectAppRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteConnectAppRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteConnectAppRequest' from JSON`,
  );
}
