/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DeleteParticipantServerList = [
  "https://api.twilio.com",
] as const;

export type DeleteParticipantRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Participant resources to delete.
   */
  accountSid: string;
  /**
   * The SID of the conference with the participants to delete.
   */
  conferenceSid: string;
  /**
   * The [Call](https://www.twilio.com/docs/voice/api/call-resource) SID or label of the participant to delete. Non URL safe characters in a label must be percent encoded, for example, a space character is represented as %20.
   */
  callSid: string;
};

/** @internal */
export const DeleteParticipantRequest$inboundSchema: z.ZodType<
  DeleteParticipantRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  ConferenceSid: z.string(),
  CallSid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "ConferenceSid": "conferenceSid",
    "CallSid": "callSid",
  });
});

/** @internal */
export type DeleteParticipantRequest$Outbound = {
  AccountSid: string;
  ConferenceSid: string;
  CallSid: string;
};

/** @internal */
export const DeleteParticipantRequest$outboundSchema: z.ZodType<
  DeleteParticipantRequest$Outbound,
  z.ZodTypeDef,
  DeleteParticipantRequest
> = z.object({
  accountSid: z.string(),
  conferenceSid: z.string(),
  callSid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    conferenceSid: "ConferenceSid",
    callSid: "CallSid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteParticipantRequest$ {
  /** @deprecated use `DeleteParticipantRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteParticipantRequest$inboundSchema;
  /** @deprecated use `DeleteParticipantRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteParticipantRequest$outboundSchema;
  /** @deprecated use `DeleteParticipantRequest$Outbound` instead. */
  export type Outbound = DeleteParticipantRequest$Outbound;
}

export function deleteParticipantRequestToJSON(
  deleteParticipantRequest: DeleteParticipantRequest,
): string {
  return JSON.stringify(
    DeleteParticipantRequest$outboundSchema.parse(deleteParticipantRequest),
  );
}

export function deleteParticipantRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteParticipantRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteParticipantRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteParticipantRequest' from JSON`,
  );
}
