/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchSipIpAccessControlListServerList = [
  "https://api.twilio.com",
] as const;

export type FetchSipIpAccessControlListRequest = {
  /**
   * The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
   */
  accountSid: string;
  /**
   * A 34 character string that uniquely identifies the resource to fetch.
   */
  sid: string;
};

export type FetchSipIpAccessControlListResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountSipSipIpAccessControlList;
};

/** @internal */
export const FetchSipIpAccessControlListRequest$inboundSchema: z.ZodType<
  FetchSipIpAccessControlListRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
  });
});

/** @internal */
export type FetchSipIpAccessControlListRequest$Outbound = {
  AccountSid: string;
  Sid: string;
};

/** @internal */
export const FetchSipIpAccessControlListRequest$outboundSchema: z.ZodType<
  FetchSipIpAccessControlListRequest$Outbound,
  z.ZodTypeDef,
  FetchSipIpAccessControlListRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchSipIpAccessControlListRequest$ {
  /** @deprecated use `FetchSipIpAccessControlListRequest$inboundSchema` instead. */
  export const inboundSchema = FetchSipIpAccessControlListRequest$inboundSchema;
  /** @deprecated use `FetchSipIpAccessControlListRequest$outboundSchema` instead. */
  export const outboundSchema =
    FetchSipIpAccessControlListRequest$outboundSchema;
  /** @deprecated use `FetchSipIpAccessControlListRequest$Outbound` instead. */
  export type Outbound = FetchSipIpAccessControlListRequest$Outbound;
}

export function fetchSipIpAccessControlListRequestToJSON(
  fetchSipIpAccessControlListRequest: FetchSipIpAccessControlListRequest,
): string {
  return JSON.stringify(
    FetchSipIpAccessControlListRequest$outboundSchema.parse(
      fetchSipIpAccessControlListRequest,
    ),
  );
}

export function fetchSipIpAccessControlListRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchSipIpAccessControlListRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FetchSipIpAccessControlListRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchSipIpAccessControlListRequest' from JSON`,
  );
}

/** @internal */
export const FetchSipIpAccessControlListResponse$inboundSchema: z.ZodType<
  FetchSipIpAccessControlListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountSipSipIpAccessControlList$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type FetchSipIpAccessControlListResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountSipSipIpAccessControlList$Outbound;
};

/** @internal */
export const FetchSipIpAccessControlListResponse$outboundSchema: z.ZodType<
  FetchSipIpAccessControlListResponse$Outbound,
  z.ZodTypeDef,
  FetchSipIpAccessControlListResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountSipSipIpAccessControlList$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchSipIpAccessControlListResponse$ {
  /** @deprecated use `FetchSipIpAccessControlListResponse$inboundSchema` instead. */
  export const inboundSchema =
    FetchSipIpAccessControlListResponse$inboundSchema;
  /** @deprecated use `FetchSipIpAccessControlListResponse$outboundSchema` instead. */
  export const outboundSchema =
    FetchSipIpAccessControlListResponse$outboundSchema;
  /** @deprecated use `FetchSipIpAccessControlListResponse$Outbound` instead. */
  export type Outbound = FetchSipIpAccessControlListResponse$Outbound;
}

export function fetchSipIpAccessControlListResponseToJSON(
  fetchSipIpAccessControlListResponse: FetchSipIpAccessControlListResponse,
): string {
  return JSON.stringify(
    FetchSipIpAccessControlListResponse$outboundSchema.parse(
      fetchSipIpAccessControlListResponse,
    ),
  );
}

export function fetchSipIpAccessControlListResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchSipIpAccessControlListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FetchSipIpAccessControlListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchSipIpAccessControlListResponse' from JSON`,
  );
}
