/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchParticipantServerList = [
  "https://api.twilio.com",
] as const;

export type FetchParticipantRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Participant resource to fetch.
   */
  accountSid: string;
  /**
   * The SID of the conference with the participant to fetch.
   */
  conferenceSid: string;
  /**
   * The [Call](https://www.twilio.com/docs/voice/api/call-resource) SID or label of the participant to fetch. Non URL safe characters in a label must be percent encoded, for example, a space character is represented as %20.
   */
  callSid: string;
};

export type FetchParticipantResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountConferenceParticipant;
};

/** @internal */
export const FetchParticipantRequest$inboundSchema: z.ZodType<
  FetchParticipantRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  ConferenceSid: z.string(),
  CallSid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "ConferenceSid": "conferenceSid",
    "CallSid": "callSid",
  });
});

/** @internal */
export type FetchParticipantRequest$Outbound = {
  AccountSid: string;
  ConferenceSid: string;
  CallSid: string;
};

/** @internal */
export const FetchParticipantRequest$outboundSchema: z.ZodType<
  FetchParticipantRequest$Outbound,
  z.ZodTypeDef,
  FetchParticipantRequest
> = z.object({
  accountSid: z.string(),
  conferenceSid: z.string(),
  callSid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    conferenceSid: "ConferenceSid",
    callSid: "CallSid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchParticipantRequest$ {
  /** @deprecated use `FetchParticipantRequest$inboundSchema` instead. */
  export const inboundSchema = FetchParticipantRequest$inboundSchema;
  /** @deprecated use `FetchParticipantRequest$outboundSchema` instead. */
  export const outboundSchema = FetchParticipantRequest$outboundSchema;
  /** @deprecated use `FetchParticipantRequest$Outbound` instead. */
  export type Outbound = FetchParticipantRequest$Outbound;
}

export function fetchParticipantRequestToJSON(
  fetchParticipantRequest: FetchParticipantRequest,
): string {
  return JSON.stringify(
    FetchParticipantRequest$outboundSchema.parse(fetchParticipantRequest),
  );
}

export function fetchParticipantRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchParticipantRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchParticipantRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchParticipantRequest' from JSON`,
  );
}

/** @internal */
export const FetchParticipantResponse$inboundSchema: z.ZodType<
  FetchParticipantResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountConferenceParticipant$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type FetchParticipantResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountConferenceParticipant$Outbound;
};

/** @internal */
export const FetchParticipantResponse$outboundSchema: z.ZodType<
  FetchParticipantResponse$Outbound,
  z.ZodTypeDef,
  FetchParticipantResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountConferenceParticipant$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchParticipantResponse$ {
  /** @deprecated use `FetchParticipantResponse$inboundSchema` instead. */
  export const inboundSchema = FetchParticipantResponse$inboundSchema;
  /** @deprecated use `FetchParticipantResponse$outboundSchema` instead. */
  export const outboundSchema = FetchParticipantResponse$outboundSchema;
  /** @deprecated use `FetchParticipantResponse$Outbound` instead. */
  export type Outbound = FetchParticipantResponse$Outbound;
}

export function fetchParticipantResponseToJSON(
  fetchParticipantResponse: FetchParticipantResponse,
): string {
  return JSON.stringify(
    FetchParticipantResponse$outboundSchema.parse(fetchParticipantResponse),
  );
}

export function fetchParticipantResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchParticipantResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchParticipantResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchParticipantResponse' from JSON`,
  );
}
