/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchSipIpAddressServerList = [
  "https://api.twilio.com",
] as const;

export type FetchSipIpAddressRequest = {
  /**
   * The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
   */
  accountSid: string;
  /**
   * The IpAccessControlList Sid that identifies the IpAddress resources to fetch.
   */
  ipAccessControlListSid: string;
  /**
   * A 34 character string that uniquely identifies the IpAddress resource to fetch.
   */
  sid: string;
};

export type FetchSipIpAddressResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountSipSipIpAccessControlListSipIpAddress;
};

/** @internal */
export const FetchSipIpAddressRequest$inboundSchema: z.ZodType<
  FetchSipIpAddressRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  IpAccessControlListSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "IpAccessControlListSid": "ipAccessControlListSid",
    "Sid": "sid",
  });
});

/** @internal */
export type FetchSipIpAddressRequest$Outbound = {
  AccountSid: string;
  IpAccessControlListSid: string;
  Sid: string;
};

/** @internal */
export const FetchSipIpAddressRequest$outboundSchema: z.ZodType<
  FetchSipIpAddressRequest$Outbound,
  z.ZodTypeDef,
  FetchSipIpAddressRequest
> = z.object({
  accountSid: z.string(),
  ipAccessControlListSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    ipAccessControlListSid: "IpAccessControlListSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchSipIpAddressRequest$ {
  /** @deprecated use `FetchSipIpAddressRequest$inboundSchema` instead. */
  export const inboundSchema = FetchSipIpAddressRequest$inboundSchema;
  /** @deprecated use `FetchSipIpAddressRequest$outboundSchema` instead. */
  export const outboundSchema = FetchSipIpAddressRequest$outboundSchema;
  /** @deprecated use `FetchSipIpAddressRequest$Outbound` instead. */
  export type Outbound = FetchSipIpAddressRequest$Outbound;
}

export function fetchSipIpAddressRequestToJSON(
  fetchSipIpAddressRequest: FetchSipIpAddressRequest,
): string {
  return JSON.stringify(
    FetchSipIpAddressRequest$outboundSchema.parse(fetchSipIpAddressRequest),
  );
}

export function fetchSipIpAddressRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchSipIpAddressRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchSipIpAddressRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchSipIpAddressRequest' from JSON`,
  );
}

/** @internal */
export const FetchSipIpAddressResponse$inboundSchema: z.ZodType<
  FetchSipIpAddressResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result:
    components
      .ApiV2010AccountSipSipIpAccessControlListSipIpAddress$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type FetchSipIpAddressResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    components.ApiV2010AccountSipSipIpAccessControlListSipIpAddress$Outbound;
};

/** @internal */
export const FetchSipIpAddressResponse$outboundSchema: z.ZodType<
  FetchSipIpAddressResponse$Outbound,
  z.ZodTypeDef,
  FetchSipIpAddressResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result:
    components
      .ApiV2010AccountSipSipIpAccessControlListSipIpAddress$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchSipIpAddressResponse$ {
  /** @deprecated use `FetchSipIpAddressResponse$inboundSchema` instead. */
  export const inboundSchema = FetchSipIpAddressResponse$inboundSchema;
  /** @deprecated use `FetchSipIpAddressResponse$outboundSchema` instead. */
  export const outboundSchema = FetchSipIpAddressResponse$outboundSchema;
  /** @deprecated use `FetchSipIpAddressResponse$Outbound` instead. */
  export type Outbound = FetchSipIpAddressResponse$Outbound;
}

export function fetchSipIpAddressResponseToJSON(
  fetchSipIpAddressResponse: FetchSipIpAddressResponse,
): string {
  return JSON.stringify(
    FetchSipIpAddressResponse$outboundSchema.parse(fetchSipIpAddressResponse),
  );
}

export function fetchSipIpAddressResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchSipIpAddressResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchSipIpAddressResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchSipIpAddressResponse' from JSON`,
  );
}
