/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchRecordingServerList = [
  "https://api.twilio.com",
] as const;

export type FetchRecordingRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording resource to fetch.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the Recording resource to fetch.
   */
  sid: string;
  /**
   * A boolean parameter indicating whether to retrieve soft deleted recordings or not. Recordings metadata are kept after deletion for a retention period of 40 days.
   */
  includeSoftDeleted?: boolean | undefined;
};

export type FetchRecordingResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountRecording;
};

/** @internal */
export const FetchRecordingRequest$inboundSchema: z.ZodType<
  FetchRecordingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
  IncludeSoftDeleted: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
    "IncludeSoftDeleted": "includeSoftDeleted",
  });
});

/** @internal */
export type FetchRecordingRequest$Outbound = {
  AccountSid: string;
  Sid: string;
  IncludeSoftDeleted?: boolean | undefined;
};

/** @internal */
export const FetchRecordingRequest$outboundSchema: z.ZodType<
  FetchRecordingRequest$Outbound,
  z.ZodTypeDef,
  FetchRecordingRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
  includeSoftDeleted: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
    includeSoftDeleted: "IncludeSoftDeleted",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchRecordingRequest$ {
  /** @deprecated use `FetchRecordingRequest$inboundSchema` instead. */
  export const inboundSchema = FetchRecordingRequest$inboundSchema;
  /** @deprecated use `FetchRecordingRequest$outboundSchema` instead. */
  export const outboundSchema = FetchRecordingRequest$outboundSchema;
  /** @deprecated use `FetchRecordingRequest$Outbound` instead. */
  export type Outbound = FetchRecordingRequest$Outbound;
}

export function fetchRecordingRequestToJSON(
  fetchRecordingRequest: FetchRecordingRequest,
): string {
  return JSON.stringify(
    FetchRecordingRequest$outboundSchema.parse(fetchRecordingRequest),
  );
}

export function fetchRecordingRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchRecordingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchRecordingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchRecordingRequest' from JSON`,
  );
}

/** @internal */
export const FetchRecordingResponse$inboundSchema: z.ZodType<
  FetchRecordingResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountRecording$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type FetchRecordingResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountRecording$Outbound;
};

/** @internal */
export const FetchRecordingResponse$outboundSchema: z.ZodType<
  FetchRecordingResponse$Outbound,
  z.ZodTypeDef,
  FetchRecordingResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountRecording$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchRecordingResponse$ {
  /** @deprecated use `FetchRecordingResponse$inboundSchema` instead. */
  export const inboundSchema = FetchRecordingResponse$inboundSchema;
  /** @deprecated use `FetchRecordingResponse$outboundSchema` instead. */
  export const outboundSchema = FetchRecordingResponse$outboundSchema;
  /** @deprecated use `FetchRecordingResponse$Outbound` instead. */
  export type Outbound = FetchRecordingResponse$Outbound;
}

export function fetchRecordingResponseToJSON(
  fetchRecordingResponse: FetchRecordingResponse,
): string {
  return JSON.stringify(
    FetchRecordingResponse$outboundSchema.parse(fetchRecordingResponse),
  );
}

export function fetchRecordingResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchRecordingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchRecordingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchRecordingResponse' from JSON`,
  );
}
