/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchIncomingPhoneNumberAssignedAddOnServerList = [
  "https://api.twilio.com",
] as const;

export type FetchIncomingPhoneNumberAssignedAddOnRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the resource to fetch.
   */
  accountSid: string;
  /**
   * The SID of the Phone Number to which the Add-on is assigned.
   */
  resourceSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the resource to fetch.
   */
  sid: string;
};

export type FetchIncomingPhoneNumberAssignedAddOnResponse = {
  headers: { [k: string]: Array<string> };
  result:
    components.ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberAssignedAddOn;
};

/** @internal */
export const FetchIncomingPhoneNumberAssignedAddOnRequest$inboundSchema:
  z.ZodType<
    FetchIncomingPhoneNumberAssignedAddOnRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    AccountSid: z.string(),
    ResourceSid: z.string(),
    Sid: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "AccountSid": "accountSid",
      "ResourceSid": "resourceSid",
      "Sid": "sid",
    });
  });

/** @internal */
export type FetchIncomingPhoneNumberAssignedAddOnRequest$Outbound = {
  AccountSid: string;
  ResourceSid: string;
  Sid: string;
};

/** @internal */
export const FetchIncomingPhoneNumberAssignedAddOnRequest$outboundSchema:
  z.ZodType<
    FetchIncomingPhoneNumberAssignedAddOnRequest$Outbound,
    z.ZodTypeDef,
    FetchIncomingPhoneNumberAssignedAddOnRequest
  > = z.object({
    accountSid: z.string(),
    resourceSid: z.string(),
    sid: z.string(),
  }).transform((v) => {
    return remap$(v, {
      accountSid: "AccountSid",
      resourceSid: "ResourceSid",
      sid: "Sid",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchIncomingPhoneNumberAssignedAddOnRequest$ {
  /** @deprecated use `FetchIncomingPhoneNumberAssignedAddOnRequest$inboundSchema` instead. */
  export const inboundSchema =
    FetchIncomingPhoneNumberAssignedAddOnRequest$inboundSchema;
  /** @deprecated use `FetchIncomingPhoneNumberAssignedAddOnRequest$outboundSchema` instead. */
  export const outboundSchema =
    FetchIncomingPhoneNumberAssignedAddOnRequest$outboundSchema;
  /** @deprecated use `FetchIncomingPhoneNumberAssignedAddOnRequest$Outbound` instead. */
  export type Outbound = FetchIncomingPhoneNumberAssignedAddOnRequest$Outbound;
}

export function fetchIncomingPhoneNumberAssignedAddOnRequestToJSON(
  fetchIncomingPhoneNumberAssignedAddOnRequest:
    FetchIncomingPhoneNumberAssignedAddOnRequest,
): string {
  return JSON.stringify(
    FetchIncomingPhoneNumberAssignedAddOnRequest$outboundSchema.parse(
      fetchIncomingPhoneNumberAssignedAddOnRequest,
    ),
  );
}

export function fetchIncomingPhoneNumberAssignedAddOnRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  FetchIncomingPhoneNumberAssignedAddOnRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FetchIncomingPhoneNumberAssignedAddOnRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FetchIncomingPhoneNumberAssignedAddOnRequest' from JSON`,
  );
}

/** @internal */
export const FetchIncomingPhoneNumberAssignedAddOnResponse$inboundSchema:
  z.ZodType<
    FetchIncomingPhoneNumberAssignedAddOnResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result:
      components
        .ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberAssignedAddOn$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type FetchIncomingPhoneNumberAssignedAddOnResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    components.ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberAssignedAddOn$Outbound;
};

/** @internal */
export const FetchIncomingPhoneNumberAssignedAddOnResponse$outboundSchema:
  z.ZodType<
    FetchIncomingPhoneNumberAssignedAddOnResponse$Outbound,
    z.ZodTypeDef,
    FetchIncomingPhoneNumberAssignedAddOnResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result:
      components
        .ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberAssignedAddOn$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchIncomingPhoneNumberAssignedAddOnResponse$ {
  /** @deprecated use `FetchIncomingPhoneNumberAssignedAddOnResponse$inboundSchema` instead. */
  export const inboundSchema =
    FetchIncomingPhoneNumberAssignedAddOnResponse$inboundSchema;
  /** @deprecated use `FetchIncomingPhoneNumberAssignedAddOnResponse$outboundSchema` instead. */
  export const outboundSchema =
    FetchIncomingPhoneNumberAssignedAddOnResponse$outboundSchema;
  /** @deprecated use `FetchIncomingPhoneNumberAssignedAddOnResponse$Outbound` instead. */
  export type Outbound = FetchIncomingPhoneNumberAssignedAddOnResponse$Outbound;
}

export function fetchIncomingPhoneNumberAssignedAddOnResponseToJSON(
  fetchIncomingPhoneNumberAssignedAddOnResponse:
    FetchIncomingPhoneNumberAssignedAddOnResponse,
): string {
  return JSON.stringify(
    FetchIncomingPhoneNumberAssignedAddOnResponse$outboundSchema.parse(
      fetchIncomingPhoneNumberAssignedAddOnResponse,
    ),
  );
}

export function fetchIncomingPhoneNumberAssignedAddOnResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  FetchIncomingPhoneNumberAssignedAddOnResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FetchIncomingPhoneNumberAssignedAddOnResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FetchIncomingPhoneNumberAssignedAddOnResponse' from JSON`,
  );
}
