/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchSipAuthRegistrationsCredentialListMappingServerList = [
  "https://api.twilio.com",
] as const;

export type FetchSipAuthRegistrationsCredentialListMappingRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the CredentialListMapping resource to fetch.
   */
  accountSid: string;
  /**
   * The SID of the SIP domain that contains the resource to fetch.
   */
  domainSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the CredentialListMapping resource to fetch.
   */
  sid: string;
};

export type FetchSipAuthRegistrationsCredentialListMappingResponse = {
  headers: { [k: string]: Array<string> };
  result:
    components.ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping;
};

/** @internal */
export const FetchSipAuthRegistrationsCredentialListMappingRequest$inboundSchema:
  z.ZodType<
    FetchSipAuthRegistrationsCredentialListMappingRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    AccountSid: z.string(),
    DomainSid: z.string(),
    Sid: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "AccountSid": "accountSid",
      "DomainSid": "domainSid",
      "Sid": "sid",
    });
  });

/** @internal */
export type FetchSipAuthRegistrationsCredentialListMappingRequest$Outbound = {
  AccountSid: string;
  DomainSid: string;
  Sid: string;
};

/** @internal */
export const FetchSipAuthRegistrationsCredentialListMappingRequest$outboundSchema:
  z.ZodType<
    FetchSipAuthRegistrationsCredentialListMappingRequest$Outbound,
    z.ZodTypeDef,
    FetchSipAuthRegistrationsCredentialListMappingRequest
  > = z.object({
    accountSid: z.string(),
    domainSid: z.string(),
    sid: z.string(),
  }).transform((v) => {
    return remap$(v, {
      accountSid: "AccountSid",
      domainSid: "DomainSid",
      sid: "Sid",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchSipAuthRegistrationsCredentialListMappingRequest$ {
  /** @deprecated use `FetchSipAuthRegistrationsCredentialListMappingRequest$inboundSchema` instead. */
  export const inboundSchema =
    FetchSipAuthRegistrationsCredentialListMappingRequest$inboundSchema;
  /** @deprecated use `FetchSipAuthRegistrationsCredentialListMappingRequest$outboundSchema` instead. */
  export const outboundSchema =
    FetchSipAuthRegistrationsCredentialListMappingRequest$outboundSchema;
  /** @deprecated use `FetchSipAuthRegistrationsCredentialListMappingRequest$Outbound` instead. */
  export type Outbound =
    FetchSipAuthRegistrationsCredentialListMappingRequest$Outbound;
}

export function fetchSipAuthRegistrationsCredentialListMappingRequestToJSON(
  fetchSipAuthRegistrationsCredentialListMappingRequest:
    FetchSipAuthRegistrationsCredentialListMappingRequest,
): string {
  return JSON.stringify(
    FetchSipAuthRegistrationsCredentialListMappingRequest$outboundSchema.parse(
      fetchSipAuthRegistrationsCredentialListMappingRequest,
    ),
  );
}

export function fetchSipAuthRegistrationsCredentialListMappingRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  FetchSipAuthRegistrationsCredentialListMappingRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FetchSipAuthRegistrationsCredentialListMappingRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FetchSipAuthRegistrationsCredentialListMappingRequest' from JSON`,
  );
}

/** @internal */
export const FetchSipAuthRegistrationsCredentialListMappingResponse$inboundSchema:
  z.ZodType<
    FetchSipAuthRegistrationsCredentialListMappingResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result:
      components
        .ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type FetchSipAuthRegistrationsCredentialListMappingResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    components.ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$Outbound;
};

/** @internal */
export const FetchSipAuthRegistrationsCredentialListMappingResponse$outboundSchema:
  z.ZodType<
    FetchSipAuthRegistrationsCredentialListMappingResponse$Outbound,
    z.ZodTypeDef,
    FetchSipAuthRegistrationsCredentialListMappingResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result:
      components
        .ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchSipAuthRegistrationsCredentialListMappingResponse$ {
  /** @deprecated use `FetchSipAuthRegistrationsCredentialListMappingResponse$inboundSchema` instead. */
  export const inboundSchema =
    FetchSipAuthRegistrationsCredentialListMappingResponse$inboundSchema;
  /** @deprecated use `FetchSipAuthRegistrationsCredentialListMappingResponse$outboundSchema` instead. */
  export const outboundSchema =
    FetchSipAuthRegistrationsCredentialListMappingResponse$outboundSchema;
  /** @deprecated use `FetchSipAuthRegistrationsCredentialListMappingResponse$Outbound` instead. */
  export type Outbound =
    FetchSipAuthRegistrationsCredentialListMappingResponse$Outbound;
}

export function fetchSipAuthRegistrationsCredentialListMappingResponseToJSON(
  fetchSipAuthRegistrationsCredentialListMappingResponse:
    FetchSipAuthRegistrationsCredentialListMappingResponse,
): string {
  return JSON.stringify(
    FetchSipAuthRegistrationsCredentialListMappingResponse$outboundSchema.parse(
      fetchSipAuthRegistrationsCredentialListMappingResponse,
    ),
  );
}

export function fetchSipAuthRegistrationsCredentialListMappingResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  FetchSipAuthRegistrationsCredentialListMappingResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FetchSipAuthRegistrationsCredentialListMappingResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'FetchSipAuthRegistrationsCredentialListMappingResponse' from JSON`,
  );
}
