/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchShortCodeServerList = [
  "https://api.twilio.com",
] as const;

export type FetchShortCodeRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ShortCode resource(s) to fetch.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the ShortCode resource to fetch
   */
  sid: string;
};

export type FetchShortCodeResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountShortCode;
};

/** @internal */
export const FetchShortCodeRequest$inboundSchema: z.ZodType<
  FetchShortCodeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
  });
});

/** @internal */
export type FetchShortCodeRequest$Outbound = {
  AccountSid: string;
  Sid: string;
};

/** @internal */
export const FetchShortCodeRequest$outboundSchema: z.ZodType<
  FetchShortCodeRequest$Outbound,
  z.ZodTypeDef,
  FetchShortCodeRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchShortCodeRequest$ {
  /** @deprecated use `FetchShortCodeRequest$inboundSchema` instead. */
  export const inboundSchema = FetchShortCodeRequest$inboundSchema;
  /** @deprecated use `FetchShortCodeRequest$outboundSchema` instead. */
  export const outboundSchema = FetchShortCodeRequest$outboundSchema;
  /** @deprecated use `FetchShortCodeRequest$Outbound` instead. */
  export type Outbound = FetchShortCodeRequest$Outbound;
}

export function fetchShortCodeRequestToJSON(
  fetchShortCodeRequest: FetchShortCodeRequest,
): string {
  return JSON.stringify(
    FetchShortCodeRequest$outboundSchema.parse(fetchShortCodeRequest),
  );
}

export function fetchShortCodeRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchShortCodeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchShortCodeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchShortCodeRequest' from JSON`,
  );
}

/** @internal */
export const FetchShortCodeResponse$inboundSchema: z.ZodType<
  FetchShortCodeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountShortCode$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type FetchShortCodeResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountShortCode$Outbound;
};

/** @internal */
export const FetchShortCodeResponse$outboundSchema: z.ZodType<
  FetchShortCodeResponse$Outbound,
  z.ZodTypeDef,
  FetchShortCodeResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountShortCode$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchShortCodeResponse$ {
  /** @deprecated use `FetchShortCodeResponse$inboundSchema` instead. */
  export const inboundSchema = FetchShortCodeResponse$inboundSchema;
  /** @deprecated use `FetchShortCodeResponse$outboundSchema` instead. */
  export const outboundSchema = FetchShortCodeResponse$outboundSchema;
  /** @deprecated use `FetchShortCodeResponse$Outbound` instead. */
  export type Outbound = FetchShortCodeResponse$Outbound;
}

export function fetchShortCodeResponseToJSON(
  fetchShortCodeResponse: FetchShortCodeResponse,
): string {
  return JSON.stringify(
    FetchShortCodeResponse$outboundSchema.parse(fetchShortCodeResponse),
  );
}

export function fetchShortCodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchShortCodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchShortCodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchShortCodeResponse' from JSON`,
  );
}
