/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchConferenceServerList = [
  "https://api.twilio.com",
] as const;

export type FetchConferenceRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Conference resource(s) to fetch.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the Conference resource to fetch
   */
  sid: string;
};

export type FetchConferenceResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountConference;
};

/** @internal */
export const FetchConferenceRequest$inboundSchema: z.ZodType<
  FetchConferenceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
  });
});

/** @internal */
export type FetchConferenceRequest$Outbound = {
  AccountSid: string;
  Sid: string;
};

/** @internal */
export const FetchConferenceRequest$outboundSchema: z.ZodType<
  FetchConferenceRequest$Outbound,
  z.ZodTypeDef,
  FetchConferenceRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchConferenceRequest$ {
  /** @deprecated use `FetchConferenceRequest$inboundSchema` instead. */
  export const inboundSchema = FetchConferenceRequest$inboundSchema;
  /** @deprecated use `FetchConferenceRequest$outboundSchema` instead. */
  export const outboundSchema = FetchConferenceRequest$outboundSchema;
  /** @deprecated use `FetchConferenceRequest$Outbound` instead. */
  export type Outbound = FetchConferenceRequest$Outbound;
}

export function fetchConferenceRequestToJSON(
  fetchConferenceRequest: FetchConferenceRequest,
): string {
  return JSON.stringify(
    FetchConferenceRequest$outboundSchema.parse(fetchConferenceRequest),
  );
}

export function fetchConferenceRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchConferenceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchConferenceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchConferenceRequest' from JSON`,
  );
}

/** @internal */
export const FetchConferenceResponse$inboundSchema: z.ZodType<
  FetchConferenceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountConference$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type FetchConferenceResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountConference$Outbound;
};

/** @internal */
export const FetchConferenceResponse$outboundSchema: z.ZodType<
  FetchConferenceResponse$Outbound,
  z.ZodTypeDef,
  FetchConferenceResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountConference$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchConferenceResponse$ {
  /** @deprecated use `FetchConferenceResponse$inboundSchema` instead. */
  export const inboundSchema = FetchConferenceResponse$inboundSchema;
  /** @deprecated use `FetchConferenceResponse$outboundSchema` instead. */
  export const outboundSchema = FetchConferenceResponse$outboundSchema;
  /** @deprecated use `FetchConferenceResponse$Outbound` instead. */
  export type Outbound = FetchConferenceResponse$Outbound;
}

export function fetchConferenceResponseToJSON(
  fetchConferenceResponse: FetchConferenceResponse,
): string {
  return JSON.stringify(
    FetchConferenceResponse$outboundSchema.parse(fetchConferenceResponse),
  );
}

export function fetchConferenceResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchConferenceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchConferenceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchConferenceResponse' from JSON`,
  );
}
