/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchSipIpAccessControlListMappingServerList = [
  "https://api.twilio.com",
] as const;

export type FetchSipIpAccessControlListMappingRequest = {
  /**
   * The unique id of the Account that is responsible for this resource.
   */
  accountSid: string;
  /**
   * A 34 character string that uniquely identifies the SIP domain.
   */
  domainSid: string;
  /**
   * A 34 character string that uniquely identifies the resource to fetch.
   */
  sid: string;
};

export type FetchSipIpAccessControlListMappingResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountSipSipDomainSipIpAccessControlListMapping;
};

/** @internal */
export const FetchSipIpAccessControlListMappingRequest$inboundSchema: z.ZodType<
  FetchSipIpAccessControlListMappingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  DomainSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "DomainSid": "domainSid",
    "Sid": "sid",
  });
});

/** @internal */
export type FetchSipIpAccessControlListMappingRequest$Outbound = {
  AccountSid: string;
  DomainSid: string;
  Sid: string;
};

/** @internal */
export const FetchSipIpAccessControlListMappingRequest$outboundSchema:
  z.ZodType<
    FetchSipIpAccessControlListMappingRequest$Outbound,
    z.ZodTypeDef,
    FetchSipIpAccessControlListMappingRequest
  > = z.object({
    accountSid: z.string(),
    domainSid: z.string(),
    sid: z.string(),
  }).transform((v) => {
    return remap$(v, {
      accountSid: "AccountSid",
      domainSid: "DomainSid",
      sid: "Sid",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchSipIpAccessControlListMappingRequest$ {
  /** @deprecated use `FetchSipIpAccessControlListMappingRequest$inboundSchema` instead. */
  export const inboundSchema =
    FetchSipIpAccessControlListMappingRequest$inboundSchema;
  /** @deprecated use `FetchSipIpAccessControlListMappingRequest$outboundSchema` instead. */
  export const outboundSchema =
    FetchSipIpAccessControlListMappingRequest$outboundSchema;
  /** @deprecated use `FetchSipIpAccessControlListMappingRequest$Outbound` instead. */
  export type Outbound = FetchSipIpAccessControlListMappingRequest$Outbound;
}

export function fetchSipIpAccessControlListMappingRequestToJSON(
  fetchSipIpAccessControlListMappingRequest:
    FetchSipIpAccessControlListMappingRequest,
): string {
  return JSON.stringify(
    FetchSipIpAccessControlListMappingRequest$outboundSchema.parse(
      fetchSipIpAccessControlListMappingRequest,
    ),
  );
}

export function fetchSipIpAccessControlListMappingRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  FetchSipIpAccessControlListMappingRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FetchSipIpAccessControlListMappingRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FetchSipIpAccessControlListMappingRequest' from JSON`,
  );
}

/** @internal */
export const FetchSipIpAccessControlListMappingResponse$inboundSchema:
  z.ZodType<FetchSipIpAccessControlListMappingResponse, z.ZodTypeDef, unknown> =
    z.object({
      Headers: z.record(z.array(z.string())),
      Result:
        components
          .ApiV2010AccountSipSipDomainSipIpAccessControlListMapping$inboundSchema,
    }).transform((v) => {
      return remap$(v, {
        "Headers": "headers",
        "Result": "result",
      });
    });

/** @internal */
export type FetchSipIpAccessControlListMappingResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    components.ApiV2010AccountSipSipDomainSipIpAccessControlListMapping$Outbound;
};

/** @internal */
export const FetchSipIpAccessControlListMappingResponse$outboundSchema:
  z.ZodType<
    FetchSipIpAccessControlListMappingResponse$Outbound,
    z.ZodTypeDef,
    FetchSipIpAccessControlListMappingResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result:
      components
        .ApiV2010AccountSipSipDomainSipIpAccessControlListMapping$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchSipIpAccessControlListMappingResponse$ {
  /** @deprecated use `FetchSipIpAccessControlListMappingResponse$inboundSchema` instead. */
  export const inboundSchema =
    FetchSipIpAccessControlListMappingResponse$inboundSchema;
  /** @deprecated use `FetchSipIpAccessControlListMappingResponse$outboundSchema` instead. */
  export const outboundSchema =
    FetchSipIpAccessControlListMappingResponse$outboundSchema;
  /** @deprecated use `FetchSipIpAccessControlListMappingResponse$Outbound` instead. */
  export type Outbound = FetchSipIpAccessControlListMappingResponse$Outbound;
}

export function fetchSipIpAccessControlListMappingResponseToJSON(
  fetchSipIpAccessControlListMappingResponse:
    FetchSipIpAccessControlListMappingResponse,
): string {
  return JSON.stringify(
    FetchSipIpAccessControlListMappingResponse$outboundSchema.parse(
      fetchSipIpAccessControlListMappingResponse,
    ),
  );
}

export function fetchSipIpAccessControlListMappingResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  FetchSipIpAccessControlListMappingResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FetchSipIpAccessControlListMappingResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FetchSipIpAccessControlListMappingResponse' from JSON`,
  );
}
