/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchAddressServerList = [
  "https://api.twilio.com",
] as const;

export type FetchAddressRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that is responsible for the Address resource to fetch.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the Address resource to fetch.
   */
  sid: string;
};

export type FetchAddressResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountAddress;
};

/** @internal */
export const FetchAddressRequest$inboundSchema: z.ZodType<
  FetchAddressRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
  });
});

/** @internal */
export type FetchAddressRequest$Outbound = {
  AccountSid: string;
  Sid: string;
};

/** @internal */
export const FetchAddressRequest$outboundSchema: z.ZodType<
  FetchAddressRequest$Outbound,
  z.ZodTypeDef,
  FetchAddressRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchAddressRequest$ {
  /** @deprecated use `FetchAddressRequest$inboundSchema` instead. */
  export const inboundSchema = FetchAddressRequest$inboundSchema;
  /** @deprecated use `FetchAddressRequest$outboundSchema` instead. */
  export const outboundSchema = FetchAddressRequest$outboundSchema;
  /** @deprecated use `FetchAddressRequest$Outbound` instead. */
  export type Outbound = FetchAddressRequest$Outbound;
}

export function fetchAddressRequestToJSON(
  fetchAddressRequest: FetchAddressRequest,
): string {
  return JSON.stringify(
    FetchAddressRequest$outboundSchema.parse(fetchAddressRequest),
  );
}

export function fetchAddressRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchAddressRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchAddressRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchAddressRequest' from JSON`,
  );
}

/** @internal */
export const FetchAddressResponse$inboundSchema: z.ZodType<
  FetchAddressResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountAddress$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type FetchAddressResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountAddress$Outbound;
};

/** @internal */
export const FetchAddressResponse$outboundSchema: z.ZodType<
  FetchAddressResponse$Outbound,
  z.ZodTypeDef,
  FetchAddressResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountAddress$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchAddressResponse$ {
  /** @deprecated use `FetchAddressResponse$inboundSchema` instead. */
  export const inboundSchema = FetchAddressResponse$inboundSchema;
  /** @deprecated use `FetchAddressResponse$outboundSchema` instead. */
  export const outboundSchema = FetchAddressResponse$outboundSchema;
  /** @deprecated use `FetchAddressResponse$Outbound` instead. */
  export type Outbound = FetchAddressResponse$Outbound;
}

export function fetchAddressResponseToJSON(
  fetchAddressResponse: FetchAddressResponse,
): string {
  return JSON.stringify(
    FetchAddressResponse$outboundSchema.parse(fetchAddressResponse),
  );
}

export function fetchAddressResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchAddressResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchAddressResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchAddressResponse' from JSON`,
  );
}
