/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchIncomingPhoneNumberServerList = [
  "https://api.twilio.com",
] as const;

export type FetchIncomingPhoneNumberRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IncomingPhoneNumber resource to fetch.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the IncomingPhoneNumber resource to fetch.
   */
  sid: string;
};

export type FetchIncomingPhoneNumberResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountIncomingPhoneNumber;
};

/** @internal */
export const FetchIncomingPhoneNumberRequest$inboundSchema: z.ZodType<
  FetchIncomingPhoneNumberRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
  });
});

/** @internal */
export type FetchIncomingPhoneNumberRequest$Outbound = {
  AccountSid: string;
  Sid: string;
};

/** @internal */
export const FetchIncomingPhoneNumberRequest$outboundSchema: z.ZodType<
  FetchIncomingPhoneNumberRequest$Outbound,
  z.ZodTypeDef,
  FetchIncomingPhoneNumberRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchIncomingPhoneNumberRequest$ {
  /** @deprecated use `FetchIncomingPhoneNumberRequest$inboundSchema` instead. */
  export const inboundSchema = FetchIncomingPhoneNumberRequest$inboundSchema;
  /** @deprecated use `FetchIncomingPhoneNumberRequest$outboundSchema` instead. */
  export const outboundSchema = FetchIncomingPhoneNumberRequest$outboundSchema;
  /** @deprecated use `FetchIncomingPhoneNumberRequest$Outbound` instead. */
  export type Outbound = FetchIncomingPhoneNumberRequest$Outbound;
}

export function fetchIncomingPhoneNumberRequestToJSON(
  fetchIncomingPhoneNumberRequest: FetchIncomingPhoneNumberRequest,
): string {
  return JSON.stringify(
    FetchIncomingPhoneNumberRequest$outboundSchema.parse(
      fetchIncomingPhoneNumberRequest,
    ),
  );
}

export function fetchIncomingPhoneNumberRequestFromJSON(
  jsonString: string,
): SafeParseResult<FetchIncomingPhoneNumberRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchIncomingPhoneNumberRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchIncomingPhoneNumberRequest' from JSON`,
  );
}

/** @internal */
export const FetchIncomingPhoneNumberResponse$inboundSchema: z.ZodType<
  FetchIncomingPhoneNumberResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountIncomingPhoneNumber$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type FetchIncomingPhoneNumberResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountIncomingPhoneNumber$Outbound;
};

/** @internal */
export const FetchIncomingPhoneNumberResponse$outboundSchema: z.ZodType<
  FetchIncomingPhoneNumberResponse$Outbound,
  z.ZodTypeDef,
  FetchIncomingPhoneNumberResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountIncomingPhoneNumber$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchIncomingPhoneNumberResponse$ {
  /** @deprecated use `FetchIncomingPhoneNumberResponse$inboundSchema` instead. */
  export const inboundSchema = FetchIncomingPhoneNumberResponse$inboundSchema;
  /** @deprecated use `FetchIncomingPhoneNumberResponse$outboundSchema` instead. */
  export const outboundSchema = FetchIncomingPhoneNumberResponse$outboundSchema;
  /** @deprecated use `FetchIncomingPhoneNumberResponse$Outbound` instead. */
  export type Outbound = FetchIncomingPhoneNumberResponse$Outbound;
}

export function fetchIncomingPhoneNumberResponseToJSON(
  fetchIncomingPhoneNumberResponse: FetchIncomingPhoneNumberResponse,
): string {
  return JSON.stringify(
    FetchIncomingPhoneNumberResponse$outboundSchema.parse(
      fetchIncomingPhoneNumberResponse,
    ),
  );
}

export function fetchIncomingPhoneNumberResponseFromJSON(
  jsonString: string,
): SafeParseResult<FetchIncomingPhoneNumberResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FetchIncomingPhoneNumberResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FetchIncomingPhoneNumberResponse' from JSON`,
  );
}
