/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListIncomingPhoneNumberMobileServerList = [
  "https://api.twilio.com",
] as const;

export type ListIncomingPhoneNumberMobileRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the resources to read.
   */
  accountSid: string;
  /**
   * Whether to include phone numbers new to the Twilio platform. Can be: `true` or `false` and the default is `true`.
   */
  beta?: boolean | undefined;
  /**
   * A string that identifies the resources to read.
   */
  friendlyName?: string | undefined;
  /**
   * The phone numbers of the IncomingPhoneNumber resources to read. You can specify partial numbers and use '*' as a wildcard for any digit.
   */
  phoneNumber?: string | undefined;
  /**
   * Whether to include phone numbers based on their origin. Can be: `twilio` or `hosted`. By default, phone numbers of all origin are included.
   */
  origin?: string | undefined;
  /**
   * How many resources to return in each list page. The default is 50, and the maximum is 1000.
   */
  pageSize?: number | undefined;
  /**
   * The page index. This value is simply for client state.
   */
  page?: number | undefined;
  /**
   * The page token. This is provided by the API.
   */
  pageToken?: string | undefined;
};

/**
 * OK
 */
export type ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse =
  {
    incomingPhoneNumbers?:
      | Array<
        components.ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberMobile
      >
      | undefined;
    end?: number | undefined;
    firstPageUri?: string | undefined;
    nextPageUri?: string | null | undefined;
    page?: number | undefined;
    pageSize?: number | undefined;
    previousPageUri?: string | null | undefined;
    start?: number | undefined;
    uri?: string | undefined;
  };

export type ListIncomingPhoneNumberMobileResponse = {
  headers: { [k: string]: Array<string> };
  result: ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse;
};

/** @internal */
export const ListIncomingPhoneNumberMobileRequest$inboundSchema: z.ZodType<
  ListIncomingPhoneNumberMobileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Beta: z.boolean().optional(),
  FriendlyName: z.string().optional(),
  PhoneNumber: z.string().optional(),
  Origin: z.string().optional(),
  PageSize: z.number().int().optional(),
  Page: z.number().int().optional(),
  PageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Beta": "beta",
    "FriendlyName": "friendlyName",
    "PhoneNumber": "phoneNumber",
    "Origin": "origin",
    "PageSize": "pageSize",
    "Page": "page",
    "PageToken": "pageToken",
  });
});

/** @internal */
export type ListIncomingPhoneNumberMobileRequest$Outbound = {
  AccountSid: string;
  Beta?: boolean | undefined;
  FriendlyName?: string | undefined;
  PhoneNumber?: string | undefined;
  Origin?: string | undefined;
  PageSize?: number | undefined;
  Page?: number | undefined;
  PageToken?: string | undefined;
};

/** @internal */
export const ListIncomingPhoneNumberMobileRequest$outboundSchema: z.ZodType<
  ListIncomingPhoneNumberMobileRequest$Outbound,
  z.ZodTypeDef,
  ListIncomingPhoneNumberMobileRequest
> = z.object({
  accountSid: z.string(),
  beta: z.boolean().optional(),
  friendlyName: z.string().optional(),
  phoneNumber: z.string().optional(),
  origin: z.string().optional(),
  pageSize: z.number().int().optional(),
  page: z.number().int().optional(),
  pageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    beta: "Beta",
    friendlyName: "FriendlyName",
    phoneNumber: "PhoneNumber",
    origin: "Origin",
    pageSize: "PageSize",
    page: "Page",
    pageToken: "PageToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListIncomingPhoneNumberMobileRequest$ {
  /** @deprecated use `ListIncomingPhoneNumberMobileRequest$inboundSchema` instead. */
  export const inboundSchema =
    ListIncomingPhoneNumberMobileRequest$inboundSchema;
  /** @deprecated use `ListIncomingPhoneNumberMobileRequest$outboundSchema` instead. */
  export const outboundSchema =
    ListIncomingPhoneNumberMobileRequest$outboundSchema;
  /** @deprecated use `ListIncomingPhoneNumberMobileRequest$Outbound` instead. */
  export type Outbound = ListIncomingPhoneNumberMobileRequest$Outbound;
}

export function listIncomingPhoneNumberMobileRequestToJSON(
  listIncomingPhoneNumberMobileRequest: ListIncomingPhoneNumberMobileRequest,
): string {
  return JSON.stringify(
    ListIncomingPhoneNumberMobileRequest$outboundSchema.parse(
      listIncomingPhoneNumberMobileRequest,
    ),
  );
}

export function listIncomingPhoneNumberMobileRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListIncomingPhoneNumberMobileRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListIncomingPhoneNumberMobileRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListIncomingPhoneNumberMobileRequest' from JSON`,
  );
}

/** @internal */
export const ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$inboundSchema:
  z.ZodType<
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    incoming_phone_numbers: z.array(
      components
        .ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberMobile$inboundSchema,
    ).optional(),
    end: z.number().int().optional(),
    first_page_uri: z.string().optional(),
    next_page_uri: z.nullable(z.string()).optional(),
    page: z.number().int().optional(),
    page_size: z.number().int().optional(),
    previous_page_uri: z.nullable(z.string()).optional(),
    start: z.number().int().optional(),
    uri: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "incoming_phone_numbers": "incomingPhoneNumbers",
      "first_page_uri": "firstPageUri",
      "next_page_uri": "nextPageUri",
      "page_size": "pageSize",
      "previous_page_uri": "previousPageUri",
    });
  });

/** @internal */
export type ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$Outbound =
  {
    incoming_phone_numbers?:
      | Array<
        components.ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberMobile$Outbound
      >
      | undefined;
    end?: number | undefined;
    first_page_uri?: string | undefined;
    next_page_uri?: string | null | undefined;
    page?: number | undefined;
    page_size?: number | undefined;
    previous_page_uri?: string | null | undefined;
    start?: number | undefined;
    uri?: string | undefined;
  };

/** @internal */
export const ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$outboundSchema:
  z.ZodType<
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$Outbound,
    z.ZodTypeDef,
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse
  > = z.object({
    incomingPhoneNumbers: z.array(
      components
        .ApiV2010AccountIncomingPhoneNumberIncomingPhoneNumberMobile$outboundSchema,
    ).optional(),
    end: z.number().int().optional(),
    firstPageUri: z.string().optional(),
    nextPageUri: z.nullable(z.string()).optional(),
    page: z.number().int().optional(),
    pageSize: z.number().int().optional(),
    previousPageUri: z.nullable(z.string()).optional(),
    start: z.number().int().optional(),
    uri: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      incomingPhoneNumbers: "incoming_phone_numbers",
      firstPageUri: "first_page_uri",
      nextPageUri: "next_page_uri",
      pageSize: "page_size",
      previousPageUri: "previous_page_uri",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$ {
  /** @deprecated use `ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$inboundSchema` instead. */
  export const inboundSchema =
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$inboundSchema;
  /** @deprecated use `ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$outboundSchema;
  /** @deprecated use `ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$Outbound` instead. */
  export type Outbound =
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$Outbound;
}

export function listIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponseToJSON(
  listIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse:
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse,
): string {
  return JSON.stringify(
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$outboundSchema
      .parse(
        listIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse,
      ),
  );
}

export function listIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse' from JSON`,
  );
}

/** @internal */
export const ListIncomingPhoneNumberMobileResponse$inboundSchema: z.ZodType<
  ListIncomingPhoneNumberMobileResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.lazy(() =>
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type ListIncomingPhoneNumberMobileResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$Outbound;
};

/** @internal */
export const ListIncomingPhoneNumberMobileResponse$outboundSchema: z.ZodType<
  ListIncomingPhoneNumberMobileResponse$Outbound,
  z.ZodTypeDef,
  ListIncomingPhoneNumberMobileResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.lazy(() =>
    ListIncomingPhoneNumberMobileListIncomingPhoneNumberMobileResponse$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListIncomingPhoneNumberMobileResponse$ {
  /** @deprecated use `ListIncomingPhoneNumberMobileResponse$inboundSchema` instead. */
  export const inboundSchema =
    ListIncomingPhoneNumberMobileResponse$inboundSchema;
  /** @deprecated use `ListIncomingPhoneNumberMobileResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListIncomingPhoneNumberMobileResponse$outboundSchema;
  /** @deprecated use `ListIncomingPhoneNumberMobileResponse$Outbound` instead. */
  export type Outbound = ListIncomingPhoneNumberMobileResponse$Outbound;
}

export function listIncomingPhoneNumberMobileResponseToJSON(
  listIncomingPhoneNumberMobileResponse: ListIncomingPhoneNumberMobileResponse,
): string {
  return JSON.stringify(
    ListIncomingPhoneNumberMobileResponse$outboundSchema.parse(
      listIncomingPhoneNumberMobileResponse,
    ),
  );
}

export function listIncomingPhoneNumberMobileResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListIncomingPhoneNumberMobileResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListIncomingPhoneNumberMobileResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListIncomingPhoneNumberMobileResponse' from JSON`,
  );
}
