/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListTranscriptionServerList = [
  "https://api.twilio.com",
] as const;

export type ListTranscriptionRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Transcription resources to read.
   */
  accountSid: string;
  /**
   * How many resources to return in each list page. The default is 50, and the maximum is 1000.
   */
  pageSize?: number | undefined;
  /**
   * The page index. This value is simply for client state.
   */
  page?: number | undefined;
  /**
   * The page token. This is provided by the API.
   */
  pageToken?: string | undefined;
};

/**
 * OK
 */
export type ListTranscriptionListTranscriptionResponse = {
  transcriptions?: Array<components.ApiV2010AccountTranscription> | undefined;
  end?: number | undefined;
  firstPageUri?: string | undefined;
  nextPageUri?: string | null | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
  previousPageUri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

export type ListTranscriptionResponse = {
  headers: { [k: string]: Array<string> };
  result: ListTranscriptionListTranscriptionResponse;
};

/** @internal */
export const ListTranscriptionRequest$inboundSchema: z.ZodType<
  ListTranscriptionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  PageSize: z.number().int().optional(),
  Page: z.number().int().optional(),
  PageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "PageSize": "pageSize",
    "Page": "page",
    "PageToken": "pageToken",
  });
});

/** @internal */
export type ListTranscriptionRequest$Outbound = {
  AccountSid: string;
  PageSize?: number | undefined;
  Page?: number | undefined;
  PageToken?: string | undefined;
};

/** @internal */
export const ListTranscriptionRequest$outboundSchema: z.ZodType<
  ListTranscriptionRequest$Outbound,
  z.ZodTypeDef,
  ListTranscriptionRequest
> = z.object({
  accountSid: z.string(),
  pageSize: z.number().int().optional(),
  page: z.number().int().optional(),
  pageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    pageSize: "PageSize",
    page: "Page",
    pageToken: "PageToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTranscriptionRequest$ {
  /** @deprecated use `ListTranscriptionRequest$inboundSchema` instead. */
  export const inboundSchema = ListTranscriptionRequest$inboundSchema;
  /** @deprecated use `ListTranscriptionRequest$outboundSchema` instead. */
  export const outboundSchema = ListTranscriptionRequest$outboundSchema;
  /** @deprecated use `ListTranscriptionRequest$Outbound` instead. */
  export type Outbound = ListTranscriptionRequest$Outbound;
}

export function listTranscriptionRequestToJSON(
  listTranscriptionRequest: ListTranscriptionRequest,
): string {
  return JSON.stringify(
    ListTranscriptionRequest$outboundSchema.parse(listTranscriptionRequest),
  );
}

export function listTranscriptionRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListTranscriptionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTranscriptionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTranscriptionRequest' from JSON`,
  );
}

/** @internal */
export const ListTranscriptionListTranscriptionResponse$inboundSchema:
  z.ZodType<ListTranscriptionListTranscriptionResponse, z.ZodTypeDef, unknown> =
    z.object({
      transcriptions: z.array(
        components.ApiV2010AccountTranscription$inboundSchema,
      ).optional(),
      end: z.number().int().optional(),
      first_page_uri: z.string().optional(),
      next_page_uri: z.nullable(z.string()).optional(),
      page: z.number().int().optional(),
      page_size: z.number().int().optional(),
      previous_page_uri: z.nullable(z.string()).optional(),
      start: z.number().int().optional(),
      uri: z.string().optional(),
    }).transform((v) => {
      return remap$(v, {
        "first_page_uri": "firstPageUri",
        "next_page_uri": "nextPageUri",
        "page_size": "pageSize",
        "previous_page_uri": "previousPageUri",
      });
    });

/** @internal */
export type ListTranscriptionListTranscriptionResponse$Outbound = {
  transcriptions?:
    | Array<components.ApiV2010AccountTranscription$Outbound>
    | undefined;
  end?: number | undefined;
  first_page_uri?: string | undefined;
  next_page_uri?: string | null | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  previous_page_uri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

/** @internal */
export const ListTranscriptionListTranscriptionResponse$outboundSchema:
  z.ZodType<
    ListTranscriptionListTranscriptionResponse$Outbound,
    z.ZodTypeDef,
    ListTranscriptionListTranscriptionResponse
  > = z.object({
    transcriptions: z.array(
      components.ApiV2010AccountTranscription$outboundSchema,
    ).optional(),
    end: z.number().int().optional(),
    firstPageUri: z.string().optional(),
    nextPageUri: z.nullable(z.string()).optional(),
    page: z.number().int().optional(),
    pageSize: z.number().int().optional(),
    previousPageUri: z.nullable(z.string()).optional(),
    start: z.number().int().optional(),
    uri: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      firstPageUri: "first_page_uri",
      nextPageUri: "next_page_uri",
      pageSize: "page_size",
      previousPageUri: "previous_page_uri",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTranscriptionListTranscriptionResponse$ {
  /** @deprecated use `ListTranscriptionListTranscriptionResponse$inboundSchema` instead. */
  export const inboundSchema =
    ListTranscriptionListTranscriptionResponse$inboundSchema;
  /** @deprecated use `ListTranscriptionListTranscriptionResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListTranscriptionListTranscriptionResponse$outboundSchema;
  /** @deprecated use `ListTranscriptionListTranscriptionResponse$Outbound` instead. */
  export type Outbound = ListTranscriptionListTranscriptionResponse$Outbound;
}

export function listTranscriptionListTranscriptionResponseToJSON(
  listTranscriptionListTranscriptionResponse:
    ListTranscriptionListTranscriptionResponse,
): string {
  return JSON.stringify(
    ListTranscriptionListTranscriptionResponse$outboundSchema.parse(
      listTranscriptionListTranscriptionResponse,
    ),
  );
}

export function listTranscriptionListTranscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListTranscriptionListTranscriptionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListTranscriptionListTranscriptionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListTranscriptionListTranscriptionResponse' from JSON`,
  );
}

/** @internal */
export const ListTranscriptionResponse$inboundSchema: z.ZodType<
  ListTranscriptionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.lazy(() =>
    ListTranscriptionListTranscriptionResponse$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type ListTranscriptionResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ListTranscriptionListTranscriptionResponse$Outbound;
};

/** @internal */
export const ListTranscriptionResponse$outboundSchema: z.ZodType<
  ListTranscriptionResponse$Outbound,
  z.ZodTypeDef,
  ListTranscriptionResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.lazy(() =>
    ListTranscriptionListTranscriptionResponse$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTranscriptionResponse$ {
  /** @deprecated use `ListTranscriptionResponse$inboundSchema` instead. */
  export const inboundSchema = ListTranscriptionResponse$inboundSchema;
  /** @deprecated use `ListTranscriptionResponse$outboundSchema` instead. */
  export const outboundSchema = ListTranscriptionResponse$outboundSchema;
  /** @deprecated use `ListTranscriptionResponse$Outbound` instead. */
  export type Outbound = ListTranscriptionResponse$Outbound;
}

export function listTranscriptionResponseToJSON(
  listTranscriptionResponse: ListTranscriptionResponse,
): string {
  return JSON.stringify(
    ListTranscriptionResponse$outboundSchema.parse(listTranscriptionResponse),
  );
}

export function listTranscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTranscriptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTranscriptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTranscriptionResponse' from JSON`,
  );
}
