/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListUsageRecordAllTimeServerList = [
  "https://api.twilio.com",
] as const;

export type ListUsageRecordAllTimeRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the UsageRecord resources to read.
   */
  accountSid: string;
  /**
   * The [usage category](https://www.twilio.com/docs/usage/api/usage-record#usage-categories) of the UsageRecord resources to read. Only UsageRecord resources in the specified category are retrieved.
   */
  category?: components.UsageRecordAllTimeEnumCategory | undefined;
  /**
   * Only include usage that has occurred on or after this date. Specify the date in GMT and format as `YYYY-MM-DD`. You can also specify offsets from the current date, such as: `-30days`, which will set the start date to be 30 days before the current date.
   */
  startDate?: RFCDate | undefined;
  /**
   * Only include usage that occurred on or before this date. Specify the date in GMT and format as `YYYY-MM-DD`.  You can also specify offsets from the current date, such as: `+30days`, which will set the end date to 30 days from the current date.
   */
  endDate?: RFCDate | undefined;
  /**
   * Whether to include usage from the master account and all its subaccounts. Can be: `true` (the default) to include usage from the master account and all subaccounts or `false` to retrieve usage from only the specified account.
   */
  includeSubaccounts?: boolean | undefined;
  /**
   * How many resources to return in each list page. The default is 50, and the maximum is 1000.
   */
  pageSize?: number | undefined;
  /**
   * The page index. This value is simply for client state.
   */
  page?: number | undefined;
  /**
   * The page token. This is provided by the API.
   */
  pageToken?: string | undefined;
};

/**
 * OK
 */
export type ListUsageRecordAllTimeListUsageRecordAllTimeResponse = {
  usageRecords?:
    | Array<components.ApiV2010AccountUsageUsageRecordUsageRecordAllTime>
    | undefined;
  end?: number | undefined;
  firstPageUri?: string | undefined;
  nextPageUri?: string | null | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
  previousPageUri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

export type ListUsageRecordAllTimeResponse = {
  headers: { [k: string]: Array<string> };
  result: ListUsageRecordAllTimeListUsageRecordAllTimeResponse;
};

/** @internal */
export const ListUsageRecordAllTimeRequest$inboundSchema: z.ZodType<
  ListUsageRecordAllTimeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Category: components.UsageRecordAllTimeEnumCategory$inboundSchema.optional(),
  StartDate: z.string().transform(v => new RFCDate(v)).optional(),
  EndDate: z.string().transform(v => new RFCDate(v)).optional(),
  IncludeSubaccounts: z.boolean().optional(),
  PageSize: z.number().int().optional(),
  Page: z.number().int().optional(),
  PageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Category": "category",
    "StartDate": "startDate",
    "EndDate": "endDate",
    "IncludeSubaccounts": "includeSubaccounts",
    "PageSize": "pageSize",
    "Page": "page",
    "PageToken": "pageToken",
  });
});

/** @internal */
export type ListUsageRecordAllTimeRequest$Outbound = {
  AccountSid: string;
  Category?: string | undefined;
  StartDate?: string | undefined;
  EndDate?: string | undefined;
  IncludeSubaccounts?: boolean | undefined;
  PageSize?: number | undefined;
  Page?: number | undefined;
  PageToken?: string | undefined;
};

/** @internal */
export const ListUsageRecordAllTimeRequest$outboundSchema: z.ZodType<
  ListUsageRecordAllTimeRequest$Outbound,
  z.ZodTypeDef,
  ListUsageRecordAllTimeRequest
> = z.object({
  accountSid: z.string(),
  category: components.UsageRecordAllTimeEnumCategory$outboundSchema.optional(),
  startDate: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  endDate: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
  includeSubaccounts: z.boolean().optional(),
  pageSize: z.number().int().optional(),
  page: z.number().int().optional(),
  pageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    category: "Category",
    startDate: "StartDate",
    endDate: "EndDate",
    includeSubaccounts: "IncludeSubaccounts",
    pageSize: "PageSize",
    page: "Page",
    pageToken: "PageToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListUsageRecordAllTimeRequest$ {
  /** @deprecated use `ListUsageRecordAllTimeRequest$inboundSchema` instead. */
  export const inboundSchema = ListUsageRecordAllTimeRequest$inboundSchema;
  /** @deprecated use `ListUsageRecordAllTimeRequest$outboundSchema` instead. */
  export const outboundSchema = ListUsageRecordAllTimeRequest$outboundSchema;
  /** @deprecated use `ListUsageRecordAllTimeRequest$Outbound` instead. */
  export type Outbound = ListUsageRecordAllTimeRequest$Outbound;
}

export function listUsageRecordAllTimeRequestToJSON(
  listUsageRecordAllTimeRequest: ListUsageRecordAllTimeRequest,
): string {
  return JSON.stringify(
    ListUsageRecordAllTimeRequest$outboundSchema.parse(
      listUsageRecordAllTimeRequest,
    ),
  );
}

export function listUsageRecordAllTimeRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListUsageRecordAllTimeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUsageRecordAllTimeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUsageRecordAllTimeRequest' from JSON`,
  );
}

/** @internal */
export const ListUsageRecordAllTimeListUsageRecordAllTimeResponse$inboundSchema:
  z.ZodType<
    ListUsageRecordAllTimeListUsageRecordAllTimeResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    usage_records: z.array(
      components
        .ApiV2010AccountUsageUsageRecordUsageRecordAllTime$inboundSchema,
    ).optional(),
    end: z.number().int().optional(),
    first_page_uri: z.string().optional(),
    next_page_uri: z.nullable(z.string()).optional(),
    page: z.number().int().optional(),
    page_size: z.number().int().optional(),
    previous_page_uri: z.nullable(z.string()).optional(),
    start: z.number().int().optional(),
    uri: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "usage_records": "usageRecords",
      "first_page_uri": "firstPageUri",
      "next_page_uri": "nextPageUri",
      "page_size": "pageSize",
      "previous_page_uri": "previousPageUri",
    });
  });

/** @internal */
export type ListUsageRecordAllTimeListUsageRecordAllTimeResponse$Outbound = {
  usage_records?:
    | Array<
      components.ApiV2010AccountUsageUsageRecordUsageRecordAllTime$Outbound
    >
    | undefined;
  end?: number | undefined;
  first_page_uri?: string | undefined;
  next_page_uri?: string | null | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  previous_page_uri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

/** @internal */
export const ListUsageRecordAllTimeListUsageRecordAllTimeResponse$outboundSchema:
  z.ZodType<
    ListUsageRecordAllTimeListUsageRecordAllTimeResponse$Outbound,
    z.ZodTypeDef,
    ListUsageRecordAllTimeListUsageRecordAllTimeResponse
  > = z.object({
    usageRecords: z.array(
      components
        .ApiV2010AccountUsageUsageRecordUsageRecordAllTime$outboundSchema,
    ).optional(),
    end: z.number().int().optional(),
    firstPageUri: z.string().optional(),
    nextPageUri: z.nullable(z.string()).optional(),
    page: z.number().int().optional(),
    pageSize: z.number().int().optional(),
    previousPageUri: z.nullable(z.string()).optional(),
    start: z.number().int().optional(),
    uri: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      usageRecords: "usage_records",
      firstPageUri: "first_page_uri",
      nextPageUri: "next_page_uri",
      pageSize: "page_size",
      previousPageUri: "previous_page_uri",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListUsageRecordAllTimeListUsageRecordAllTimeResponse$ {
  /** @deprecated use `ListUsageRecordAllTimeListUsageRecordAllTimeResponse$inboundSchema` instead. */
  export const inboundSchema =
    ListUsageRecordAllTimeListUsageRecordAllTimeResponse$inboundSchema;
  /** @deprecated use `ListUsageRecordAllTimeListUsageRecordAllTimeResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListUsageRecordAllTimeListUsageRecordAllTimeResponse$outboundSchema;
  /** @deprecated use `ListUsageRecordAllTimeListUsageRecordAllTimeResponse$Outbound` instead. */
  export type Outbound =
    ListUsageRecordAllTimeListUsageRecordAllTimeResponse$Outbound;
}

export function listUsageRecordAllTimeListUsageRecordAllTimeResponseToJSON(
  listUsageRecordAllTimeListUsageRecordAllTimeResponse:
    ListUsageRecordAllTimeListUsageRecordAllTimeResponse,
): string {
  return JSON.stringify(
    ListUsageRecordAllTimeListUsageRecordAllTimeResponse$outboundSchema.parse(
      listUsageRecordAllTimeListUsageRecordAllTimeResponse,
    ),
  );
}

export function listUsageRecordAllTimeListUsageRecordAllTimeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListUsageRecordAllTimeListUsageRecordAllTimeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListUsageRecordAllTimeListUsageRecordAllTimeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListUsageRecordAllTimeListUsageRecordAllTimeResponse' from JSON`,
  );
}

/** @internal */
export const ListUsageRecordAllTimeResponse$inboundSchema: z.ZodType<
  ListUsageRecordAllTimeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.lazy(() =>
    ListUsageRecordAllTimeListUsageRecordAllTimeResponse$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type ListUsageRecordAllTimeResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ListUsageRecordAllTimeListUsageRecordAllTimeResponse$Outbound;
};

/** @internal */
export const ListUsageRecordAllTimeResponse$outboundSchema: z.ZodType<
  ListUsageRecordAllTimeResponse$Outbound,
  z.ZodTypeDef,
  ListUsageRecordAllTimeResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.lazy(() =>
    ListUsageRecordAllTimeListUsageRecordAllTimeResponse$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListUsageRecordAllTimeResponse$ {
  /** @deprecated use `ListUsageRecordAllTimeResponse$inboundSchema` instead. */
  export const inboundSchema = ListUsageRecordAllTimeResponse$inboundSchema;
  /** @deprecated use `ListUsageRecordAllTimeResponse$outboundSchema` instead. */
  export const outboundSchema = ListUsageRecordAllTimeResponse$outboundSchema;
  /** @deprecated use `ListUsageRecordAllTimeResponse$Outbound` instead. */
  export type Outbound = ListUsageRecordAllTimeResponse$Outbound;
}

export function listUsageRecordAllTimeResponseToJSON(
  listUsageRecordAllTimeResponse: ListUsageRecordAllTimeResponse,
): string {
  return JSON.stringify(
    ListUsageRecordAllTimeResponse$outboundSchema.parse(
      listUsageRecordAllTimeResponse,
    ),
  );
}

export function listUsageRecordAllTimeResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListUsageRecordAllTimeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUsageRecordAllTimeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUsageRecordAllTimeResponse' from JSON`,
  );
}
