/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListDependentPhoneNumberServerList = [
  "https://api.twilio.com",
] as const;

export type ListDependentPhoneNumberRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the DependentPhoneNumber resources to read.
   */
  accountSid: string;
  /**
   * The SID of the Address resource associated with the phone number.
   */
  addressSid: string;
  /**
   * How many resources to return in each list page. The default is 50, and the maximum is 1000.
   */
  pageSize?: number | undefined;
  /**
   * The page index. This value is simply for client state.
   */
  page?: number | undefined;
  /**
   * The page token. This is provided by the API.
   */
  pageToken?: string | undefined;
};

/**
 * OK
 */
export type ListDependentPhoneNumberListDependentPhoneNumberResponse = {
  dependentPhoneNumbers?:
    | Array<components.ApiV2010AccountAddressDependentPhoneNumber>
    | undefined;
  end?: number | undefined;
  firstPageUri?: string | undefined;
  nextPageUri?: string | null | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
  previousPageUri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

export type ListDependentPhoneNumberResponse = {
  headers: { [k: string]: Array<string> };
  result: ListDependentPhoneNumberListDependentPhoneNumberResponse;
};

/** @internal */
export const ListDependentPhoneNumberRequest$inboundSchema: z.ZodType<
  ListDependentPhoneNumberRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  AddressSid: z.string(),
  PageSize: z.number().int().optional(),
  Page: z.number().int().optional(),
  PageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "AddressSid": "addressSid",
    "PageSize": "pageSize",
    "Page": "page",
    "PageToken": "pageToken",
  });
});

/** @internal */
export type ListDependentPhoneNumberRequest$Outbound = {
  AccountSid: string;
  AddressSid: string;
  PageSize?: number | undefined;
  Page?: number | undefined;
  PageToken?: string | undefined;
};

/** @internal */
export const ListDependentPhoneNumberRequest$outboundSchema: z.ZodType<
  ListDependentPhoneNumberRequest$Outbound,
  z.ZodTypeDef,
  ListDependentPhoneNumberRequest
> = z.object({
  accountSid: z.string(),
  addressSid: z.string(),
  pageSize: z.number().int().optional(),
  page: z.number().int().optional(),
  pageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    addressSid: "AddressSid",
    pageSize: "PageSize",
    page: "Page",
    pageToken: "PageToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListDependentPhoneNumberRequest$ {
  /** @deprecated use `ListDependentPhoneNumberRequest$inboundSchema` instead. */
  export const inboundSchema = ListDependentPhoneNumberRequest$inboundSchema;
  /** @deprecated use `ListDependentPhoneNumberRequest$outboundSchema` instead. */
  export const outboundSchema = ListDependentPhoneNumberRequest$outboundSchema;
  /** @deprecated use `ListDependentPhoneNumberRequest$Outbound` instead. */
  export type Outbound = ListDependentPhoneNumberRequest$Outbound;
}

export function listDependentPhoneNumberRequestToJSON(
  listDependentPhoneNumberRequest: ListDependentPhoneNumberRequest,
): string {
  return JSON.stringify(
    ListDependentPhoneNumberRequest$outboundSchema.parse(
      listDependentPhoneNumberRequest,
    ),
  );
}

export function listDependentPhoneNumberRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListDependentPhoneNumberRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDependentPhoneNumberRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDependentPhoneNumberRequest' from JSON`,
  );
}

/** @internal */
export const ListDependentPhoneNumberListDependentPhoneNumberResponse$inboundSchema:
  z.ZodType<
    ListDependentPhoneNumberListDependentPhoneNumberResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    dependent_phone_numbers: z.array(
      components.ApiV2010AccountAddressDependentPhoneNumber$inboundSchema,
    ).optional(),
    end: z.number().int().optional(),
    first_page_uri: z.string().optional(),
    next_page_uri: z.nullable(z.string()).optional(),
    page: z.number().int().optional(),
    page_size: z.number().int().optional(),
    previous_page_uri: z.nullable(z.string()).optional(),
    start: z.number().int().optional(),
    uri: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "dependent_phone_numbers": "dependentPhoneNumbers",
      "first_page_uri": "firstPageUri",
      "next_page_uri": "nextPageUri",
      "page_size": "pageSize",
      "previous_page_uri": "previousPageUri",
    });
  });

/** @internal */
export type ListDependentPhoneNumberListDependentPhoneNumberResponse$Outbound =
  {
    dependent_phone_numbers?:
      | Array<components.ApiV2010AccountAddressDependentPhoneNumber$Outbound>
      | undefined;
    end?: number | undefined;
    first_page_uri?: string | undefined;
    next_page_uri?: string | null | undefined;
    page?: number | undefined;
    page_size?: number | undefined;
    previous_page_uri?: string | null | undefined;
    start?: number | undefined;
    uri?: string | undefined;
  };

/** @internal */
export const ListDependentPhoneNumberListDependentPhoneNumberResponse$outboundSchema:
  z.ZodType<
    ListDependentPhoneNumberListDependentPhoneNumberResponse$Outbound,
    z.ZodTypeDef,
    ListDependentPhoneNumberListDependentPhoneNumberResponse
  > = z.object({
    dependentPhoneNumbers: z.array(
      components.ApiV2010AccountAddressDependentPhoneNumber$outboundSchema,
    ).optional(),
    end: z.number().int().optional(),
    firstPageUri: z.string().optional(),
    nextPageUri: z.nullable(z.string()).optional(),
    page: z.number().int().optional(),
    pageSize: z.number().int().optional(),
    previousPageUri: z.nullable(z.string()).optional(),
    start: z.number().int().optional(),
    uri: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      dependentPhoneNumbers: "dependent_phone_numbers",
      firstPageUri: "first_page_uri",
      nextPageUri: "next_page_uri",
      pageSize: "page_size",
      previousPageUri: "previous_page_uri",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListDependentPhoneNumberListDependentPhoneNumberResponse$ {
  /** @deprecated use `ListDependentPhoneNumberListDependentPhoneNumberResponse$inboundSchema` instead. */
  export const inboundSchema =
    ListDependentPhoneNumberListDependentPhoneNumberResponse$inboundSchema;
  /** @deprecated use `ListDependentPhoneNumberListDependentPhoneNumberResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListDependentPhoneNumberListDependentPhoneNumberResponse$outboundSchema;
  /** @deprecated use `ListDependentPhoneNumberListDependentPhoneNumberResponse$Outbound` instead. */
  export type Outbound =
    ListDependentPhoneNumberListDependentPhoneNumberResponse$Outbound;
}

export function listDependentPhoneNumberListDependentPhoneNumberResponseToJSON(
  listDependentPhoneNumberListDependentPhoneNumberResponse:
    ListDependentPhoneNumberListDependentPhoneNumberResponse,
): string {
  return JSON.stringify(
    ListDependentPhoneNumberListDependentPhoneNumberResponse$outboundSchema
      .parse(listDependentPhoneNumberListDependentPhoneNumberResponse),
  );
}

export function listDependentPhoneNumberListDependentPhoneNumberResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListDependentPhoneNumberListDependentPhoneNumberResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListDependentPhoneNumberListDependentPhoneNumberResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ListDependentPhoneNumberListDependentPhoneNumberResponse' from JSON`,
  );
}

/** @internal */
export const ListDependentPhoneNumberResponse$inboundSchema: z.ZodType<
  ListDependentPhoneNumberResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.lazy(() =>
    ListDependentPhoneNumberListDependentPhoneNumberResponse$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type ListDependentPhoneNumberResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ListDependentPhoneNumberListDependentPhoneNumberResponse$Outbound;
};

/** @internal */
export const ListDependentPhoneNumberResponse$outboundSchema: z.ZodType<
  ListDependentPhoneNumberResponse$Outbound,
  z.ZodTypeDef,
  ListDependentPhoneNumberResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.lazy(() =>
    ListDependentPhoneNumberListDependentPhoneNumberResponse$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListDependentPhoneNumberResponse$ {
  /** @deprecated use `ListDependentPhoneNumberResponse$inboundSchema` instead. */
  export const inboundSchema = ListDependentPhoneNumberResponse$inboundSchema;
  /** @deprecated use `ListDependentPhoneNumberResponse$outboundSchema` instead. */
  export const outboundSchema = ListDependentPhoneNumberResponse$outboundSchema;
  /** @deprecated use `ListDependentPhoneNumberResponse$Outbound` instead. */
  export type Outbound = ListDependentPhoneNumberResponse$Outbound;
}

export function listDependentPhoneNumberResponseToJSON(
  listDependentPhoneNumberResponse: ListDependentPhoneNumberResponse,
): string {
  return JSON.stringify(
    ListDependentPhoneNumberResponse$outboundSchema.parse(
      listDependentPhoneNumberResponse,
    ),
  );
}

export function listDependentPhoneNumberResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDependentPhoneNumberResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDependentPhoneNumberResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDependentPhoneNumberResponse' from JSON`,
  );
}
