/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListMediaServerList = [
  "https://api.twilio.com",
] as const;

export type ListMediaRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that is associated with the Media resources.
   */
  accountSid: string;
  /**
   * The SID of the Message resource that is associated with the Media resources.
   */
  messageSid: string;
  /**
   * Only include Media resources that were created on this date. Specify a date as `YYYY-MM-DD` in GMT, for example: `2009-07-06`, to read Media that were created on this date. You can also specify an inequality, such as `StartTime<=YYYY-MM-DD`, to read Media that were created on or before midnight of this date, and `StartTime>=YYYY-MM-DD` to read Media that were created on or after midnight of this date.
   */
  dateCreated?: Date | undefined;
  /**
   * Only include Media resources that were created on this date. Specify a date as `YYYY-MM-DD` in GMT, for example: `2009-07-06`, to read Media that were created on this date. You can also specify an inequality, such as `StartTime<=YYYY-MM-DD`, to read Media that were created on or before midnight of this date, and `StartTime>=YYYY-MM-DD` to read Media that were created on or after midnight of this date.
   */
  dateCreatedLessThan?: Date | undefined;
  /**
   * Only include Media resources that were created on this date. Specify a date as `YYYY-MM-DD` in GMT, for example: `2009-07-06`, to read Media that were created on this date. You can also specify an inequality, such as `StartTime<=YYYY-MM-DD`, to read Media that were created on or before midnight of this date, and `StartTime>=YYYY-MM-DD` to read Media that were created on or after midnight of this date.
   */
  dateCreatedGreaterThan?: Date | undefined;
  /**
   * How many resources to return in each list page. The default is 50, and the maximum is 1000.
   */
  pageSize?: number | undefined;
  /**
   * The page index. This value is simply for client state.
   */
  page?: number | undefined;
  /**
   * The page token. This is provided by the API.
   */
  pageToken?: string | undefined;
};

/**
 * OK
 */
export type ListMediaListMediaResponse = {
  mediaList?: Array<components.ApiV2010AccountMessageMedia> | undefined;
  end?: number | undefined;
  firstPageUri?: string | undefined;
  nextPageUri?: string | null | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
  previousPageUri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

export type ListMediaResponse = {
  headers: { [k: string]: Array<string> };
  result: ListMediaListMediaResponse;
};

/** @internal */
export const ListMediaRequest$inboundSchema: z.ZodType<
  ListMediaRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  MessageSid: z.string(),
  DateCreated: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  "DateCreated<": z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  "DateCreated>": z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  PageSize: z.number().int().optional(),
  Page: z.number().int().optional(),
  PageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "MessageSid": "messageSid",
    "DateCreated": "dateCreated",
    "DateCreated<": "dateCreatedLessThan",
    "DateCreated>": "dateCreatedGreaterThan",
    "PageSize": "pageSize",
    "Page": "page",
    "PageToken": "pageToken",
  });
});

/** @internal */
export type ListMediaRequest$Outbound = {
  AccountSid: string;
  MessageSid: string;
  DateCreated?: string | undefined;
  "DateCreated<"?: string | undefined;
  "DateCreated>"?: string | undefined;
  PageSize?: number | undefined;
  Page?: number | undefined;
  PageToken?: string | undefined;
};

/** @internal */
export const ListMediaRequest$outboundSchema: z.ZodType<
  ListMediaRequest$Outbound,
  z.ZodTypeDef,
  ListMediaRequest
> = z.object({
  accountSid: z.string(),
  messageSid: z.string(),
  dateCreated: z.date().transform(v => v.toISOString()).optional(),
  dateCreatedLessThan: z.date().transform(v => v.toISOString()).optional(),
  dateCreatedGreaterThan: z.date().transform(v => v.toISOString()).optional(),
  pageSize: z.number().int().optional(),
  page: z.number().int().optional(),
  pageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    messageSid: "MessageSid",
    dateCreated: "DateCreated",
    dateCreatedLessThan: "DateCreated<",
    dateCreatedGreaterThan: "DateCreated>",
    pageSize: "PageSize",
    page: "Page",
    pageToken: "PageToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMediaRequest$ {
  /** @deprecated use `ListMediaRequest$inboundSchema` instead. */
  export const inboundSchema = ListMediaRequest$inboundSchema;
  /** @deprecated use `ListMediaRequest$outboundSchema` instead. */
  export const outboundSchema = ListMediaRequest$outboundSchema;
  /** @deprecated use `ListMediaRequest$Outbound` instead. */
  export type Outbound = ListMediaRequest$Outbound;
}

export function listMediaRequestToJSON(
  listMediaRequest: ListMediaRequest,
): string {
  return JSON.stringify(
    ListMediaRequest$outboundSchema.parse(listMediaRequest),
  );
}

export function listMediaRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListMediaRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMediaRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMediaRequest' from JSON`,
  );
}

/** @internal */
export const ListMediaListMediaResponse$inboundSchema: z.ZodType<
  ListMediaListMediaResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  media_list: z.array(components.ApiV2010AccountMessageMedia$inboundSchema)
    .optional(),
  end: z.number().int().optional(),
  first_page_uri: z.string().optional(),
  next_page_uri: z.nullable(z.string()).optional(),
  page: z.number().int().optional(),
  page_size: z.number().int().optional(),
  previous_page_uri: z.nullable(z.string()).optional(),
  start: z.number().int().optional(),
  uri: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "media_list": "mediaList",
    "first_page_uri": "firstPageUri",
    "next_page_uri": "nextPageUri",
    "page_size": "pageSize",
    "previous_page_uri": "previousPageUri",
  });
});

/** @internal */
export type ListMediaListMediaResponse$Outbound = {
  media_list?:
    | Array<components.ApiV2010AccountMessageMedia$Outbound>
    | undefined;
  end?: number | undefined;
  first_page_uri?: string | undefined;
  next_page_uri?: string | null | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  previous_page_uri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

/** @internal */
export const ListMediaListMediaResponse$outboundSchema: z.ZodType<
  ListMediaListMediaResponse$Outbound,
  z.ZodTypeDef,
  ListMediaListMediaResponse
> = z.object({
  mediaList: z.array(components.ApiV2010AccountMessageMedia$outboundSchema)
    .optional(),
  end: z.number().int().optional(),
  firstPageUri: z.string().optional(),
  nextPageUri: z.nullable(z.string()).optional(),
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
  previousPageUri: z.nullable(z.string()).optional(),
  start: z.number().int().optional(),
  uri: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    mediaList: "media_list",
    firstPageUri: "first_page_uri",
    nextPageUri: "next_page_uri",
    pageSize: "page_size",
    previousPageUri: "previous_page_uri",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMediaListMediaResponse$ {
  /** @deprecated use `ListMediaListMediaResponse$inboundSchema` instead. */
  export const inboundSchema = ListMediaListMediaResponse$inboundSchema;
  /** @deprecated use `ListMediaListMediaResponse$outboundSchema` instead. */
  export const outboundSchema = ListMediaListMediaResponse$outboundSchema;
  /** @deprecated use `ListMediaListMediaResponse$Outbound` instead. */
  export type Outbound = ListMediaListMediaResponse$Outbound;
}

export function listMediaListMediaResponseToJSON(
  listMediaListMediaResponse: ListMediaListMediaResponse,
): string {
  return JSON.stringify(
    ListMediaListMediaResponse$outboundSchema.parse(listMediaListMediaResponse),
  );
}

export function listMediaListMediaResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMediaListMediaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMediaListMediaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMediaListMediaResponse' from JSON`,
  );
}

/** @internal */
export const ListMediaResponse$inboundSchema: z.ZodType<
  ListMediaResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.lazy(() => ListMediaListMediaResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type ListMediaResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ListMediaListMediaResponse$Outbound;
};

/** @internal */
export const ListMediaResponse$outboundSchema: z.ZodType<
  ListMediaResponse$Outbound,
  z.ZodTypeDef,
  ListMediaResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.lazy(() => ListMediaListMediaResponse$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMediaResponse$ {
  /** @deprecated use `ListMediaResponse$inboundSchema` instead. */
  export const inboundSchema = ListMediaResponse$inboundSchema;
  /** @deprecated use `ListMediaResponse$outboundSchema` instead. */
  export const outboundSchema = ListMediaResponse$outboundSchema;
  /** @deprecated use `ListMediaResponse$Outbound` instead. */
  export type Outbound = ListMediaResponse$Outbound;
}

export function listMediaResponseToJSON(
  listMediaResponse: ListMediaResponse,
): string {
  return JSON.stringify(
    ListMediaResponse$outboundSchema.parse(listMediaResponse),
  );
}

export function listMediaResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMediaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMediaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMediaResponse' from JSON`,
  );
}
