/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListMessageServerList = [
  "https://api.twilio.com",
] as const;

export type ListMessageRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) associated with the Message resources.
   */
  accountSid: string;
  /**
   * Filter by recipient. For example: Set this `to` parameter to `+15558881111` to retrieve a list of Message resources with `to` properties of `+15558881111`
   */
  to?: string | undefined;
  /**
   * Filter by sender. For example: Set this `from` parameter to `+15552229999` to retrieve a list of Message resources with `from` properties of `+15552229999`
   */
  from?: string | undefined;
  /**
   * Filter by Message `sent_date`. Accepts GMT dates in the following formats: `YYYY-MM-DD` (to find Messages with a specific `sent_date`), `<=YYYY-MM-DD` (to find Messages with `sent_date`s on and before a specific date), and `>=YYYY-MM-DD` (to find Messages with `sent_dates` on and after a specific date).
   */
  dateSent?: Date | undefined;
  /**
   * Filter by Message `sent_date`. Accepts GMT dates in the following formats: `YYYY-MM-DD` (to find Messages with a specific `sent_date`), `<=YYYY-MM-DD` (to find Messages with `sent_date`s on and before a specific date), and `>=YYYY-MM-DD` (to find Messages with `sent_dates` on and after a specific date).
   */
  dateSentLessThan?: Date | undefined;
  /**
   * Filter by Message `sent_date`. Accepts GMT dates in the following formats: `YYYY-MM-DD` (to find Messages with a specific `sent_date`), `<=YYYY-MM-DD` (to find Messages with `sent_date`s on and before a specific date), and `>=YYYY-MM-DD` (to find Messages with `sent_dates` on and after a specific date).
   */
  dateSentGreaterThan?: Date | undefined;
  /**
   * How many resources to return in each list page. The default is 50, and the maximum is 1000.
   */
  pageSize?: number | undefined;
  /**
   * The page index. This value is simply for client state.
   */
  page?: number | undefined;
  /**
   * The page token. This is provided by the API.
   */
  pageToken?: string | undefined;
};

/**
 * OK
 */
export type ListMessageListMessageResponse = {
  messages?: Array<components.ApiV2010AccountMessage> | undefined;
  end?: number | undefined;
  firstPageUri?: string | undefined;
  nextPageUri?: string | null | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
  previousPageUri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

export type ListMessageResponse = {
  headers: { [k: string]: Array<string> };
  result: ListMessageListMessageResponse;
};

/** @internal */
export const ListMessageRequest$inboundSchema: z.ZodType<
  ListMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  To: z.string().optional(),
  From: z.string().optional(),
  DateSent: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  "DateSent<": z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  "DateSent>": z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  PageSize: z.number().int().optional(),
  Page: z.number().int().optional(),
  PageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "To": "to",
    "From": "from",
    "DateSent": "dateSent",
    "DateSent<": "dateSentLessThan",
    "DateSent>": "dateSentGreaterThan",
    "PageSize": "pageSize",
    "Page": "page",
    "PageToken": "pageToken",
  });
});

/** @internal */
export type ListMessageRequest$Outbound = {
  AccountSid: string;
  To?: string | undefined;
  From?: string | undefined;
  DateSent?: string | undefined;
  "DateSent<"?: string | undefined;
  "DateSent>"?: string | undefined;
  PageSize?: number | undefined;
  Page?: number | undefined;
  PageToken?: string | undefined;
};

/** @internal */
export const ListMessageRequest$outboundSchema: z.ZodType<
  ListMessageRequest$Outbound,
  z.ZodTypeDef,
  ListMessageRequest
> = z.object({
  accountSid: z.string(),
  to: z.string().optional(),
  from: z.string().optional(),
  dateSent: z.date().transform(v => v.toISOString()).optional(),
  dateSentLessThan: z.date().transform(v => v.toISOString()).optional(),
  dateSentGreaterThan: z.date().transform(v => v.toISOString()).optional(),
  pageSize: z.number().int().optional(),
  page: z.number().int().optional(),
  pageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    to: "To",
    from: "From",
    dateSent: "DateSent",
    dateSentLessThan: "DateSent<",
    dateSentGreaterThan: "DateSent>",
    pageSize: "PageSize",
    page: "Page",
    pageToken: "PageToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMessageRequest$ {
  /** @deprecated use `ListMessageRequest$inboundSchema` instead. */
  export const inboundSchema = ListMessageRequest$inboundSchema;
  /** @deprecated use `ListMessageRequest$outboundSchema` instead. */
  export const outboundSchema = ListMessageRequest$outboundSchema;
  /** @deprecated use `ListMessageRequest$Outbound` instead. */
  export type Outbound = ListMessageRequest$Outbound;
}

export function listMessageRequestToJSON(
  listMessageRequest: ListMessageRequest,
): string {
  return JSON.stringify(
    ListMessageRequest$outboundSchema.parse(listMessageRequest),
  );
}

export function listMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMessageRequest' from JSON`,
  );
}

/** @internal */
export const ListMessageListMessageResponse$inboundSchema: z.ZodType<
  ListMessageListMessageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  messages: z.array(components.ApiV2010AccountMessage$inboundSchema).optional(),
  end: z.number().int().optional(),
  first_page_uri: z.string().optional(),
  next_page_uri: z.nullable(z.string()).optional(),
  page: z.number().int().optional(),
  page_size: z.number().int().optional(),
  previous_page_uri: z.nullable(z.string()).optional(),
  start: z.number().int().optional(),
  uri: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "first_page_uri": "firstPageUri",
    "next_page_uri": "nextPageUri",
    "page_size": "pageSize",
    "previous_page_uri": "previousPageUri",
  });
});

/** @internal */
export type ListMessageListMessageResponse$Outbound = {
  messages?: Array<components.ApiV2010AccountMessage$Outbound> | undefined;
  end?: number | undefined;
  first_page_uri?: string | undefined;
  next_page_uri?: string | null | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  previous_page_uri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

/** @internal */
export const ListMessageListMessageResponse$outboundSchema: z.ZodType<
  ListMessageListMessageResponse$Outbound,
  z.ZodTypeDef,
  ListMessageListMessageResponse
> = z.object({
  messages: z.array(components.ApiV2010AccountMessage$outboundSchema)
    .optional(),
  end: z.number().int().optional(),
  firstPageUri: z.string().optional(),
  nextPageUri: z.nullable(z.string()).optional(),
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
  previousPageUri: z.nullable(z.string()).optional(),
  start: z.number().int().optional(),
  uri: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    firstPageUri: "first_page_uri",
    nextPageUri: "next_page_uri",
    pageSize: "page_size",
    previousPageUri: "previous_page_uri",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMessageListMessageResponse$ {
  /** @deprecated use `ListMessageListMessageResponse$inboundSchema` instead. */
  export const inboundSchema = ListMessageListMessageResponse$inboundSchema;
  /** @deprecated use `ListMessageListMessageResponse$outboundSchema` instead. */
  export const outboundSchema = ListMessageListMessageResponse$outboundSchema;
  /** @deprecated use `ListMessageListMessageResponse$Outbound` instead. */
  export type Outbound = ListMessageListMessageResponse$Outbound;
}

export function listMessageListMessageResponseToJSON(
  listMessageListMessageResponse: ListMessageListMessageResponse,
): string {
  return JSON.stringify(
    ListMessageListMessageResponse$outboundSchema.parse(
      listMessageListMessageResponse,
    ),
  );
}

export function listMessageListMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMessageListMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMessageListMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMessageListMessageResponse' from JSON`,
  );
}

/** @internal */
export const ListMessageResponse$inboundSchema: z.ZodType<
  ListMessageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.lazy(() => ListMessageListMessageResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type ListMessageResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ListMessageListMessageResponse$Outbound;
};

/** @internal */
export const ListMessageResponse$outboundSchema: z.ZodType<
  ListMessageResponse$Outbound,
  z.ZodTypeDef,
  ListMessageResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.lazy(() => ListMessageListMessageResponse$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMessageResponse$ {
  /** @deprecated use `ListMessageResponse$inboundSchema` instead. */
  export const inboundSchema = ListMessageResponse$inboundSchema;
  /** @deprecated use `ListMessageResponse$outboundSchema` instead. */
  export const outboundSchema = ListMessageResponse$outboundSchema;
  /** @deprecated use `ListMessageResponse$Outbound` instead. */
  export type Outbound = ListMessageResponse$Outbound;
}

export function listMessageResponseToJSON(
  listMessageResponse: ListMessageResponse,
): string {
  return JSON.stringify(
    ListMessageResponse$outboundSchema.parse(listMessageResponse),
  );
}

export function listMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMessageResponse' from JSON`,
  );
}
