/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListShortCodeServerList = [
  "https://api.twilio.com",
] as const;

export type ListShortCodeRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ShortCode resource(s) to read.
   */
  accountSid: string;
  /**
   * The string that identifies the ShortCode resources to read.
   */
  friendlyName?: string | undefined;
  /**
   * Only show the ShortCode resources that match this pattern. You can specify partial numbers and use '*' as a wildcard for any digit.
   */
  shortCode?: string | undefined;
  /**
   * How many resources to return in each list page. The default is 50, and the maximum is 1000.
   */
  pageSize?: number | undefined;
  /**
   * The page index. This value is simply for client state.
   */
  page?: number | undefined;
  /**
   * The page token. This is provided by the API.
   */
  pageToken?: string | undefined;
};

/**
 * OK
 */
export type ListShortCodeListShortCodeResponse = {
  shortCodes?: Array<components.ApiV2010AccountShortCode> | undefined;
  end?: number | undefined;
  firstPageUri?: string | undefined;
  nextPageUri?: string | null | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
  previousPageUri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

export type ListShortCodeResponse = {
  headers: { [k: string]: Array<string> };
  result: ListShortCodeListShortCodeResponse;
};

/** @internal */
export const ListShortCodeRequest$inboundSchema: z.ZodType<
  ListShortCodeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  FriendlyName: z.string().optional(),
  ShortCode: z.string().optional(),
  PageSize: z.number().int().optional(),
  Page: z.number().int().optional(),
  PageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "FriendlyName": "friendlyName",
    "ShortCode": "shortCode",
    "PageSize": "pageSize",
    "Page": "page",
    "PageToken": "pageToken",
  });
});

/** @internal */
export type ListShortCodeRequest$Outbound = {
  AccountSid: string;
  FriendlyName?: string | undefined;
  ShortCode?: string | undefined;
  PageSize?: number | undefined;
  Page?: number | undefined;
  PageToken?: string | undefined;
};

/** @internal */
export const ListShortCodeRequest$outboundSchema: z.ZodType<
  ListShortCodeRequest$Outbound,
  z.ZodTypeDef,
  ListShortCodeRequest
> = z.object({
  accountSid: z.string(),
  friendlyName: z.string().optional(),
  shortCode: z.string().optional(),
  pageSize: z.number().int().optional(),
  page: z.number().int().optional(),
  pageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    friendlyName: "FriendlyName",
    shortCode: "ShortCode",
    pageSize: "PageSize",
    page: "Page",
    pageToken: "PageToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListShortCodeRequest$ {
  /** @deprecated use `ListShortCodeRequest$inboundSchema` instead. */
  export const inboundSchema = ListShortCodeRequest$inboundSchema;
  /** @deprecated use `ListShortCodeRequest$outboundSchema` instead. */
  export const outboundSchema = ListShortCodeRequest$outboundSchema;
  /** @deprecated use `ListShortCodeRequest$Outbound` instead. */
  export type Outbound = ListShortCodeRequest$Outbound;
}

export function listShortCodeRequestToJSON(
  listShortCodeRequest: ListShortCodeRequest,
): string {
  return JSON.stringify(
    ListShortCodeRequest$outboundSchema.parse(listShortCodeRequest),
  );
}

export function listShortCodeRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListShortCodeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListShortCodeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListShortCodeRequest' from JSON`,
  );
}

/** @internal */
export const ListShortCodeListShortCodeResponse$inboundSchema: z.ZodType<
  ListShortCodeListShortCodeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  short_codes: z.array(components.ApiV2010AccountShortCode$inboundSchema)
    .optional(),
  end: z.number().int().optional(),
  first_page_uri: z.string().optional(),
  next_page_uri: z.nullable(z.string()).optional(),
  page: z.number().int().optional(),
  page_size: z.number().int().optional(),
  previous_page_uri: z.nullable(z.string()).optional(),
  start: z.number().int().optional(),
  uri: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "short_codes": "shortCodes",
    "first_page_uri": "firstPageUri",
    "next_page_uri": "nextPageUri",
    "page_size": "pageSize",
    "previous_page_uri": "previousPageUri",
  });
});

/** @internal */
export type ListShortCodeListShortCodeResponse$Outbound = {
  short_codes?: Array<components.ApiV2010AccountShortCode$Outbound> | undefined;
  end?: number | undefined;
  first_page_uri?: string | undefined;
  next_page_uri?: string | null | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  previous_page_uri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

/** @internal */
export const ListShortCodeListShortCodeResponse$outboundSchema: z.ZodType<
  ListShortCodeListShortCodeResponse$Outbound,
  z.ZodTypeDef,
  ListShortCodeListShortCodeResponse
> = z.object({
  shortCodes: z.array(components.ApiV2010AccountShortCode$outboundSchema)
    .optional(),
  end: z.number().int().optional(),
  firstPageUri: z.string().optional(),
  nextPageUri: z.nullable(z.string()).optional(),
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
  previousPageUri: z.nullable(z.string()).optional(),
  start: z.number().int().optional(),
  uri: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    shortCodes: "short_codes",
    firstPageUri: "first_page_uri",
    nextPageUri: "next_page_uri",
    pageSize: "page_size",
    previousPageUri: "previous_page_uri",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListShortCodeListShortCodeResponse$ {
  /** @deprecated use `ListShortCodeListShortCodeResponse$inboundSchema` instead. */
  export const inboundSchema = ListShortCodeListShortCodeResponse$inboundSchema;
  /** @deprecated use `ListShortCodeListShortCodeResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListShortCodeListShortCodeResponse$outboundSchema;
  /** @deprecated use `ListShortCodeListShortCodeResponse$Outbound` instead. */
  export type Outbound = ListShortCodeListShortCodeResponse$Outbound;
}

export function listShortCodeListShortCodeResponseToJSON(
  listShortCodeListShortCodeResponse: ListShortCodeListShortCodeResponse,
): string {
  return JSON.stringify(
    ListShortCodeListShortCodeResponse$outboundSchema.parse(
      listShortCodeListShortCodeResponse,
    ),
  );
}

export function listShortCodeListShortCodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListShortCodeListShortCodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListShortCodeListShortCodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListShortCodeListShortCodeResponse' from JSON`,
  );
}

/** @internal */
export const ListShortCodeResponse$inboundSchema: z.ZodType<
  ListShortCodeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.lazy(() => ListShortCodeListShortCodeResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type ListShortCodeResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ListShortCodeListShortCodeResponse$Outbound;
};

/** @internal */
export const ListShortCodeResponse$outboundSchema: z.ZodType<
  ListShortCodeResponse$Outbound,
  z.ZodTypeDef,
  ListShortCodeResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.lazy(() => ListShortCodeListShortCodeResponse$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListShortCodeResponse$ {
  /** @deprecated use `ListShortCodeResponse$inboundSchema` instead. */
  export const inboundSchema = ListShortCodeResponse$inboundSchema;
  /** @deprecated use `ListShortCodeResponse$outboundSchema` instead. */
  export const outboundSchema = ListShortCodeResponse$outboundSchema;
  /** @deprecated use `ListShortCodeResponse$Outbound` instead. */
  export type Outbound = ListShortCodeResponse$Outbound;
}

export function listShortCodeResponseToJSON(
  listShortCodeResponse: ListShortCodeResponse,
): string {
  return JSON.stringify(
    ListShortCodeResponse$outboundSchema.parse(listShortCodeResponse),
  );
}

export function listShortCodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListShortCodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListShortCodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListShortCodeResponse' from JSON`,
  );
}
