/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListParticipantServerList = [
  "https://api.twilio.com",
] as const;

export type ListParticipantRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Participant resources to read.
   */
  accountSid: string;
  /**
   * The SID of the conference with the participants to read.
   */
  conferenceSid: string;
  /**
   * Whether to return only participants that are muted. Can be: `true` or `false`.
   */
  muted?: boolean | undefined;
  /**
   * Whether to return only participants that are on hold. Can be: `true` or `false`.
   */
  hold?: boolean | undefined;
  /**
   * Whether to return only participants who are coaching another call. Can be: `true` or `false`.
   */
  coaching?: boolean | undefined;
  /**
   * How many resources to return in each list page. The default is 50, and the maximum is 1000.
   */
  pageSize?: number | undefined;
  /**
   * The page index. This value is simply for client state.
   */
  page?: number | undefined;
  /**
   * The page token. This is provided by the API.
   */
  pageToken?: string | undefined;
};

/**
 * OK
 */
export type ListParticipantListParticipantResponse = {
  participants?:
    | Array<components.ApiV2010AccountConferenceParticipant>
    | undefined;
  end?: number | undefined;
  firstPageUri?: string | undefined;
  nextPageUri?: string | null | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
  previousPageUri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

export type ListParticipantResponse = {
  headers: { [k: string]: Array<string> };
  result: ListParticipantListParticipantResponse;
};

/** @internal */
export const ListParticipantRequest$inboundSchema: z.ZodType<
  ListParticipantRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  ConferenceSid: z.string(),
  Muted: z.boolean().optional(),
  Hold: z.boolean().optional(),
  Coaching: z.boolean().optional(),
  PageSize: z.number().int().optional(),
  Page: z.number().int().optional(),
  PageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "ConferenceSid": "conferenceSid",
    "Muted": "muted",
    "Hold": "hold",
    "Coaching": "coaching",
    "PageSize": "pageSize",
    "Page": "page",
    "PageToken": "pageToken",
  });
});

/** @internal */
export type ListParticipantRequest$Outbound = {
  AccountSid: string;
  ConferenceSid: string;
  Muted?: boolean | undefined;
  Hold?: boolean | undefined;
  Coaching?: boolean | undefined;
  PageSize?: number | undefined;
  Page?: number | undefined;
  PageToken?: string | undefined;
};

/** @internal */
export const ListParticipantRequest$outboundSchema: z.ZodType<
  ListParticipantRequest$Outbound,
  z.ZodTypeDef,
  ListParticipantRequest
> = z.object({
  accountSid: z.string(),
  conferenceSid: z.string(),
  muted: z.boolean().optional(),
  hold: z.boolean().optional(),
  coaching: z.boolean().optional(),
  pageSize: z.number().int().optional(),
  page: z.number().int().optional(),
  pageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    conferenceSid: "ConferenceSid",
    muted: "Muted",
    hold: "Hold",
    coaching: "Coaching",
    pageSize: "PageSize",
    page: "Page",
    pageToken: "PageToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListParticipantRequest$ {
  /** @deprecated use `ListParticipantRequest$inboundSchema` instead. */
  export const inboundSchema = ListParticipantRequest$inboundSchema;
  /** @deprecated use `ListParticipantRequest$outboundSchema` instead. */
  export const outboundSchema = ListParticipantRequest$outboundSchema;
  /** @deprecated use `ListParticipantRequest$Outbound` instead. */
  export type Outbound = ListParticipantRequest$Outbound;
}

export function listParticipantRequestToJSON(
  listParticipantRequest: ListParticipantRequest,
): string {
  return JSON.stringify(
    ListParticipantRequest$outboundSchema.parse(listParticipantRequest),
  );
}

export function listParticipantRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListParticipantRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListParticipantRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListParticipantRequest' from JSON`,
  );
}

/** @internal */
export const ListParticipantListParticipantResponse$inboundSchema: z.ZodType<
  ListParticipantListParticipantResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  participants: z.array(
    components.ApiV2010AccountConferenceParticipant$inboundSchema,
  ).optional(),
  end: z.number().int().optional(),
  first_page_uri: z.string().optional(),
  next_page_uri: z.nullable(z.string()).optional(),
  page: z.number().int().optional(),
  page_size: z.number().int().optional(),
  previous_page_uri: z.nullable(z.string()).optional(),
  start: z.number().int().optional(),
  uri: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "first_page_uri": "firstPageUri",
    "next_page_uri": "nextPageUri",
    "page_size": "pageSize",
    "previous_page_uri": "previousPageUri",
  });
});

/** @internal */
export type ListParticipantListParticipantResponse$Outbound = {
  participants?:
    | Array<components.ApiV2010AccountConferenceParticipant$Outbound>
    | undefined;
  end?: number | undefined;
  first_page_uri?: string | undefined;
  next_page_uri?: string | null | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
  previous_page_uri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

/** @internal */
export const ListParticipantListParticipantResponse$outboundSchema: z.ZodType<
  ListParticipantListParticipantResponse$Outbound,
  z.ZodTypeDef,
  ListParticipantListParticipantResponse
> = z.object({
  participants: z.array(
    components.ApiV2010AccountConferenceParticipant$outboundSchema,
  ).optional(),
  end: z.number().int().optional(),
  firstPageUri: z.string().optional(),
  nextPageUri: z.nullable(z.string()).optional(),
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
  previousPageUri: z.nullable(z.string()).optional(),
  start: z.number().int().optional(),
  uri: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    firstPageUri: "first_page_uri",
    nextPageUri: "next_page_uri",
    pageSize: "page_size",
    previousPageUri: "previous_page_uri",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListParticipantListParticipantResponse$ {
  /** @deprecated use `ListParticipantListParticipantResponse$inboundSchema` instead. */
  export const inboundSchema =
    ListParticipantListParticipantResponse$inboundSchema;
  /** @deprecated use `ListParticipantListParticipantResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListParticipantListParticipantResponse$outboundSchema;
  /** @deprecated use `ListParticipantListParticipantResponse$Outbound` instead. */
  export type Outbound = ListParticipantListParticipantResponse$Outbound;
}

export function listParticipantListParticipantResponseToJSON(
  listParticipantListParticipantResponse:
    ListParticipantListParticipantResponse,
): string {
  return JSON.stringify(
    ListParticipantListParticipantResponse$outboundSchema.parse(
      listParticipantListParticipantResponse,
    ),
  );
}

export function listParticipantListParticipantResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListParticipantListParticipantResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListParticipantListParticipantResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListParticipantListParticipantResponse' from JSON`,
  );
}

/** @internal */
export const ListParticipantResponse$inboundSchema: z.ZodType<
  ListParticipantResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.lazy(() => ListParticipantListParticipantResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type ListParticipantResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ListParticipantListParticipantResponse$Outbound;
};

/** @internal */
export const ListParticipantResponse$outboundSchema: z.ZodType<
  ListParticipantResponse$Outbound,
  z.ZodTypeDef,
  ListParticipantResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.lazy(() => ListParticipantListParticipantResponse$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListParticipantResponse$ {
  /** @deprecated use `ListParticipantResponse$inboundSchema` instead. */
  export const inboundSchema = ListParticipantResponse$inboundSchema;
  /** @deprecated use `ListParticipantResponse$outboundSchema` instead. */
  export const outboundSchema = ListParticipantResponse$outboundSchema;
  /** @deprecated use `ListParticipantResponse$Outbound` instead. */
  export type Outbound = ListParticipantResponse$Outbound;
}

export function listParticipantResponseToJSON(
  listParticipantResponse: ListParticipantResponse,
): string {
  return JSON.stringify(
    ListParticipantResponse$outboundSchema.parse(listParticipantResponse),
  );
}

export function listParticipantResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListParticipantResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListParticipantResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListParticipantResponse' from JSON`,
  );
}
