/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListRecordingTranscriptionServerList = [
  "https://api.twilio.com",
] as const;

export type ListRecordingTranscriptionRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Transcription resources to read.
   */
  accountSid: string;
  /**
   * The SID of the [Recording](https://www.twilio.com/docs/voice/api/recording) that created the transcriptions to read.
   */
  recordingSid: string;
  /**
   * How many resources to return in each list page. The default is 50, and the maximum is 1000.
   */
  pageSize?: number | undefined;
  /**
   * The page index. This value is simply for client state.
   */
  page?: number | undefined;
  /**
   * The page token. This is provided by the API.
   */
  pageToken?: string | undefined;
};

/**
 * OK
 */
export type ListRecordingTranscriptionListRecordingTranscriptionResponse = {
  transcriptions?:
    | Array<components.ApiV2010AccountRecordingRecordingTranscription>
    | undefined;
  end?: number | undefined;
  firstPageUri?: string | undefined;
  nextPageUri?: string | null | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
  previousPageUri?: string | null | undefined;
  start?: number | undefined;
  uri?: string | undefined;
};

export type ListRecordingTranscriptionResponse = {
  headers: { [k: string]: Array<string> };
  result: ListRecordingTranscriptionListRecordingTranscriptionResponse;
};

/** @internal */
export const ListRecordingTranscriptionRequest$inboundSchema: z.ZodType<
  ListRecordingTranscriptionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  RecordingSid: z.string(),
  PageSize: z.number().int().optional(),
  Page: z.number().int().optional(),
  PageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "RecordingSid": "recordingSid",
    "PageSize": "pageSize",
    "Page": "page",
    "PageToken": "pageToken",
  });
});

/** @internal */
export type ListRecordingTranscriptionRequest$Outbound = {
  AccountSid: string;
  RecordingSid: string;
  PageSize?: number | undefined;
  Page?: number | undefined;
  PageToken?: string | undefined;
};

/** @internal */
export const ListRecordingTranscriptionRequest$outboundSchema: z.ZodType<
  ListRecordingTranscriptionRequest$Outbound,
  z.ZodTypeDef,
  ListRecordingTranscriptionRequest
> = z.object({
  accountSid: z.string(),
  recordingSid: z.string(),
  pageSize: z.number().int().optional(),
  page: z.number().int().optional(),
  pageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    recordingSid: "RecordingSid",
    pageSize: "PageSize",
    page: "Page",
    pageToken: "PageToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRecordingTranscriptionRequest$ {
  /** @deprecated use `ListRecordingTranscriptionRequest$inboundSchema` instead. */
  export const inboundSchema = ListRecordingTranscriptionRequest$inboundSchema;
  /** @deprecated use `ListRecordingTranscriptionRequest$outboundSchema` instead. */
  export const outboundSchema =
    ListRecordingTranscriptionRequest$outboundSchema;
  /** @deprecated use `ListRecordingTranscriptionRequest$Outbound` instead. */
  export type Outbound = ListRecordingTranscriptionRequest$Outbound;
}

export function listRecordingTranscriptionRequestToJSON(
  listRecordingTranscriptionRequest: ListRecordingTranscriptionRequest,
): string {
  return JSON.stringify(
    ListRecordingTranscriptionRequest$outboundSchema.parse(
      listRecordingTranscriptionRequest,
    ),
  );
}

export function listRecordingTranscriptionRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListRecordingTranscriptionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRecordingTranscriptionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRecordingTranscriptionRequest' from JSON`,
  );
}

/** @internal */
export const ListRecordingTranscriptionListRecordingTranscriptionResponse$inboundSchema:
  z.ZodType<
    ListRecordingTranscriptionListRecordingTranscriptionResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    transcriptions: z.array(
      components.ApiV2010AccountRecordingRecordingTranscription$inboundSchema,
    ).optional(),
    end: z.number().int().optional(),
    first_page_uri: z.string().optional(),
    next_page_uri: z.nullable(z.string()).optional(),
    page: z.number().int().optional(),
    page_size: z.number().int().optional(),
    previous_page_uri: z.nullable(z.string()).optional(),
    start: z.number().int().optional(),
    uri: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "first_page_uri": "firstPageUri",
      "next_page_uri": "nextPageUri",
      "page_size": "pageSize",
      "previous_page_uri": "previousPageUri",
    });
  });

/** @internal */
export type ListRecordingTranscriptionListRecordingTranscriptionResponse$Outbound =
  {
    transcriptions?:
      | Array<
        components.ApiV2010AccountRecordingRecordingTranscription$Outbound
      >
      | undefined;
    end?: number | undefined;
    first_page_uri?: string | undefined;
    next_page_uri?: string | null | undefined;
    page?: number | undefined;
    page_size?: number | undefined;
    previous_page_uri?: string | null | undefined;
    start?: number | undefined;
    uri?: string | undefined;
  };

/** @internal */
export const ListRecordingTranscriptionListRecordingTranscriptionResponse$outboundSchema:
  z.ZodType<
    ListRecordingTranscriptionListRecordingTranscriptionResponse$Outbound,
    z.ZodTypeDef,
    ListRecordingTranscriptionListRecordingTranscriptionResponse
  > = z.object({
    transcriptions: z.array(
      components.ApiV2010AccountRecordingRecordingTranscription$outboundSchema,
    ).optional(),
    end: z.number().int().optional(),
    firstPageUri: z.string().optional(),
    nextPageUri: z.nullable(z.string()).optional(),
    page: z.number().int().optional(),
    pageSize: z.number().int().optional(),
    previousPageUri: z.nullable(z.string()).optional(),
    start: z.number().int().optional(),
    uri: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      firstPageUri: "first_page_uri",
      nextPageUri: "next_page_uri",
      pageSize: "page_size",
      previousPageUri: "previous_page_uri",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRecordingTranscriptionListRecordingTranscriptionResponse$ {
  /** @deprecated use `ListRecordingTranscriptionListRecordingTranscriptionResponse$inboundSchema` instead. */
  export const inboundSchema =
    ListRecordingTranscriptionListRecordingTranscriptionResponse$inboundSchema;
  /** @deprecated use `ListRecordingTranscriptionListRecordingTranscriptionResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListRecordingTranscriptionListRecordingTranscriptionResponse$outboundSchema;
  /** @deprecated use `ListRecordingTranscriptionListRecordingTranscriptionResponse$Outbound` instead. */
  export type Outbound =
    ListRecordingTranscriptionListRecordingTranscriptionResponse$Outbound;
}

export function listRecordingTranscriptionListRecordingTranscriptionResponseToJSON(
  listRecordingTranscriptionListRecordingTranscriptionResponse:
    ListRecordingTranscriptionListRecordingTranscriptionResponse,
): string {
  return JSON.stringify(
    ListRecordingTranscriptionListRecordingTranscriptionResponse$outboundSchema
      .parse(listRecordingTranscriptionListRecordingTranscriptionResponse),
  );
}

export function listRecordingTranscriptionListRecordingTranscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ListRecordingTranscriptionListRecordingTranscriptionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListRecordingTranscriptionListRecordingTranscriptionResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ListRecordingTranscriptionListRecordingTranscriptionResponse' from JSON`,
  );
}

/** @internal */
export const ListRecordingTranscriptionResponse$inboundSchema: z.ZodType<
  ListRecordingTranscriptionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: z.lazy(() =>
    ListRecordingTranscriptionListRecordingTranscriptionResponse$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type ListRecordingTranscriptionResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: ListRecordingTranscriptionListRecordingTranscriptionResponse$Outbound;
};

/** @internal */
export const ListRecordingTranscriptionResponse$outboundSchema: z.ZodType<
  ListRecordingTranscriptionResponse$Outbound,
  z.ZodTypeDef,
  ListRecordingTranscriptionResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.lazy(() =>
    ListRecordingTranscriptionListRecordingTranscriptionResponse$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRecordingTranscriptionResponse$ {
  /** @deprecated use `ListRecordingTranscriptionResponse$inboundSchema` instead. */
  export const inboundSchema = ListRecordingTranscriptionResponse$inboundSchema;
  /** @deprecated use `ListRecordingTranscriptionResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListRecordingTranscriptionResponse$outboundSchema;
  /** @deprecated use `ListRecordingTranscriptionResponse$Outbound` instead. */
  export type Outbound = ListRecordingTranscriptionResponse$Outbound;
}

export function listRecordingTranscriptionResponseToJSON(
  listRecordingTranscriptionResponse: ListRecordingTranscriptionResponse,
): string {
  return JSON.stringify(
    ListRecordingTranscriptionResponse$outboundSchema.parse(
      listRecordingTranscriptionResponse,
    ),
  );
}

export function listRecordingTranscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListRecordingTranscriptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListRecordingTranscriptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRecordingTranscriptionResponse' from JSON`,
  );
}
