/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const UpdateCallRecordingServerList = [
  "https://api.twilio.com",
] as const;

export type UpdateCallRecordingUpdateCallRecordingRequest = {
  status: components.CallRecordingEnumStatus;
  /**
   * Whether to record during a pause. Can be: `skip` or `silence` and the default is `silence`. `skip` does not record during the pause period, while `silence` will replace the actual audio of the call with silence during the pause period. This parameter only applies when setting `status` is set to `paused`.
   */
  pauseBehavior?: string | undefined;
};

export type UpdateCallRecordingRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording resource to update.
   */
  accountSid: string;
  /**
   * The [Call](https://www.twilio.com/docs/voice/api/call-resource) SID of the resource to update.
   */
  callSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the Recording resource to update.
   */
  sid: string;
  requestBody?: UpdateCallRecordingUpdateCallRecordingRequest | undefined;
};

export type UpdateCallRecordingResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountCallCallRecording;
};

/** @internal */
export const UpdateCallRecordingUpdateCallRecordingRequest$inboundSchema:
  z.ZodType<
    UpdateCallRecordingUpdateCallRecordingRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Status: components.CallRecordingEnumStatus$inboundSchema,
    PauseBehavior: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "Status": "status",
      "PauseBehavior": "pauseBehavior",
    });
  });

/** @internal */
export type UpdateCallRecordingUpdateCallRecordingRequest$Outbound = {
  Status: string;
  PauseBehavior?: string | undefined;
};

/** @internal */
export const UpdateCallRecordingUpdateCallRecordingRequest$outboundSchema:
  z.ZodType<
    UpdateCallRecordingUpdateCallRecordingRequest$Outbound,
    z.ZodTypeDef,
    UpdateCallRecordingUpdateCallRecordingRequest
  > = z.object({
    status: components.CallRecordingEnumStatus$outboundSchema,
    pauseBehavior: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      status: "Status",
      pauseBehavior: "PauseBehavior",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCallRecordingUpdateCallRecordingRequest$ {
  /** @deprecated use `UpdateCallRecordingUpdateCallRecordingRequest$inboundSchema` instead. */
  export const inboundSchema =
    UpdateCallRecordingUpdateCallRecordingRequest$inboundSchema;
  /** @deprecated use `UpdateCallRecordingUpdateCallRecordingRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateCallRecordingUpdateCallRecordingRequest$outboundSchema;
  /** @deprecated use `UpdateCallRecordingUpdateCallRecordingRequest$Outbound` instead. */
  export type Outbound = UpdateCallRecordingUpdateCallRecordingRequest$Outbound;
}

export function updateCallRecordingUpdateCallRecordingRequestToJSON(
  updateCallRecordingUpdateCallRecordingRequest:
    UpdateCallRecordingUpdateCallRecordingRequest,
): string {
  return JSON.stringify(
    UpdateCallRecordingUpdateCallRecordingRequest$outboundSchema.parse(
      updateCallRecordingUpdateCallRecordingRequest,
    ),
  );
}

export function updateCallRecordingUpdateCallRecordingRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateCallRecordingUpdateCallRecordingRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateCallRecordingUpdateCallRecordingRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateCallRecordingUpdateCallRecordingRequest' from JSON`,
  );
}

/** @internal */
export const UpdateCallRecordingRequest$inboundSchema: z.ZodType<
  UpdateCallRecordingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  CallSid: z.string(),
  Sid: z.string(),
  RequestBody: z.lazy(() =>
    UpdateCallRecordingUpdateCallRecordingRequest$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "CallSid": "callSid",
    "Sid": "sid",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateCallRecordingRequest$Outbound = {
  AccountSid: string;
  CallSid: string;
  Sid: string;
  RequestBody?:
    | UpdateCallRecordingUpdateCallRecordingRequest$Outbound
    | undefined;
};

/** @internal */
export const UpdateCallRecordingRequest$outboundSchema: z.ZodType<
  UpdateCallRecordingRequest$Outbound,
  z.ZodTypeDef,
  UpdateCallRecordingRequest
> = z.object({
  accountSid: z.string(),
  callSid: z.string(),
  sid: z.string(),
  requestBody: z.lazy(() =>
    UpdateCallRecordingUpdateCallRecordingRequest$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    callSid: "CallSid",
    sid: "Sid",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCallRecordingRequest$ {
  /** @deprecated use `UpdateCallRecordingRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateCallRecordingRequest$inboundSchema;
  /** @deprecated use `UpdateCallRecordingRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateCallRecordingRequest$outboundSchema;
  /** @deprecated use `UpdateCallRecordingRequest$Outbound` instead. */
  export type Outbound = UpdateCallRecordingRequest$Outbound;
}

export function updateCallRecordingRequestToJSON(
  updateCallRecordingRequest: UpdateCallRecordingRequest,
): string {
  return JSON.stringify(
    UpdateCallRecordingRequest$outboundSchema.parse(updateCallRecordingRequest),
  );
}

export function updateCallRecordingRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCallRecordingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCallRecordingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCallRecordingRequest' from JSON`,
  );
}

/** @internal */
export const UpdateCallRecordingResponse$inboundSchema: z.ZodType<
  UpdateCallRecordingResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountCallCallRecording$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type UpdateCallRecordingResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountCallCallRecording$Outbound;
};

/** @internal */
export const UpdateCallRecordingResponse$outboundSchema: z.ZodType<
  UpdateCallRecordingResponse$Outbound,
  z.ZodTypeDef,
  UpdateCallRecordingResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountCallCallRecording$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCallRecordingResponse$ {
  /** @deprecated use `UpdateCallRecordingResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateCallRecordingResponse$inboundSchema;
  /** @deprecated use `UpdateCallRecordingResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateCallRecordingResponse$outboundSchema;
  /** @deprecated use `UpdateCallRecordingResponse$Outbound` instead. */
  export type Outbound = UpdateCallRecordingResponse$Outbound;
}

export function updateCallRecordingResponseToJSON(
  updateCallRecordingResponse: UpdateCallRecordingResponse,
): string {
  return JSON.stringify(
    UpdateCallRecordingResponse$outboundSchema.parse(
      updateCallRecordingResponse,
    ),
  );
}

export function updateCallRecordingResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCallRecordingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCallRecordingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCallRecordingResponse' from JSON`,
  );
}
