/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const UpdateSipIpAddressServerList = [
  "https://api.twilio.com",
] as const;

export type UpdateSipIpAddressUpdateSipIpAddressRequest = {
  /**
   * An IP address in dotted decimal notation from which you want to accept traffic. Any SIP requests from this IP address will be allowed by Twilio. IPv4 only supported today.
   */
  ipAddress?: string | undefined;
  /**
   * A human readable descriptive text for this resource, up to 255 characters long.
   */
  friendlyName?: string | undefined;
  /**
   * An integer representing the length of the CIDR prefix to use with this IP address when accepting traffic. By default the entire IP address is used.
   */
  cidrPrefixLength?: number | undefined;
};

export type UpdateSipIpAddressRequest = {
  /**
   * The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
   */
  accountSid: string;
  /**
   * The IpAccessControlList Sid that identifies the IpAddress resources to update.
   */
  ipAccessControlListSid: string;
  /**
   * A 34 character string that identifies the IpAddress resource to update.
   */
  sid: string;
  requestBody?: UpdateSipIpAddressUpdateSipIpAddressRequest | undefined;
};

export type UpdateSipIpAddressResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountSipSipIpAccessControlListSipIpAddress;
};

/** @internal */
export const UpdateSipIpAddressUpdateSipIpAddressRequest$inboundSchema:
  z.ZodType<
    UpdateSipIpAddressUpdateSipIpAddressRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    IpAddress: z.string().optional(),
    FriendlyName: z.string().optional(),
    CidrPrefixLength: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      "IpAddress": "ipAddress",
      "FriendlyName": "friendlyName",
      "CidrPrefixLength": "cidrPrefixLength",
    });
  });

/** @internal */
export type UpdateSipIpAddressUpdateSipIpAddressRequest$Outbound = {
  IpAddress?: string | undefined;
  FriendlyName?: string | undefined;
  CidrPrefixLength?: number | undefined;
};

/** @internal */
export const UpdateSipIpAddressUpdateSipIpAddressRequest$outboundSchema:
  z.ZodType<
    UpdateSipIpAddressUpdateSipIpAddressRequest$Outbound,
    z.ZodTypeDef,
    UpdateSipIpAddressUpdateSipIpAddressRequest
  > = z.object({
    ipAddress: z.string().optional(),
    friendlyName: z.string().optional(),
    cidrPrefixLength: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      ipAddress: "IpAddress",
      friendlyName: "FriendlyName",
      cidrPrefixLength: "CidrPrefixLength",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateSipIpAddressUpdateSipIpAddressRequest$ {
  /** @deprecated use `UpdateSipIpAddressUpdateSipIpAddressRequest$inboundSchema` instead. */
  export const inboundSchema =
    UpdateSipIpAddressUpdateSipIpAddressRequest$inboundSchema;
  /** @deprecated use `UpdateSipIpAddressUpdateSipIpAddressRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateSipIpAddressUpdateSipIpAddressRequest$outboundSchema;
  /** @deprecated use `UpdateSipIpAddressUpdateSipIpAddressRequest$Outbound` instead. */
  export type Outbound = UpdateSipIpAddressUpdateSipIpAddressRequest$Outbound;
}

export function updateSipIpAddressUpdateSipIpAddressRequestToJSON(
  updateSipIpAddressUpdateSipIpAddressRequest:
    UpdateSipIpAddressUpdateSipIpAddressRequest,
): string {
  return JSON.stringify(
    UpdateSipIpAddressUpdateSipIpAddressRequest$outboundSchema.parse(
      updateSipIpAddressUpdateSipIpAddressRequest,
    ),
  );
}

export function updateSipIpAddressUpdateSipIpAddressRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateSipIpAddressUpdateSipIpAddressRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateSipIpAddressUpdateSipIpAddressRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateSipIpAddressUpdateSipIpAddressRequest' from JSON`,
  );
}

/** @internal */
export const UpdateSipIpAddressRequest$inboundSchema: z.ZodType<
  UpdateSipIpAddressRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  IpAccessControlListSid: z.string(),
  Sid: z.string(),
  RequestBody: z.lazy(() =>
    UpdateSipIpAddressUpdateSipIpAddressRequest$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "IpAccessControlListSid": "ipAccessControlListSid",
    "Sid": "sid",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateSipIpAddressRequest$Outbound = {
  AccountSid: string;
  IpAccessControlListSid: string;
  Sid: string;
  RequestBody?:
    | UpdateSipIpAddressUpdateSipIpAddressRequest$Outbound
    | undefined;
};

/** @internal */
export const UpdateSipIpAddressRequest$outboundSchema: z.ZodType<
  UpdateSipIpAddressRequest$Outbound,
  z.ZodTypeDef,
  UpdateSipIpAddressRequest
> = z.object({
  accountSid: z.string(),
  ipAccessControlListSid: z.string(),
  sid: z.string(),
  requestBody: z.lazy(() =>
    UpdateSipIpAddressUpdateSipIpAddressRequest$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    ipAccessControlListSid: "IpAccessControlListSid",
    sid: "Sid",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateSipIpAddressRequest$ {
  /** @deprecated use `UpdateSipIpAddressRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateSipIpAddressRequest$inboundSchema;
  /** @deprecated use `UpdateSipIpAddressRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateSipIpAddressRequest$outboundSchema;
  /** @deprecated use `UpdateSipIpAddressRequest$Outbound` instead. */
  export type Outbound = UpdateSipIpAddressRequest$Outbound;
}

export function updateSipIpAddressRequestToJSON(
  updateSipIpAddressRequest: UpdateSipIpAddressRequest,
): string {
  return JSON.stringify(
    UpdateSipIpAddressRequest$outboundSchema.parse(updateSipIpAddressRequest),
  );
}

export function updateSipIpAddressRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSipIpAddressRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSipIpAddressRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSipIpAddressRequest' from JSON`,
  );
}

/** @internal */
export const UpdateSipIpAddressResponse$inboundSchema: z.ZodType<
  UpdateSipIpAddressResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result:
    components
      .ApiV2010AccountSipSipIpAccessControlListSipIpAddress$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type UpdateSipIpAddressResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    components.ApiV2010AccountSipSipIpAccessControlListSipIpAddress$Outbound;
};

/** @internal */
export const UpdateSipIpAddressResponse$outboundSchema: z.ZodType<
  UpdateSipIpAddressResponse$Outbound,
  z.ZodTypeDef,
  UpdateSipIpAddressResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result:
    components
      .ApiV2010AccountSipSipIpAccessControlListSipIpAddress$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateSipIpAddressResponse$ {
  /** @deprecated use `UpdateSipIpAddressResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateSipIpAddressResponse$inboundSchema;
  /** @deprecated use `UpdateSipIpAddressResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateSipIpAddressResponse$outboundSchema;
  /** @deprecated use `UpdateSipIpAddressResponse$Outbound` instead. */
  export type Outbound = UpdateSipIpAddressResponse$Outbound;
}

export function updateSipIpAddressResponseToJSON(
  updateSipIpAddressResponse: UpdateSipIpAddressResponse,
): string {
  return JSON.stringify(
    UpdateSipIpAddressResponse$outboundSchema.parse(updateSipIpAddressResponse),
  );
}

export function updateSipIpAddressResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSipIpAddressResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSipIpAddressResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSipIpAddressResponse' from JSON`,
  );
}
