/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const UpdateUsageTriggerServerList = [
  "https://api.twilio.com",
] as const;

/**
 * The HTTP method we should use to call `callback_url`. Can be: `GET` or `POST` and the default is `POST`.
 */
export const CallbackMethod = {
  Get: "GET",
  Post: "POST",
} as const;
/**
 * The HTTP method we should use to call `callback_url`. Can be: `GET` or `POST` and the default is `POST`.
 */
export type CallbackMethod = ClosedEnum<typeof CallbackMethod>;

export type UpdateUsageTriggerUpdateUsageTriggerRequest = {
  /**
   * The HTTP method we should use to call `callback_url`. Can be: `GET` or `POST` and the default is `POST`.
   */
  callbackMethod?: CallbackMethod | undefined;
  /**
   * The URL we should call using `callback_method` when the trigger fires.
   */
  callbackUrl?: string | undefined;
  /**
   * A descriptive string that you create to describe the resource. It can be up to 64 characters long.
   */
  friendlyName?: string | undefined;
};

export type UpdateUsageTriggerRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the UsageTrigger resources to update.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the UsageTrigger resource to update.
   */
  sid: string;
  requestBody?: UpdateUsageTriggerUpdateUsageTriggerRequest | undefined;
};

export type UpdateUsageTriggerResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountUsageUsageTrigger;
};

/** @internal */
export const CallbackMethod$inboundSchema: z.ZodNativeEnum<
  typeof CallbackMethod
> = z.nativeEnum(CallbackMethod);

/** @internal */
export const CallbackMethod$outboundSchema: z.ZodNativeEnum<
  typeof CallbackMethod
> = CallbackMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CallbackMethod$ {
  /** @deprecated use `CallbackMethod$inboundSchema` instead. */
  export const inboundSchema = CallbackMethod$inboundSchema;
  /** @deprecated use `CallbackMethod$outboundSchema` instead. */
  export const outboundSchema = CallbackMethod$outboundSchema;
}

/** @internal */
export const UpdateUsageTriggerUpdateUsageTriggerRequest$inboundSchema:
  z.ZodType<
    UpdateUsageTriggerUpdateUsageTriggerRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    CallbackMethod: CallbackMethod$inboundSchema.optional(),
    CallbackUrl: z.string().optional(),
    FriendlyName: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "CallbackMethod": "callbackMethod",
      "CallbackUrl": "callbackUrl",
      "FriendlyName": "friendlyName",
    });
  });

/** @internal */
export type UpdateUsageTriggerUpdateUsageTriggerRequest$Outbound = {
  CallbackMethod?: string | undefined;
  CallbackUrl?: string | undefined;
  FriendlyName?: string | undefined;
};

/** @internal */
export const UpdateUsageTriggerUpdateUsageTriggerRequest$outboundSchema:
  z.ZodType<
    UpdateUsageTriggerUpdateUsageTriggerRequest$Outbound,
    z.ZodTypeDef,
    UpdateUsageTriggerUpdateUsageTriggerRequest
  > = z.object({
    callbackMethod: CallbackMethod$outboundSchema.optional(),
    callbackUrl: z.string().optional(),
    friendlyName: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      callbackMethod: "CallbackMethod",
      callbackUrl: "CallbackUrl",
      friendlyName: "FriendlyName",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUsageTriggerUpdateUsageTriggerRequest$ {
  /** @deprecated use `UpdateUsageTriggerUpdateUsageTriggerRequest$inboundSchema` instead. */
  export const inboundSchema =
    UpdateUsageTriggerUpdateUsageTriggerRequest$inboundSchema;
  /** @deprecated use `UpdateUsageTriggerUpdateUsageTriggerRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateUsageTriggerUpdateUsageTriggerRequest$outboundSchema;
  /** @deprecated use `UpdateUsageTriggerUpdateUsageTriggerRequest$Outbound` instead. */
  export type Outbound = UpdateUsageTriggerUpdateUsageTriggerRequest$Outbound;
}

export function updateUsageTriggerUpdateUsageTriggerRequestToJSON(
  updateUsageTriggerUpdateUsageTriggerRequest:
    UpdateUsageTriggerUpdateUsageTriggerRequest,
): string {
  return JSON.stringify(
    UpdateUsageTriggerUpdateUsageTriggerRequest$outboundSchema.parse(
      updateUsageTriggerUpdateUsageTriggerRequest,
    ),
  );
}

export function updateUsageTriggerUpdateUsageTriggerRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateUsageTriggerUpdateUsageTriggerRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateUsageTriggerUpdateUsageTriggerRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateUsageTriggerUpdateUsageTriggerRequest' from JSON`,
  );
}

/** @internal */
export const UpdateUsageTriggerRequest$inboundSchema: z.ZodType<
  UpdateUsageTriggerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
  RequestBody: z.lazy(() =>
    UpdateUsageTriggerUpdateUsageTriggerRequest$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateUsageTriggerRequest$Outbound = {
  AccountSid: string;
  Sid: string;
  RequestBody?:
    | UpdateUsageTriggerUpdateUsageTriggerRequest$Outbound
    | undefined;
};

/** @internal */
export const UpdateUsageTriggerRequest$outboundSchema: z.ZodType<
  UpdateUsageTriggerRequest$Outbound,
  z.ZodTypeDef,
  UpdateUsageTriggerRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
  requestBody: z.lazy(() =>
    UpdateUsageTriggerUpdateUsageTriggerRequest$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUsageTriggerRequest$ {
  /** @deprecated use `UpdateUsageTriggerRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateUsageTriggerRequest$inboundSchema;
  /** @deprecated use `UpdateUsageTriggerRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateUsageTriggerRequest$outboundSchema;
  /** @deprecated use `UpdateUsageTriggerRequest$Outbound` instead. */
  export type Outbound = UpdateUsageTriggerRequest$Outbound;
}

export function updateUsageTriggerRequestToJSON(
  updateUsageTriggerRequest: UpdateUsageTriggerRequest,
): string {
  return JSON.stringify(
    UpdateUsageTriggerRequest$outboundSchema.parse(updateUsageTriggerRequest),
  );
}

export function updateUsageTriggerRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateUsageTriggerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateUsageTriggerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateUsageTriggerRequest' from JSON`,
  );
}

/** @internal */
export const UpdateUsageTriggerResponse$inboundSchema: z.ZodType<
  UpdateUsageTriggerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountUsageUsageTrigger$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type UpdateUsageTriggerResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountUsageUsageTrigger$Outbound;
};

/** @internal */
export const UpdateUsageTriggerResponse$outboundSchema: z.ZodType<
  UpdateUsageTriggerResponse$Outbound,
  z.ZodTypeDef,
  UpdateUsageTriggerResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountUsageUsageTrigger$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUsageTriggerResponse$ {
  /** @deprecated use `UpdateUsageTriggerResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateUsageTriggerResponse$inboundSchema;
  /** @deprecated use `UpdateUsageTriggerResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateUsageTriggerResponse$outboundSchema;
  /** @deprecated use `UpdateUsageTriggerResponse$Outbound` instead. */
  export type Outbound = UpdateUsageTriggerResponse$Outbound;
}

export function updateUsageTriggerResponseToJSON(
  updateUsageTriggerResponse: UpdateUsageTriggerResponse,
): string {
  return JSON.stringify(
    UpdateUsageTriggerResponse$outboundSchema.parse(updateUsageTriggerResponse),
  );
}

export function updateUsageTriggerResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateUsageTriggerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateUsageTriggerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateUsageTriggerResponse' from JSON`,
  );
}
