/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const UpdateCallServerList = [
  "https://api.twilio.com",
] as const;

/**
 * The HTTP method we should use when calling the `url`. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
 */
export const UpdateCallMethod = {
  Get: "GET",
  Post: "POST",
} as const;
/**
 * The HTTP method we should use when calling the `url`. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
 */
export type UpdateCallMethod = ClosedEnum<typeof UpdateCallMethod>;

/**
 * The HTTP method that we should use to request the `fallback_url`. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
 */
export const UpdateCallFallbackMethod = {
  Get: "GET",
  Post: "POST",
} as const;
/**
 * The HTTP method that we should use to request the `fallback_url`. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
 */
export type UpdateCallFallbackMethod = ClosedEnum<
  typeof UpdateCallFallbackMethod
>;

/**
 * The HTTP method we should use when requesting the `status_callback` URL. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
 */
export const UpdateCallStatusCallbackMethod = {
  Get: "GET",
  Post: "POST",
} as const;
/**
 * The HTTP method we should use when requesting the `status_callback` URL. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
 */
export type UpdateCallStatusCallbackMethod = ClosedEnum<
  typeof UpdateCallStatusCallbackMethod
>;

export type UpdateCallUpdateCallRequest = {
  /**
   * The absolute URL that returns the TwiML instructions for the call. We will call this URL using the `method` when the call connects. For more information, see the [Url Parameter](https://www.twilio.com/docs/voice/make-calls#specify-a-url-parameter) section in [Making Calls](https://www.twilio.com/docs/voice/make-calls).
   */
  url?: string | undefined;
  /**
   * The HTTP method we should use when calling the `url`. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
   */
  method?: UpdateCallMethod | undefined;
  status?: components.CallEnumUpdateStatus | undefined;
  /**
   * The URL that we call using the `fallback_method` if an error occurs when requesting or executing the TwiML at `url`. If an `application_sid` parameter is present, this parameter is ignored.
   */
  fallbackUrl?: string | undefined;
  /**
   * The HTTP method that we should use to request the `fallback_url`. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
   */
  fallbackMethod?: UpdateCallFallbackMethod | undefined;
  /**
   * The URL we should call using the `status_callback_method` to send status information to your application. If no `status_callback_event` is specified, we will send the `completed` status. If an `application_sid` parameter is present, this parameter is ignored. URLs must contain a valid hostname (underscores are not permitted).
   */
  statusCallback?: string | undefined;
  /**
   * The HTTP method we should use when requesting the `status_callback` URL. Can be: `GET` or `POST` and the default is `POST`. If an `application_sid` parameter is present, this parameter is ignored.
   */
  statusCallbackMethod?: UpdateCallStatusCallbackMethod | undefined;
  /**
   * TwiML instructions for the call Twilio will use without fetching Twiml from url. Twiml and url parameters are mutually exclusive
   */
  twiml?: string | undefined;
  /**
   * The maximum duration of the call in seconds. Constraints depend on account and configuration.
   */
  timeLimit?: number | undefined;
};

export type UpdateCallRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Call resource(s) to update.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the Call resource to update
   */
  sid: string;
  requestBody?: UpdateCallUpdateCallRequest | undefined;
};

export type UpdateCallResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountCall;
};

/** @internal */
export const UpdateCallMethod$inboundSchema: z.ZodNativeEnum<
  typeof UpdateCallMethod
> = z.nativeEnum(UpdateCallMethod);

/** @internal */
export const UpdateCallMethod$outboundSchema: z.ZodNativeEnum<
  typeof UpdateCallMethod
> = UpdateCallMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCallMethod$ {
  /** @deprecated use `UpdateCallMethod$inboundSchema` instead. */
  export const inboundSchema = UpdateCallMethod$inboundSchema;
  /** @deprecated use `UpdateCallMethod$outboundSchema` instead. */
  export const outboundSchema = UpdateCallMethod$outboundSchema;
}

/** @internal */
export const UpdateCallFallbackMethod$inboundSchema: z.ZodNativeEnum<
  typeof UpdateCallFallbackMethod
> = z.nativeEnum(UpdateCallFallbackMethod);

/** @internal */
export const UpdateCallFallbackMethod$outboundSchema: z.ZodNativeEnum<
  typeof UpdateCallFallbackMethod
> = UpdateCallFallbackMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCallFallbackMethod$ {
  /** @deprecated use `UpdateCallFallbackMethod$inboundSchema` instead. */
  export const inboundSchema = UpdateCallFallbackMethod$inboundSchema;
  /** @deprecated use `UpdateCallFallbackMethod$outboundSchema` instead. */
  export const outboundSchema = UpdateCallFallbackMethod$outboundSchema;
}

/** @internal */
export const UpdateCallStatusCallbackMethod$inboundSchema: z.ZodNativeEnum<
  typeof UpdateCallStatusCallbackMethod
> = z.nativeEnum(UpdateCallStatusCallbackMethod);

/** @internal */
export const UpdateCallStatusCallbackMethod$outboundSchema: z.ZodNativeEnum<
  typeof UpdateCallStatusCallbackMethod
> = UpdateCallStatusCallbackMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCallStatusCallbackMethod$ {
  /** @deprecated use `UpdateCallStatusCallbackMethod$inboundSchema` instead. */
  export const inboundSchema = UpdateCallStatusCallbackMethod$inboundSchema;
  /** @deprecated use `UpdateCallStatusCallbackMethod$outboundSchema` instead. */
  export const outboundSchema = UpdateCallStatusCallbackMethod$outboundSchema;
}

/** @internal */
export const UpdateCallUpdateCallRequest$inboundSchema: z.ZodType<
  UpdateCallUpdateCallRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Url: z.string().optional(),
  Method: UpdateCallMethod$inboundSchema.optional(),
  Status: components.CallEnumUpdateStatus$inboundSchema.optional(),
  FallbackUrl: z.string().optional(),
  FallbackMethod: UpdateCallFallbackMethod$inboundSchema.optional(),
  StatusCallback: z.string().optional(),
  StatusCallbackMethod: UpdateCallStatusCallbackMethod$inboundSchema.optional(),
  Twiml: z.string().optional(),
  TimeLimit: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "Url": "url",
    "Method": "method",
    "Status": "status",
    "FallbackUrl": "fallbackUrl",
    "FallbackMethod": "fallbackMethod",
    "StatusCallback": "statusCallback",
    "StatusCallbackMethod": "statusCallbackMethod",
    "Twiml": "twiml",
    "TimeLimit": "timeLimit",
  });
});

/** @internal */
export type UpdateCallUpdateCallRequest$Outbound = {
  Url?: string | undefined;
  Method?: string | undefined;
  Status?: string | undefined;
  FallbackUrl?: string | undefined;
  FallbackMethod?: string | undefined;
  StatusCallback?: string | undefined;
  StatusCallbackMethod?: string | undefined;
  Twiml?: string | undefined;
  TimeLimit?: number | undefined;
};

/** @internal */
export const UpdateCallUpdateCallRequest$outboundSchema: z.ZodType<
  UpdateCallUpdateCallRequest$Outbound,
  z.ZodTypeDef,
  UpdateCallUpdateCallRequest
> = z.object({
  url: z.string().optional(),
  method: UpdateCallMethod$outboundSchema.optional(),
  status: components.CallEnumUpdateStatus$outboundSchema.optional(),
  fallbackUrl: z.string().optional(),
  fallbackMethod: UpdateCallFallbackMethod$outboundSchema.optional(),
  statusCallback: z.string().optional(),
  statusCallbackMethod: UpdateCallStatusCallbackMethod$outboundSchema
    .optional(),
  twiml: z.string().optional(),
  timeLimit: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    url: "Url",
    method: "Method",
    status: "Status",
    fallbackUrl: "FallbackUrl",
    fallbackMethod: "FallbackMethod",
    statusCallback: "StatusCallback",
    statusCallbackMethod: "StatusCallbackMethod",
    twiml: "Twiml",
    timeLimit: "TimeLimit",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCallUpdateCallRequest$ {
  /** @deprecated use `UpdateCallUpdateCallRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateCallUpdateCallRequest$inboundSchema;
  /** @deprecated use `UpdateCallUpdateCallRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateCallUpdateCallRequest$outboundSchema;
  /** @deprecated use `UpdateCallUpdateCallRequest$Outbound` instead. */
  export type Outbound = UpdateCallUpdateCallRequest$Outbound;
}

export function updateCallUpdateCallRequestToJSON(
  updateCallUpdateCallRequest: UpdateCallUpdateCallRequest,
): string {
  return JSON.stringify(
    UpdateCallUpdateCallRequest$outboundSchema.parse(
      updateCallUpdateCallRequest,
    ),
  );
}

export function updateCallUpdateCallRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCallUpdateCallRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCallUpdateCallRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCallUpdateCallRequest' from JSON`,
  );
}

/** @internal */
export const UpdateCallRequest$inboundSchema: z.ZodType<
  UpdateCallRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
  RequestBody: z.lazy(() => UpdateCallUpdateCallRequest$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateCallRequest$Outbound = {
  AccountSid: string;
  Sid: string;
  RequestBody?: UpdateCallUpdateCallRequest$Outbound | undefined;
};

/** @internal */
export const UpdateCallRequest$outboundSchema: z.ZodType<
  UpdateCallRequest$Outbound,
  z.ZodTypeDef,
  UpdateCallRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
  requestBody: z.lazy(() => UpdateCallUpdateCallRequest$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCallRequest$ {
  /** @deprecated use `UpdateCallRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateCallRequest$inboundSchema;
  /** @deprecated use `UpdateCallRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateCallRequest$outboundSchema;
  /** @deprecated use `UpdateCallRequest$Outbound` instead. */
  export type Outbound = UpdateCallRequest$Outbound;
}

export function updateCallRequestToJSON(
  updateCallRequest: UpdateCallRequest,
): string {
  return JSON.stringify(
    UpdateCallRequest$outboundSchema.parse(updateCallRequest),
  );
}

export function updateCallRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCallRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCallRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCallRequest' from JSON`,
  );
}

/** @internal */
export const UpdateCallResponse$inboundSchema: z.ZodType<
  UpdateCallResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountCall$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type UpdateCallResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountCall$Outbound;
};

/** @internal */
export const UpdateCallResponse$outboundSchema: z.ZodType<
  UpdateCallResponse$Outbound,
  z.ZodTypeDef,
  UpdateCallResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountCall$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCallResponse$ {
  /** @deprecated use `UpdateCallResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateCallResponse$inboundSchema;
  /** @deprecated use `UpdateCallResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateCallResponse$outboundSchema;
  /** @deprecated use `UpdateCallResponse$Outbound` instead. */
  export type Outbound = UpdateCallResponse$Outbound;
}

export function updateCallResponseToJSON(
  updateCallResponse: UpdateCallResponse,
): string {
  return JSON.stringify(
    UpdateCallResponse$outboundSchema.parse(updateCallResponse),
  );
}

export function updateCallResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCallResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCallResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCallResponse' from JSON`,
  );
}
