/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const UpdateOutgoingCallerIdServerList = [
  "https://api.twilio.com",
] as const;

export type UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest = {
  /**
   * A descriptive string that you create to describe the resource. It can be up to 64 characters long.
   */
  friendlyName?: string | undefined;
};

export type UpdateOutgoingCallerIdRequest = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the OutgoingCallerId resources to update.
   */
  accountSid: string;
  /**
   * The Twilio-provided string that uniquely identifies the OutgoingCallerId resource to update.
   */
  sid: string;
  requestBody?: UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest | undefined;
};

export type UpdateOutgoingCallerIdResponse = {
  headers: { [k: string]: Array<string> };
  result: components.ApiV2010AccountOutgoingCallerId;
};

/** @internal */
export const UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$inboundSchema:
  z.ZodType<
    UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    FriendlyName: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "FriendlyName": "friendlyName",
    });
  });

/** @internal */
export type UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$Outbound = {
  FriendlyName?: string | undefined;
};

/** @internal */
export const UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$outboundSchema:
  z.ZodType<
    UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$Outbound,
    z.ZodTypeDef,
    UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest
  > = z.object({
    friendlyName: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      friendlyName: "FriendlyName",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$ {
  /** @deprecated use `UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$inboundSchema;
  /** @deprecated use `UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$outboundSchema;
  /** @deprecated use `UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$Outbound` instead. */
  export type Outbound =
    UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$Outbound;
}

export function updateOutgoingCallerIdUpdateOutgoingCallerIdRequestToJSON(
  updateOutgoingCallerIdUpdateOutgoingCallerIdRequest:
    UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest,
): string {
  return JSON.stringify(
    UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$outboundSchema.parse(
      updateOutgoingCallerIdUpdateOutgoingCallerIdRequest,
    ),
  );
}

export function updateOutgoingCallerIdUpdateOutgoingCallerIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest' from JSON`,
  );
}

/** @internal */
export const UpdateOutgoingCallerIdRequest$inboundSchema: z.ZodType<
  UpdateOutgoingCallerIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  AccountSid: z.string(),
  Sid: z.string(),
  RequestBody: z.lazy(() =>
    UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "AccountSid": "accountSid",
    "Sid": "sid",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateOutgoingCallerIdRequest$Outbound = {
  AccountSid: string;
  Sid: string;
  RequestBody?:
    | UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$Outbound
    | undefined;
};

/** @internal */
export const UpdateOutgoingCallerIdRequest$outboundSchema: z.ZodType<
  UpdateOutgoingCallerIdRequest$Outbound,
  z.ZodTypeDef,
  UpdateOutgoingCallerIdRequest
> = z.object({
  accountSid: z.string(),
  sid: z.string(),
  requestBody: z.lazy(() =>
    UpdateOutgoingCallerIdUpdateOutgoingCallerIdRequest$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "AccountSid",
    sid: "Sid",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateOutgoingCallerIdRequest$ {
  /** @deprecated use `UpdateOutgoingCallerIdRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateOutgoingCallerIdRequest$inboundSchema;
  /** @deprecated use `UpdateOutgoingCallerIdRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateOutgoingCallerIdRequest$outboundSchema;
  /** @deprecated use `UpdateOutgoingCallerIdRequest$Outbound` instead. */
  export type Outbound = UpdateOutgoingCallerIdRequest$Outbound;
}

export function updateOutgoingCallerIdRequestToJSON(
  updateOutgoingCallerIdRequest: UpdateOutgoingCallerIdRequest,
): string {
  return JSON.stringify(
    UpdateOutgoingCallerIdRequest$outboundSchema.parse(
      updateOutgoingCallerIdRequest,
    ),
  );
}

export function updateOutgoingCallerIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateOutgoingCallerIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateOutgoingCallerIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateOutgoingCallerIdRequest' from JSON`,
  );
}

/** @internal */
export const UpdateOutgoingCallerIdResponse$inboundSchema: z.ZodType<
  UpdateOutgoingCallerIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: components.ApiV2010AccountOutgoingCallerId$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type UpdateOutgoingCallerIdResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.ApiV2010AccountOutgoingCallerId$Outbound;
};

/** @internal */
export const UpdateOutgoingCallerIdResponse$outboundSchema: z.ZodType<
  UpdateOutgoingCallerIdResponse$Outbound,
  z.ZodTypeDef,
  UpdateOutgoingCallerIdResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: components.ApiV2010AccountOutgoingCallerId$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateOutgoingCallerIdResponse$ {
  /** @deprecated use `UpdateOutgoingCallerIdResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateOutgoingCallerIdResponse$inboundSchema;
  /** @deprecated use `UpdateOutgoingCallerIdResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateOutgoingCallerIdResponse$outboundSchema;
  /** @deprecated use `UpdateOutgoingCallerIdResponse$Outbound` instead. */
  export type Outbound = UpdateOutgoingCallerIdResponse$Outbound;
}

export function updateOutgoingCallerIdResponseToJSON(
  updateOutgoingCallerIdResponse: UpdateOutgoingCallerIdResponse,
): string {
  return JSON.stringify(
    UpdateOutgoingCallerIdResponse$outboundSchema.parse(
      updateOutgoingCallerIdResponse,
    ),
  );
}

export function updateOutgoingCallerIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateOutgoingCallerIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateOutgoingCallerIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateOutgoingCallerIdResponse' from JSON`,
  );
}
