/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const AccountEnumStatus = {
  Active: "active",
  Suspended: "suspended",
  Closed: "closed",
} as const;
export type AccountEnumStatus = ClosedEnum<typeof AccountEnumStatus>;

/** @internal */
export const AccountEnumStatus$inboundSchema: z.ZodNativeEnum<
  typeof AccountEnumStatus
> = z.nativeEnum(AccountEnumStatus);

/** @internal */
export const AccountEnumStatus$outboundSchema: z.ZodNativeEnum<
  typeof AccountEnumStatus
> = AccountEnumStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountEnumStatus$ {
  /** @deprecated use `AccountEnumStatus$inboundSchema` instead. */
  export const inboundSchema = AccountEnumStatus$inboundSchema;
  /** @deprecated use `AccountEnumStatus$outboundSchema` instead. */
  export const outboundSchema = AccountEnumStatus$outboundSchema;
}
