/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IceServers = {
  credential?: string | undefined;
  username?: string | undefined;
  url?: string | undefined;
  urls?: string | undefined;
};

export type ApiV2010AccountToken = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Token resource.
   */
  accountSid?: string | null | undefined;
  /**
   * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateCreated?: string | null | undefined;
  /**
   * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateUpdated?: string | null | undefined;
  /**
   * An array representing the ephemeral credentials and the STUN and TURN server URIs.
   */
  iceServers?: Array<IceServers> | null | undefined;
  /**
   * The temporary password that the username will use when authenticating with Twilio.
   */
  password?: string | null | undefined;
  /**
   * The duration in seconds for which the username and password are valid.
   */
  ttl?: string | null | undefined;
  /**
   * The temporary username that uniquely identifies a Token.
   */
  username?: string | null | undefined;
};

/** @internal */
export const IceServers$inboundSchema: z.ZodType<
  IceServers,
  z.ZodTypeDef,
  unknown
> = z.object({
  credential: z.string().optional(),
  username: z.string().optional(),
  url: z.string().optional(),
  urls: z.string().optional(),
});

/** @internal */
export type IceServers$Outbound = {
  credential?: string | undefined;
  username?: string | undefined;
  url?: string | undefined;
  urls?: string | undefined;
};

/** @internal */
export const IceServers$outboundSchema: z.ZodType<
  IceServers$Outbound,
  z.ZodTypeDef,
  IceServers
> = z.object({
  credential: z.string().optional(),
  username: z.string().optional(),
  url: z.string().optional(),
  urls: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IceServers$ {
  /** @deprecated use `IceServers$inboundSchema` instead. */
  export const inboundSchema = IceServers$inboundSchema;
  /** @deprecated use `IceServers$outboundSchema` instead. */
  export const outboundSchema = IceServers$outboundSchema;
  /** @deprecated use `IceServers$Outbound` instead. */
  export type Outbound = IceServers$Outbound;
}

export function iceServersToJSON(iceServers: IceServers): string {
  return JSON.stringify(IceServers$outboundSchema.parse(iceServers));
}

export function iceServersFromJSON(
  jsonString: string,
): SafeParseResult<IceServers, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IceServers$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IceServers' from JSON`,
  );
}

/** @internal */
export const ApiV2010AccountToken$inboundSchema: z.ZodType<
  ApiV2010AccountToken,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_sid: z.nullable(z.string()).optional(),
  date_created: z.nullable(z.string()).optional(),
  date_updated: z.nullable(z.string()).optional(),
  ice_servers: z.nullable(z.array(z.lazy(() => IceServers$inboundSchema)))
    .optional(),
  password: z.nullable(z.string()).optional(),
  ttl: z.nullable(z.string()).optional(),
  username: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "account_sid": "accountSid",
    "date_created": "dateCreated",
    "date_updated": "dateUpdated",
    "ice_servers": "iceServers",
  });
});

/** @internal */
export type ApiV2010AccountToken$Outbound = {
  account_sid?: string | null | undefined;
  date_created?: string | null | undefined;
  date_updated?: string | null | undefined;
  ice_servers?: Array<IceServers$Outbound> | null | undefined;
  password?: string | null | undefined;
  ttl?: string | null | undefined;
  username?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountToken$outboundSchema: z.ZodType<
  ApiV2010AccountToken$Outbound,
  z.ZodTypeDef,
  ApiV2010AccountToken
> = z.object({
  accountSid: z.nullable(z.string()).optional(),
  dateCreated: z.nullable(z.string()).optional(),
  dateUpdated: z.nullable(z.string()).optional(),
  iceServers: z.nullable(z.array(z.lazy(() => IceServers$outboundSchema)))
    .optional(),
  password: z.nullable(z.string()).optional(),
  ttl: z.nullable(z.string()).optional(),
  username: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "account_sid",
    dateCreated: "date_created",
    dateUpdated: "date_updated",
    iceServers: "ice_servers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountToken$ {
  /** @deprecated use `ApiV2010AccountToken$inboundSchema` instead. */
  export const inboundSchema = ApiV2010AccountToken$inboundSchema;
  /** @deprecated use `ApiV2010AccountToken$outboundSchema` instead. */
  export const outboundSchema = ApiV2010AccountToken$outboundSchema;
  /** @deprecated use `ApiV2010AccountToken$Outbound` instead. */
  export type Outbound = ApiV2010AccountToken$Outbound;
}

export function apiV2010AccountTokenToJSON(
  apiV2010AccountToken: ApiV2010AccountToken,
): string {
  return JSON.stringify(
    ApiV2010AccountToken$outboundSchema.parse(apiV2010AccountToken),
  );
}

export function apiV2010AccountTokenFromJSON(
  jsonString: string,
): SafeParseResult<ApiV2010AccountToken, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiV2010AccountToken$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiV2010AccountToken' from JSON`,
  );
}
