/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  UsageRecordLastMonthEnumCategory,
  UsageRecordLastMonthEnumCategory$inboundSchema,
  UsageRecordLastMonthEnumCategory$outboundSchema,
} from "./usagerecordlastmonthenumcategory.js";

/**
 * A list of related resources identified by their URIs. For more information, see [List Subresources](https://www.twilio.com/docs/usage/api/usage-record#list-subresources).
 */
export type ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris =
  {};

export type ApiV2010AccountUsageUsageRecordUsageRecordLastMonth = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that accrued the usage.
   */
  accountSid?: string | null | undefined;
  /**
   * The API version used to create the resource.
   */
  apiVersion?: string | null | undefined;
  /**
   * Usage records up to date as of this timestamp, formatted as YYYY-MM-DDTHH:MM:SS+00:00. All timestamps are in GMT
   */
  asOf?: string | null | undefined;
  category?: UsageRecordLastMonthEnumCategory | undefined;
  /**
   * The number of usage events, such as the number of calls.
   */
  count?: string | null | undefined;
  /**
   * The units in which `count` is measured, such as `calls` for calls or `messages` for SMS.
   */
  countUnit?: string | null | undefined;
  /**
   * A plain-language description of the usage category.
   */
  description?: string | null | undefined;
  /**
   * The last date for which usage is included in the UsageRecord. The date is specified in GMT and formatted as `YYYY-MM-DD`.
   */
  endDate?: RFCDate | null | undefined;
  /**
   * The total price of the usage in the currency specified in `price_unit` and associated with the account.
   */
  price?: number | null | undefined;
  /**
   * The currency in which `price` is measured, in [ISO 4127](https://www.iso.org/iso/home/standards/currency_codes.htm) format, such as `usd`, `eur`, and `jpy`.
   */
  priceUnit?: string | null | undefined;
  /**
   * The first date for which usage is included in this UsageRecord. The date is specified in GMT and formatted as `YYYY-MM-DD`.
   */
  startDate?: RFCDate | null | undefined;
  /**
   * A list of related resources identified by their URIs. For more information, see [List Subresources](https://www.twilio.com/docs/usage/api/usage-record#list-subresources).
   */
  subresourceUris?:
    | ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris
    | null
    | undefined;
  /**
   * The URI of the resource, relative to `https://api.twilio.com`.
   */
  uri?: string | null | undefined;
  /**
   * The amount used to bill usage and measured in units described in `usage_unit`.
   */
  usage?: string | null | undefined;
  /**
   * The units in which `usage` is measured, such as `minutes` for calls or `messages` for SMS.
   */
  usageUnit?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$inboundSchema:
  z.ZodType<
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$Outbound =
  {};

/** @internal */
export const ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$outboundSchema:
  z.ZodType<
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$Outbound,
    z.ZodTypeDef,
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$ {
  /** @deprecated use `ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$inboundSchema` instead. */
  export const inboundSchema =
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$inboundSchema;
  /** @deprecated use `ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$outboundSchema` instead. */
  export const outboundSchema =
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$outboundSchema;
  /** @deprecated use `ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$Outbound` instead. */
  export type Outbound =
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$Outbound;
}

export function apiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUrisToJSON(
  apiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris:
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris,
): string {
  return JSON.stringify(
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$outboundSchema
      .parse(
        apiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris,
      ),
  );
}

export function apiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUrisFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris' from JSON`,
  );
}

/** @internal */
export const ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$inboundSchema:
  z.ZodType<
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonth,
    z.ZodTypeDef,
    unknown
  > = z.object({
    account_sid: z.nullable(z.string()).optional(),
    api_version: z.nullable(z.string()).optional(),
    as_of: z.nullable(z.string()).optional(),
    category: UsageRecordLastMonthEnumCategory$inboundSchema.optional(),
    count: z.nullable(z.string()).optional(),
    count_unit: z.nullable(z.string()).optional(),
    description: z.nullable(z.string()).optional(),
    end_date: z.nullable(z.string().transform(v => new RFCDate(v))).optional(),
    price: z.nullable(z.number()).optional(),
    price_unit: z.nullable(z.string()).optional(),
    start_date: z.nullable(z.string().transform(v => new RFCDate(v)))
      .optional(),
    subresource_uris: z.nullable(
      z.lazy(() =>
        ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$inboundSchema
      ),
    ).optional(),
    uri: z.nullable(z.string()).optional(),
    usage: z.nullable(z.string()).optional(),
    usage_unit: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "account_sid": "accountSid",
      "api_version": "apiVersion",
      "as_of": "asOf",
      "count_unit": "countUnit",
      "end_date": "endDate",
      "price_unit": "priceUnit",
      "start_date": "startDate",
      "subresource_uris": "subresourceUris",
      "usage_unit": "usageUnit",
    });
  });

/** @internal */
export type ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$Outbound = {
  account_sid?: string | null | undefined;
  api_version?: string | null | undefined;
  as_of?: string | null | undefined;
  category?: string | undefined;
  count?: string | null | undefined;
  count_unit?: string | null | undefined;
  description?: string | null | undefined;
  end_date?: string | null | undefined;
  price?: number | null | undefined;
  price_unit?: string | null | undefined;
  start_date?: string | null | undefined;
  subresource_uris?:
    | ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$Outbound
    | null
    | undefined;
  uri?: string | null | undefined;
  usage?: string | null | undefined;
  usage_unit?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$outboundSchema:
  z.ZodType<
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$Outbound,
    z.ZodTypeDef,
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonth
  > = z.object({
    accountSid: z.nullable(z.string()).optional(),
    apiVersion: z.nullable(z.string()).optional(),
    asOf: z.nullable(z.string()).optional(),
    category: UsageRecordLastMonthEnumCategory$outboundSchema.optional(),
    count: z.nullable(z.string()).optional(),
    countUnit: z.nullable(z.string()).optional(),
    description: z.nullable(z.string()).optional(),
    endDate: z.nullable(z.instanceof(RFCDate).transform(v => v.toString()))
      .optional(),
    price: z.nullable(z.number()).optional(),
    priceUnit: z.nullable(z.string()).optional(),
    startDate: z.nullable(z.instanceof(RFCDate).transform(v => v.toString()))
      .optional(),
    subresourceUris: z.nullable(
      z.lazy(() =>
        ApiV2010AccountUsageUsageRecordUsageRecordLastMonthSubresourceUris$outboundSchema
      ),
    ).optional(),
    uri: z.nullable(z.string()).optional(),
    usage: z.nullable(z.string()).optional(),
    usageUnit: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      accountSid: "account_sid",
      apiVersion: "api_version",
      asOf: "as_of",
      countUnit: "count_unit",
      endDate: "end_date",
      priceUnit: "price_unit",
      startDate: "start_date",
      subresourceUris: "subresource_uris",
      usageUnit: "usage_unit",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$ {
  /** @deprecated use `ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$inboundSchema` instead. */
  export const inboundSchema =
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$inboundSchema;
  /** @deprecated use `ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$outboundSchema` instead. */
  export const outboundSchema =
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$outboundSchema;
  /** @deprecated use `ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$Outbound` instead. */
  export type Outbound =
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$Outbound;
}

export function apiV2010AccountUsageUsageRecordUsageRecordLastMonthToJSON(
  apiV2010AccountUsageUsageRecordUsageRecordLastMonth:
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonth,
): string {
  return JSON.stringify(
    ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$outboundSchema.parse(
      apiV2010AccountUsageUsageRecordUsageRecordLastMonth,
    ),
  );
}

export function apiV2010AccountUsageUsageRecordUsageRecordLastMonthFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiV2010AccountUsageUsageRecordUsageRecordLastMonth,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiV2010AccountUsageUsageRecordUsageRecordLastMonth$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiV2010AccountUsageUsageRecordUsageRecordLastMonth' from JSON`,
  );
}
