/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApiV2010AccountSipSipDomainSipCredentialListMapping = {
  /**
   * The unique id of the Account that is responsible for this resource.
   */
  accountSid?: string | null | undefined;
  /**
   * The date that this resource was created, given as GMT in [RFC 2822](https://www.php.net/manual/en/class.datetime.php#datetime.constants.rfc2822) format.
   */
  dateCreated?: string | null | undefined;
  /**
   * The date that this resource was last updated, given as GMT in [RFC 2822](https://www.php.net/manual/en/class.datetime.php#datetime.constants.rfc2822) format.
   */
  dateUpdated?: string | null | undefined;
  /**
   * The unique string that is created to identify the SipDomain resource.
   */
  domainSid?: string | null | undefined;
  /**
   * A human readable descriptive text for this resource, up to 64 characters long.
   */
  friendlyName?: string | null | undefined;
  /**
   * A 34 character string that uniquely identifies this resource.
   */
  sid?: string | null | undefined;
  /**
   * The URI for this resource, relative to `https://api.twilio.com`
   */
  uri?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountSipSipDomainSipCredentialListMapping$inboundSchema:
  z.ZodType<
    ApiV2010AccountSipSipDomainSipCredentialListMapping,
    z.ZodTypeDef,
    unknown
  > = z.object({
    account_sid: z.nullable(z.string()).optional(),
    date_created: z.nullable(z.string()).optional(),
    date_updated: z.nullable(z.string()).optional(),
    domain_sid: z.nullable(z.string()).optional(),
    friendly_name: z.nullable(z.string()).optional(),
    sid: z.nullable(z.string()).optional(),
    uri: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "account_sid": "accountSid",
      "date_created": "dateCreated",
      "date_updated": "dateUpdated",
      "domain_sid": "domainSid",
      "friendly_name": "friendlyName",
    });
  });

/** @internal */
export type ApiV2010AccountSipSipDomainSipCredentialListMapping$Outbound = {
  account_sid?: string | null | undefined;
  date_created?: string | null | undefined;
  date_updated?: string | null | undefined;
  domain_sid?: string | null | undefined;
  friendly_name?: string | null | undefined;
  sid?: string | null | undefined;
  uri?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountSipSipDomainSipCredentialListMapping$outboundSchema:
  z.ZodType<
    ApiV2010AccountSipSipDomainSipCredentialListMapping$Outbound,
    z.ZodTypeDef,
    ApiV2010AccountSipSipDomainSipCredentialListMapping
  > = z.object({
    accountSid: z.nullable(z.string()).optional(),
    dateCreated: z.nullable(z.string()).optional(),
    dateUpdated: z.nullable(z.string()).optional(),
    domainSid: z.nullable(z.string()).optional(),
    friendlyName: z.nullable(z.string()).optional(),
    sid: z.nullable(z.string()).optional(),
    uri: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      accountSid: "account_sid",
      dateCreated: "date_created",
      dateUpdated: "date_updated",
      domainSid: "domain_sid",
      friendlyName: "friendly_name",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountSipSipDomainSipCredentialListMapping$ {
  /** @deprecated use `ApiV2010AccountSipSipDomainSipCredentialListMapping$inboundSchema` instead. */
  export const inboundSchema =
    ApiV2010AccountSipSipDomainSipCredentialListMapping$inboundSchema;
  /** @deprecated use `ApiV2010AccountSipSipDomainSipCredentialListMapping$outboundSchema` instead. */
  export const outboundSchema =
    ApiV2010AccountSipSipDomainSipCredentialListMapping$outboundSchema;
  /** @deprecated use `ApiV2010AccountSipSipDomainSipCredentialListMapping$Outbound` instead. */
  export type Outbound =
    ApiV2010AccountSipSipDomainSipCredentialListMapping$Outbound;
}

export function apiV2010AccountSipSipDomainSipCredentialListMappingToJSON(
  apiV2010AccountSipSipDomainSipCredentialListMapping:
    ApiV2010AccountSipSipDomainSipCredentialListMapping,
): string {
  return JSON.stringify(
    ApiV2010AccountSipSipDomainSipCredentialListMapping$outboundSchema.parse(
      apiV2010AccountSipSipDomainSipCredentialListMapping,
    ),
  );
}

export function apiV2010AccountSipSipDomainSipCredentialListMappingFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiV2010AccountSipSipDomainSipCredentialListMapping,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiV2010AccountSipSipDomainSipCredentialListMapping$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiV2010AccountSipSipDomainSipCredentialListMapping' from JSON`,
  );
}
