/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MessageFeedbackEnumOutcome,
  MessageFeedbackEnumOutcome$inboundSchema,
  MessageFeedbackEnumOutcome$outboundSchema,
} from "./messagefeedbackenumoutcome.js";

export type ApiV2010AccountMessageMessageFeedback = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) associated with this MessageFeedback resource.
   */
  accountSid?: string | null | undefined;
  /**
   * The SID of the Message resource associated with this MessageFeedback resource.
   */
  messageSid?: string | null | undefined;
  outcome?: MessageFeedbackEnumOutcome | undefined;
  /**
   * The date and time in GMT when this MessageFeedback resource was created, specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateCreated?: string | null | undefined;
  /**
   * The date and time in GMT when this MessageFeedback resource was last updated, specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateUpdated?: string | null | undefined;
  /**
   * The URI of the resource, relative to `https://api.twilio.com`.
   */
  uri?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountMessageMessageFeedback$inboundSchema: z.ZodType<
  ApiV2010AccountMessageMessageFeedback,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_sid: z.nullable(z.string()).optional(),
  message_sid: z.nullable(z.string()).optional(),
  outcome: MessageFeedbackEnumOutcome$inboundSchema.optional(),
  date_created: z.nullable(z.string()).optional(),
  date_updated: z.nullable(z.string()).optional(),
  uri: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "account_sid": "accountSid",
    "message_sid": "messageSid",
    "date_created": "dateCreated",
    "date_updated": "dateUpdated",
  });
});

/** @internal */
export type ApiV2010AccountMessageMessageFeedback$Outbound = {
  account_sid?: string | null | undefined;
  message_sid?: string | null | undefined;
  outcome?: string | undefined;
  date_created?: string | null | undefined;
  date_updated?: string | null | undefined;
  uri?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountMessageMessageFeedback$outboundSchema: z.ZodType<
  ApiV2010AccountMessageMessageFeedback$Outbound,
  z.ZodTypeDef,
  ApiV2010AccountMessageMessageFeedback
> = z.object({
  accountSid: z.nullable(z.string()).optional(),
  messageSid: z.nullable(z.string()).optional(),
  outcome: MessageFeedbackEnumOutcome$outboundSchema.optional(),
  dateCreated: z.nullable(z.string()).optional(),
  dateUpdated: z.nullable(z.string()).optional(),
  uri: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "account_sid",
    messageSid: "message_sid",
    dateCreated: "date_created",
    dateUpdated: "date_updated",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountMessageMessageFeedback$ {
  /** @deprecated use `ApiV2010AccountMessageMessageFeedback$inboundSchema` instead. */
  export const inboundSchema =
    ApiV2010AccountMessageMessageFeedback$inboundSchema;
  /** @deprecated use `ApiV2010AccountMessageMessageFeedback$outboundSchema` instead. */
  export const outboundSchema =
    ApiV2010AccountMessageMessageFeedback$outboundSchema;
  /** @deprecated use `ApiV2010AccountMessageMessageFeedback$Outbound` instead. */
  export type Outbound = ApiV2010AccountMessageMessageFeedback$Outbound;
}

export function apiV2010AccountMessageMessageFeedbackToJSON(
  apiV2010AccountMessageMessageFeedback: ApiV2010AccountMessageMessageFeedback,
): string {
  return JSON.stringify(
    ApiV2010AccountMessageMessageFeedback$outboundSchema.parse(
      apiV2010AccountMessageMessageFeedback,
    ),
  );
}

export function apiV2010AccountMessageMessageFeedbackFromJSON(
  jsonString: string,
): SafeParseResult<ApiV2010AccountMessageMessageFeedback, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApiV2010AccountMessageMessageFeedback$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiV2010AccountMessageMessageFeedback' from JSON`,
  );
}
