/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApiV2010AccountBalance = {
  /**
   * The unique SID identifier of the Account.
   */
  accountSid?: string | null | undefined;
  /**
   * The balance of the Account, in units specified by the unit parameter. Balance changes may not be reflected immediately. Child accounts do not contain balance information
   */
  balance?: string | null | undefined;
  /**
   * The units of currency for the account balance
   */
  currency?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountBalance$inboundSchema: z.ZodType<
  ApiV2010AccountBalance,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_sid: z.nullable(z.string()).optional(),
  balance: z.nullable(z.string()).optional(),
  currency: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "account_sid": "accountSid",
  });
});

/** @internal */
export type ApiV2010AccountBalance$Outbound = {
  account_sid?: string | null | undefined;
  balance?: string | null | undefined;
  currency?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountBalance$outboundSchema: z.ZodType<
  ApiV2010AccountBalance$Outbound,
  z.ZodTypeDef,
  ApiV2010AccountBalance
> = z.object({
  accountSid: z.nullable(z.string()).optional(),
  balance: z.nullable(z.string()).optional(),
  currency: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "account_sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountBalance$ {
  /** @deprecated use `ApiV2010AccountBalance$inboundSchema` instead. */
  export const inboundSchema = ApiV2010AccountBalance$inboundSchema;
  /** @deprecated use `ApiV2010AccountBalance$outboundSchema` instead. */
  export const outboundSchema = ApiV2010AccountBalance$outboundSchema;
  /** @deprecated use `ApiV2010AccountBalance$Outbound` instead. */
  export type Outbound = ApiV2010AccountBalance$Outbound;
}

export function apiV2010AccountBalanceToJSON(
  apiV2010AccountBalance: ApiV2010AccountBalance,
): string {
  return JSON.stringify(
    ApiV2010AccountBalance$outboundSchema.parse(apiV2010AccountBalance),
  );
}

export function apiV2010AccountBalanceFromJSON(
  jsonString: string,
): SafeParseResult<ApiV2010AccountBalance, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiV2010AccountBalance$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiV2010AccountBalance' from JSON`,
  );
}
