/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ConferenceEnumReasonConferenceEnded,
  ConferenceEnumReasonConferenceEnded$inboundSchema,
  ConferenceEnumReasonConferenceEnded$outboundSchema,
} from "./conferenceenumreasonconferenceended.js";
import {
  ConferenceEnumStatus,
  ConferenceEnumStatus$inboundSchema,
  ConferenceEnumStatus$outboundSchema,
} from "./conferenceenumstatus.js";

/**
 * A list of related resources identified by their URIs relative to `https://api.twilio.com`.
 */
export type ApiV2010AccountConferenceSubresourceUris = {};

export type ApiV2010AccountConference = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created this Conference resource.
   */
  accountSid?: string | null | undefined;
  /**
   * The date and time in UTC that this resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateCreated?: string | null | undefined;
  /**
   * The date and time in UTC that this resource was last updated, specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateUpdated?: string | null | undefined;
  /**
   * The API version used to create this conference.
   */
  apiVersion?: string | null | undefined;
  /**
   * A string that you assigned to describe this conference room. Maximum length is 128 characters.
   */
  friendlyName?: string | null | undefined;
  /**
   * A string that represents the Twilio Region where the conference audio was mixed. May be `us1`, `ie1`,  `de1`, `sg1`, `br1`, `au1`, and `jp1`. Basic conference audio will always be mixed in `us1`. Global Conference audio will be mixed nearest to the majority of participants.
   */
  region?: string | null | undefined;
  /**
   * The unique, Twilio-provided string used to identify this Conference resource.
   */
  sid?: string | null | undefined;
  status?: ConferenceEnumStatus | undefined;
  /**
   * The URI of this resource, relative to `https://api.twilio.com`.
   */
  uri?: string | null | undefined;
  /**
   * A list of related resources identified by their URIs relative to `https://api.twilio.com`.
   */
  subresourceUris?: ApiV2010AccountConferenceSubresourceUris | null | undefined;
  reasonConferenceEnded?: ConferenceEnumReasonConferenceEnded | undefined;
  /**
   * The call SID that caused the conference to end.
   */
  callSidEndingConference?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountConferenceSubresourceUris$inboundSchema: z.ZodType<
  ApiV2010AccountConferenceSubresourceUris,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type ApiV2010AccountConferenceSubresourceUris$Outbound = {};

/** @internal */
export const ApiV2010AccountConferenceSubresourceUris$outboundSchema: z.ZodType<
  ApiV2010AccountConferenceSubresourceUris$Outbound,
  z.ZodTypeDef,
  ApiV2010AccountConferenceSubresourceUris
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountConferenceSubresourceUris$ {
  /** @deprecated use `ApiV2010AccountConferenceSubresourceUris$inboundSchema` instead. */
  export const inboundSchema =
    ApiV2010AccountConferenceSubresourceUris$inboundSchema;
  /** @deprecated use `ApiV2010AccountConferenceSubresourceUris$outboundSchema` instead. */
  export const outboundSchema =
    ApiV2010AccountConferenceSubresourceUris$outboundSchema;
  /** @deprecated use `ApiV2010AccountConferenceSubresourceUris$Outbound` instead. */
  export type Outbound = ApiV2010AccountConferenceSubresourceUris$Outbound;
}

export function apiV2010AccountConferenceSubresourceUrisToJSON(
  apiV2010AccountConferenceSubresourceUris:
    ApiV2010AccountConferenceSubresourceUris,
): string {
  return JSON.stringify(
    ApiV2010AccountConferenceSubresourceUris$outboundSchema.parse(
      apiV2010AccountConferenceSubresourceUris,
    ),
  );
}

export function apiV2010AccountConferenceSubresourceUrisFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiV2010AccountConferenceSubresourceUris,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiV2010AccountConferenceSubresourceUris$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiV2010AccountConferenceSubresourceUris' from JSON`,
  );
}

/** @internal */
export const ApiV2010AccountConference$inboundSchema: z.ZodType<
  ApiV2010AccountConference,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_sid: z.nullable(z.string()).optional(),
  date_created: z.nullable(z.string()).optional(),
  date_updated: z.nullable(z.string()).optional(),
  api_version: z.nullable(z.string()).optional(),
  friendly_name: z.nullable(z.string()).optional(),
  region: z.nullable(z.string()).optional(),
  sid: z.nullable(z.string()).optional(),
  status: ConferenceEnumStatus$inboundSchema.optional(),
  uri: z.nullable(z.string()).optional(),
  subresource_uris: z.nullable(
    z.lazy(() => ApiV2010AccountConferenceSubresourceUris$inboundSchema),
  ).optional(),
  reason_conference_ended: ConferenceEnumReasonConferenceEnded$inboundSchema
    .optional(),
  call_sid_ending_conference: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "account_sid": "accountSid",
    "date_created": "dateCreated",
    "date_updated": "dateUpdated",
    "api_version": "apiVersion",
    "friendly_name": "friendlyName",
    "subresource_uris": "subresourceUris",
    "reason_conference_ended": "reasonConferenceEnded",
    "call_sid_ending_conference": "callSidEndingConference",
  });
});

/** @internal */
export type ApiV2010AccountConference$Outbound = {
  account_sid?: string | null | undefined;
  date_created?: string | null | undefined;
  date_updated?: string | null | undefined;
  api_version?: string | null | undefined;
  friendly_name?: string | null | undefined;
  region?: string | null | undefined;
  sid?: string | null | undefined;
  status?: string | undefined;
  uri?: string | null | undefined;
  subresource_uris?:
    | ApiV2010AccountConferenceSubresourceUris$Outbound
    | null
    | undefined;
  reason_conference_ended?: string | undefined;
  call_sid_ending_conference?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountConference$outboundSchema: z.ZodType<
  ApiV2010AccountConference$Outbound,
  z.ZodTypeDef,
  ApiV2010AccountConference
> = z.object({
  accountSid: z.nullable(z.string()).optional(),
  dateCreated: z.nullable(z.string()).optional(),
  dateUpdated: z.nullable(z.string()).optional(),
  apiVersion: z.nullable(z.string()).optional(),
  friendlyName: z.nullable(z.string()).optional(),
  region: z.nullable(z.string()).optional(),
  sid: z.nullable(z.string()).optional(),
  status: ConferenceEnumStatus$outboundSchema.optional(),
  uri: z.nullable(z.string()).optional(),
  subresourceUris: z.nullable(
    z.lazy(() => ApiV2010AccountConferenceSubresourceUris$outboundSchema),
  ).optional(),
  reasonConferenceEnded: ConferenceEnumReasonConferenceEnded$outboundSchema
    .optional(),
  callSidEndingConference: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "account_sid",
    dateCreated: "date_created",
    dateUpdated: "date_updated",
    apiVersion: "api_version",
    friendlyName: "friendly_name",
    subresourceUris: "subresource_uris",
    reasonConferenceEnded: "reason_conference_ended",
    callSidEndingConference: "call_sid_ending_conference",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountConference$ {
  /** @deprecated use `ApiV2010AccountConference$inboundSchema` instead. */
  export const inboundSchema = ApiV2010AccountConference$inboundSchema;
  /** @deprecated use `ApiV2010AccountConference$outboundSchema` instead. */
  export const outboundSchema = ApiV2010AccountConference$outboundSchema;
  /** @deprecated use `ApiV2010AccountConference$Outbound` instead. */
  export type Outbound = ApiV2010AccountConference$Outbound;
}

export function apiV2010AccountConferenceToJSON(
  apiV2010AccountConference: ApiV2010AccountConference,
): string {
  return JSON.stringify(
    ApiV2010AccountConference$outboundSchema.parse(apiV2010AccountConference),
  );
}

export function apiV2010AccountConferenceFromJSON(
  jsonString: string,
): SafeParseResult<ApiV2010AccountConference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiV2010AccountConference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiV2010AccountConference' from JSON`,
  );
}
