/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The HTTP method used to generate the notification. If the notification was generated during a phone call, this is the HTTP Method used to request the resource on your server. If the notification was generated by your use of our REST API, this is the HTTP method used to call the resource on our servers.
 */
export const ApiV2010AccountNotificationRequestMethod = {
  Get: "GET",
  Post: "POST",
} as const;
/**
 * The HTTP method used to generate the notification. If the notification was generated during a phone call, this is the HTTP Method used to request the resource on your server. If the notification was generated by your use of our REST API, this is the HTTP method used to call the resource on our servers.
 */
export type ApiV2010AccountNotificationRequestMethod = ClosedEnum<
  typeof ApiV2010AccountNotificationRequestMethod
>;

export type ApiV2010AccountNotification = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Notification resource.
   */
  accountSid?: string | null | undefined;
  /**
   * The API version used to generate the notification. Can be empty for events that don't have a specific API version, such as incoming phone calls.
   */
  apiVersion?: string | null | undefined;
  /**
   * The SID of the [Call](https://www.twilio.com/docs/voice/api/call-resource) the Notification resource is associated with.
   */
  callSid?: string | null | undefined;
  /**
   * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateCreated?: string | null | undefined;
  /**
   * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateUpdated?: string | null | undefined;
  /**
   * A unique error code for the error condition that is described in our [Error Dictionary](https://www.twilio.com/docs/api/errors).
   */
  errorCode?: string | null | undefined;
  /**
   * An integer log level that corresponds to the type of notification: `0` is ERROR, `1` is WARNING.
   */
  log?: string | null | undefined;
  /**
   * The date the notification was actually generated in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format. Message buffering can cause this value to differ from `date_created`.
   */
  messageDate?: string | null | undefined;
  /**
   * The text of the notification.
   */
  messageText?: string | null | undefined;
  /**
   * The URL for more information about the error condition. This value is a page in our [Error Dictionary](https://www.twilio.com/docs/api/errors).
   */
  moreInfo?: string | null | undefined;
  /**
   * The HTTP method used to generate the notification. If the notification was generated during a phone call, this is the HTTP Method used to request the resource on your server. If the notification was generated by your use of our REST API, this is the HTTP method used to call the resource on our servers.
   */
  requestMethod?: ApiV2010AccountNotificationRequestMethod | null | undefined;
  /**
   * The URL of the resource that generated the notification. If the notification was generated during a phone call, this is the URL of the resource on your server that caused the notification. If the notification was generated by your use of our REST API, this is the URL of the resource you called.
   */
  requestUrl?: string | null | undefined;
  /**
   * The unique string that that we created to identify the Notification resource.
   */
  sid?: string | null | undefined;
  /**
   * The URI of the resource, relative to `https://api.twilio.com`.
   */
  uri?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountNotificationRequestMethod$inboundSchema:
  z.ZodNativeEnum<typeof ApiV2010AccountNotificationRequestMethod> = z
    .nativeEnum(ApiV2010AccountNotificationRequestMethod);

/** @internal */
export const ApiV2010AccountNotificationRequestMethod$outboundSchema:
  z.ZodNativeEnum<typeof ApiV2010AccountNotificationRequestMethod> =
    ApiV2010AccountNotificationRequestMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountNotificationRequestMethod$ {
  /** @deprecated use `ApiV2010AccountNotificationRequestMethod$inboundSchema` instead. */
  export const inboundSchema =
    ApiV2010AccountNotificationRequestMethod$inboundSchema;
  /** @deprecated use `ApiV2010AccountNotificationRequestMethod$outboundSchema` instead. */
  export const outboundSchema =
    ApiV2010AccountNotificationRequestMethod$outboundSchema;
}

/** @internal */
export const ApiV2010AccountNotification$inboundSchema: z.ZodType<
  ApiV2010AccountNotification,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_sid: z.nullable(z.string()).optional(),
  api_version: z.nullable(z.string()).optional(),
  call_sid: z.nullable(z.string()).optional(),
  date_created: z.nullable(z.string()).optional(),
  date_updated: z.nullable(z.string()).optional(),
  error_code: z.nullable(z.string()).optional(),
  log: z.nullable(z.string()).optional(),
  message_date: z.nullable(z.string()).optional(),
  message_text: z.nullable(z.string()).optional(),
  more_info: z.nullable(z.string()).optional(),
  request_method: z.nullable(
    ApiV2010AccountNotificationRequestMethod$inboundSchema,
  ).optional(),
  request_url: z.nullable(z.string()).optional(),
  sid: z.nullable(z.string()).optional(),
  uri: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "account_sid": "accountSid",
    "api_version": "apiVersion",
    "call_sid": "callSid",
    "date_created": "dateCreated",
    "date_updated": "dateUpdated",
    "error_code": "errorCode",
    "message_date": "messageDate",
    "message_text": "messageText",
    "more_info": "moreInfo",
    "request_method": "requestMethod",
    "request_url": "requestUrl",
  });
});

/** @internal */
export type ApiV2010AccountNotification$Outbound = {
  account_sid?: string | null | undefined;
  api_version?: string | null | undefined;
  call_sid?: string | null | undefined;
  date_created?: string | null | undefined;
  date_updated?: string | null | undefined;
  error_code?: string | null | undefined;
  log?: string | null | undefined;
  message_date?: string | null | undefined;
  message_text?: string | null | undefined;
  more_info?: string | null | undefined;
  request_method?: string | null | undefined;
  request_url?: string | null | undefined;
  sid?: string | null | undefined;
  uri?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountNotification$outboundSchema: z.ZodType<
  ApiV2010AccountNotification$Outbound,
  z.ZodTypeDef,
  ApiV2010AccountNotification
> = z.object({
  accountSid: z.nullable(z.string()).optional(),
  apiVersion: z.nullable(z.string()).optional(),
  callSid: z.nullable(z.string()).optional(),
  dateCreated: z.nullable(z.string()).optional(),
  dateUpdated: z.nullable(z.string()).optional(),
  errorCode: z.nullable(z.string()).optional(),
  log: z.nullable(z.string()).optional(),
  messageDate: z.nullable(z.string()).optional(),
  messageText: z.nullable(z.string()).optional(),
  moreInfo: z.nullable(z.string()).optional(),
  requestMethod: z.nullable(
    ApiV2010AccountNotificationRequestMethod$outboundSchema,
  ).optional(),
  requestUrl: z.nullable(z.string()).optional(),
  sid: z.nullable(z.string()).optional(),
  uri: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "account_sid",
    apiVersion: "api_version",
    callSid: "call_sid",
    dateCreated: "date_created",
    dateUpdated: "date_updated",
    errorCode: "error_code",
    messageDate: "message_date",
    messageText: "message_text",
    moreInfo: "more_info",
    requestMethod: "request_method",
    requestUrl: "request_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountNotification$ {
  /** @deprecated use `ApiV2010AccountNotification$inboundSchema` instead. */
  export const inboundSchema = ApiV2010AccountNotification$inboundSchema;
  /** @deprecated use `ApiV2010AccountNotification$outboundSchema` instead. */
  export const outboundSchema = ApiV2010AccountNotification$outboundSchema;
  /** @deprecated use `ApiV2010AccountNotification$Outbound` instead. */
  export type Outbound = ApiV2010AccountNotification$Outbound;
}

export function apiV2010AccountNotificationToJSON(
  apiV2010AccountNotification: ApiV2010AccountNotification,
): string {
  return JSON.stringify(
    ApiV2010AccountNotification$outboundSchema.parse(
      apiV2010AccountNotification,
    ),
  );
}

export function apiV2010AccountNotificationFromJSON(
  jsonString: string,
): SafeParseResult<ApiV2010AccountNotification, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiV2010AccountNotification$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiV2010AccountNotification' from JSON`,
  );
}
