/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping =
  {
    /**
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the CredentialListMapping resource.
     */
    accountSid?: string | null | undefined;
    /**
     * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
     */
    dateCreated?: string | null | undefined;
    /**
     * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
     */
    dateUpdated?: string | null | undefined;
    /**
     * The string that you assigned to describe the resource.
     */
    friendlyName?: string | null | undefined;
    /**
     * The unique string that that we created to identify the CredentialListMapping resource.
     */
    sid?: string | null | undefined;
  };

/** @internal */
export const ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$inboundSchema:
  z.ZodType<
    ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping,
    z.ZodTypeDef,
    unknown
  > = z.object({
    account_sid: z.nullable(z.string()).optional(),
    date_created: z.nullable(z.string()).optional(),
    date_updated: z.nullable(z.string()).optional(),
    friendly_name: z.nullable(z.string()).optional(),
    sid: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "account_sid": "accountSid",
      "date_created": "dateCreated",
      "date_updated": "dateUpdated",
      "friendly_name": "friendlyName",
    });
  });

/** @internal */
export type ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$Outbound =
  {
    account_sid?: string | null | undefined;
    date_created?: string | null | undefined;
    date_updated?: string | null | undefined;
    friendly_name?: string | null | undefined;
    sid?: string | null | undefined;
  };

/** @internal */
export const ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$outboundSchema:
  z.ZodType<
    ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$Outbound,
    z.ZodTypeDef,
    ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping
  > = z.object({
    accountSid: z.nullable(z.string()).optional(),
    dateCreated: z.nullable(z.string()).optional(),
    dateUpdated: z.nullable(z.string()).optional(),
    friendlyName: z.nullable(z.string()).optional(),
    sid: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      accountSid: "account_sid",
      dateCreated: "date_created",
      dateUpdated: "date_updated",
      friendlyName: "friendly_name",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$ {
  /** @deprecated use `ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$inboundSchema` instead. */
  export const inboundSchema =
    ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$inboundSchema;
  /** @deprecated use `ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$outboundSchema` instead. */
  export const outboundSchema =
    ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$outboundSchema;
  /** @deprecated use `ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$Outbound` instead. */
  export type Outbound =
    ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$Outbound;
}

export function apiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMappingToJSON(
  apiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping:
    ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping,
): string {
  return JSON.stringify(
    ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$outboundSchema
      .parse(
        apiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping,
      ),
  );
}

export function apiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMappingFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ApiV2010AccountSipSipDomainSipAuthSipAuthRegistrationsSipAuthRegistrationsCredentialListMapping' from JSON`,
  );
}
