/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApiV2010AccountCallCallEvent = {
  /**
   * Contains a dictionary representing the request of the call.
   */
  request?: any | null | undefined;
  /**
   * Contains a dictionary representing the call response, including a list of the call events.
   */
  response?: any | null | undefined;
};

/** @internal */
export const ApiV2010AccountCallCallEvent$inboundSchema: z.ZodType<
  ApiV2010AccountCallCallEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  request: z.nullable(z.any()).optional(),
  response: z.nullable(z.any()).optional(),
});

/** @internal */
export type ApiV2010AccountCallCallEvent$Outbound = {
  request?: any | null | undefined;
  response?: any | null | undefined;
};

/** @internal */
export const ApiV2010AccountCallCallEvent$outboundSchema: z.ZodType<
  ApiV2010AccountCallCallEvent$Outbound,
  z.ZodTypeDef,
  ApiV2010AccountCallCallEvent
> = z.object({
  request: z.nullable(z.any()).optional(),
  response: z.nullable(z.any()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountCallCallEvent$ {
  /** @deprecated use `ApiV2010AccountCallCallEvent$inboundSchema` instead. */
  export const inboundSchema = ApiV2010AccountCallCallEvent$inboundSchema;
  /** @deprecated use `ApiV2010AccountCallCallEvent$outboundSchema` instead. */
  export const outboundSchema = ApiV2010AccountCallCallEvent$outboundSchema;
  /** @deprecated use `ApiV2010AccountCallCallEvent$Outbound` instead. */
  export type Outbound = ApiV2010AccountCallCallEvent$Outbound;
}

export function apiV2010AccountCallCallEventToJSON(
  apiV2010AccountCallCallEvent: ApiV2010AccountCallCallEvent,
): string {
  return JSON.stringify(
    ApiV2010AccountCallCallEvent$outboundSchema.parse(
      apiV2010AccountCallCallEvent,
    ),
  );
}

export function apiV2010AccountCallCallEventFromJSON(
  jsonString: string,
): SafeParseResult<ApiV2010AccountCallCallEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiV2010AccountCallCallEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiV2010AccountCallCallEvent' from JSON`,
  );
}
