/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RecordingEnumSource,
  RecordingEnumSource$inboundSchema,
  RecordingEnumSource$outboundSchema,
} from "./recordingenumsource.js";
import {
  RecordingEnumStatus,
  RecordingEnumStatus$inboundSchema,
  RecordingEnumStatus$outboundSchema,
} from "./recordingenumstatus.js";

/**
 * A list of related resources identified by their relative URIs.
 */
export type ApiV2010AccountRecordingSubresourceUris = {};

export type ApiV2010AccountRecording = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Recording resource.
   */
  accountSid?: string | null | undefined;
  /**
   * The API version used during the recording.
   */
  apiVersion?: string | null | undefined;
  /**
   * The SID of the [Call](https://www.twilio.com/docs/voice/api/call-resource) the Recording resource is associated with. This will always refer to the parent leg of a two-leg call.
   */
  callSid?: string | null | undefined;
  /**
   * The Conference SID that identifies the conference associated with the recording, if a conference recording.
   */
  conferenceSid?: string | null | undefined;
  /**
   * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateCreated?: string | null | undefined;
  /**
   * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateUpdated?: string | null | undefined;
  /**
   * The start time of the recording in GMT and in [RFC 2822](https://www.php.net/manual/en/class.datetime.php#datetime.constants.rfc2822) format.
   */
  startTime?: string | null | undefined;
  /**
   * The length of the recording in seconds.
   */
  duration?: string | null | undefined;
  /**
   * The unique string that that we created to identify the Recording resource.
   */
  sid?: string | null | undefined;
  /**
   * The one-time cost of creating the recording in the `price_unit` currency.
   */
  price?: string | null | undefined;
  /**
   * The currency used in the `price` property. Example: `USD`.
   */
  priceUnit?: string | null | undefined;
  status?: RecordingEnumStatus | undefined;
  /**
   * The number of channels in the final recording file. Can be: `1` or `2`.
   */
  channels?: number | undefined;
  source?: RecordingEnumSource | undefined;
  /**
   * The error code that describes why the recording is `absent`. The error code is described in our [Error Dictionary](https://www.twilio.com/docs/api/errors). This value is null if the recording `status` is not `absent`.
   */
  errorCode?: number | null | undefined;
  /**
   * The URI of the resource, relative to `https://api.twilio.com`.
   */
  uri?: string | null | undefined;
  /**
   * How to decrypt the recording if it was encrypted using [Call Recording Encryption](https://www.twilio.com/docs/voice/tutorials/voice-recording-encryption) feature.
   */
  encryptionDetails?: any | null | undefined;
  /**
   * A list of related resources identified by their relative URIs.
   */
  subresourceUris?: ApiV2010AccountRecordingSubresourceUris | null | undefined;
  /**
   * The URL of the media file associated with this recording resource. When stored externally, this is the full URL location of the media file.
   */
  mediaUrl?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountRecordingSubresourceUris$inboundSchema: z.ZodType<
  ApiV2010AccountRecordingSubresourceUris,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type ApiV2010AccountRecordingSubresourceUris$Outbound = {};

/** @internal */
export const ApiV2010AccountRecordingSubresourceUris$outboundSchema: z.ZodType<
  ApiV2010AccountRecordingSubresourceUris$Outbound,
  z.ZodTypeDef,
  ApiV2010AccountRecordingSubresourceUris
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountRecordingSubresourceUris$ {
  /** @deprecated use `ApiV2010AccountRecordingSubresourceUris$inboundSchema` instead. */
  export const inboundSchema =
    ApiV2010AccountRecordingSubresourceUris$inboundSchema;
  /** @deprecated use `ApiV2010AccountRecordingSubresourceUris$outboundSchema` instead. */
  export const outboundSchema =
    ApiV2010AccountRecordingSubresourceUris$outboundSchema;
  /** @deprecated use `ApiV2010AccountRecordingSubresourceUris$Outbound` instead. */
  export type Outbound = ApiV2010AccountRecordingSubresourceUris$Outbound;
}

export function apiV2010AccountRecordingSubresourceUrisToJSON(
  apiV2010AccountRecordingSubresourceUris:
    ApiV2010AccountRecordingSubresourceUris,
): string {
  return JSON.stringify(
    ApiV2010AccountRecordingSubresourceUris$outboundSchema.parse(
      apiV2010AccountRecordingSubresourceUris,
    ),
  );
}

export function apiV2010AccountRecordingSubresourceUrisFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiV2010AccountRecordingSubresourceUris,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiV2010AccountRecordingSubresourceUris$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiV2010AccountRecordingSubresourceUris' from JSON`,
  );
}

/** @internal */
export const ApiV2010AccountRecording$inboundSchema: z.ZodType<
  ApiV2010AccountRecording,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_sid: z.nullable(z.string()).optional(),
  api_version: z.nullable(z.string()).optional(),
  call_sid: z.nullable(z.string()).optional(),
  conference_sid: z.nullable(z.string()).optional(),
  date_created: z.nullable(z.string()).optional(),
  date_updated: z.nullable(z.string()).optional(),
  start_time: z.nullable(z.string()).optional(),
  duration: z.nullable(z.string()).optional(),
  sid: z.nullable(z.string()).optional(),
  price: z.nullable(z.string()).optional(),
  price_unit: z.nullable(z.string()).optional(),
  status: RecordingEnumStatus$inboundSchema.optional(),
  channels: z.number().int().default(0),
  source: RecordingEnumSource$inboundSchema.optional(),
  error_code: z.nullable(z.number().int()).optional(),
  uri: z.nullable(z.string()).optional(),
  encryption_details: z.nullable(z.any()).optional(),
  subresource_uris: z.nullable(
    z.lazy(() => ApiV2010AccountRecordingSubresourceUris$inboundSchema),
  ).optional(),
  media_url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "account_sid": "accountSid",
    "api_version": "apiVersion",
    "call_sid": "callSid",
    "conference_sid": "conferenceSid",
    "date_created": "dateCreated",
    "date_updated": "dateUpdated",
    "start_time": "startTime",
    "price_unit": "priceUnit",
    "error_code": "errorCode",
    "encryption_details": "encryptionDetails",
    "subresource_uris": "subresourceUris",
    "media_url": "mediaUrl",
  });
});

/** @internal */
export type ApiV2010AccountRecording$Outbound = {
  account_sid?: string | null | undefined;
  api_version?: string | null | undefined;
  call_sid?: string | null | undefined;
  conference_sid?: string | null | undefined;
  date_created?: string | null | undefined;
  date_updated?: string | null | undefined;
  start_time?: string | null | undefined;
  duration?: string | null | undefined;
  sid?: string | null | undefined;
  price?: string | null | undefined;
  price_unit?: string | null | undefined;
  status?: string | undefined;
  channels: number;
  source?: string | undefined;
  error_code?: number | null | undefined;
  uri?: string | null | undefined;
  encryption_details?: any | null | undefined;
  subresource_uris?:
    | ApiV2010AccountRecordingSubresourceUris$Outbound
    | null
    | undefined;
  media_url?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountRecording$outboundSchema: z.ZodType<
  ApiV2010AccountRecording$Outbound,
  z.ZodTypeDef,
  ApiV2010AccountRecording
> = z.object({
  accountSid: z.nullable(z.string()).optional(),
  apiVersion: z.nullable(z.string()).optional(),
  callSid: z.nullable(z.string()).optional(),
  conferenceSid: z.nullable(z.string()).optional(),
  dateCreated: z.nullable(z.string()).optional(),
  dateUpdated: z.nullable(z.string()).optional(),
  startTime: z.nullable(z.string()).optional(),
  duration: z.nullable(z.string()).optional(),
  sid: z.nullable(z.string()).optional(),
  price: z.nullable(z.string()).optional(),
  priceUnit: z.nullable(z.string()).optional(),
  status: RecordingEnumStatus$outboundSchema.optional(),
  channels: z.number().int().default(0),
  source: RecordingEnumSource$outboundSchema.optional(),
  errorCode: z.nullable(z.number().int()).optional(),
  uri: z.nullable(z.string()).optional(),
  encryptionDetails: z.nullable(z.any()).optional(),
  subresourceUris: z.nullable(
    z.lazy(() => ApiV2010AccountRecordingSubresourceUris$outboundSchema),
  ).optional(),
  mediaUrl: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "account_sid",
    apiVersion: "api_version",
    callSid: "call_sid",
    conferenceSid: "conference_sid",
    dateCreated: "date_created",
    dateUpdated: "date_updated",
    startTime: "start_time",
    priceUnit: "price_unit",
    errorCode: "error_code",
    encryptionDetails: "encryption_details",
    subresourceUris: "subresource_uris",
    mediaUrl: "media_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountRecording$ {
  /** @deprecated use `ApiV2010AccountRecording$inboundSchema` instead. */
  export const inboundSchema = ApiV2010AccountRecording$inboundSchema;
  /** @deprecated use `ApiV2010AccountRecording$outboundSchema` instead. */
  export const outboundSchema = ApiV2010AccountRecording$outboundSchema;
  /** @deprecated use `ApiV2010AccountRecording$Outbound` instead. */
  export type Outbound = ApiV2010AccountRecording$Outbound;
}

export function apiV2010AccountRecordingToJSON(
  apiV2010AccountRecording: ApiV2010AccountRecording,
): string {
  return JSON.stringify(
    ApiV2010AccountRecording$outboundSchema.parse(apiV2010AccountRecording),
  );
}

export function apiV2010AccountRecordingFromJSON(
  jsonString: string,
): SafeParseResult<ApiV2010AccountRecording, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiV2010AccountRecording$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiV2010AccountRecording' from JSON`,
  );
}
