/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  UsageRecordEnumCategory,
  UsageRecordEnumCategory$inboundSchema,
  UsageRecordEnumCategory$outboundSchema,
} from "./usagerecordenumcategory.js";

/**
 * A list of related resources identified by their URIs. For more information, see [List Subresources](https://www.twilio.com/docs/usage/api/usage-record#list-subresources).
 */
export type ApiV2010AccountUsageUsageRecordSubresourceUris = {};

export type ApiV2010AccountUsageUsageRecord = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that accrued the usage.
   */
  accountSid?: string | null | undefined;
  /**
   * The API version used to create the resource.
   */
  apiVersion?: string | null | undefined;
  /**
   * Usage records up to date as of this timestamp, formatted as YYYY-MM-DDTHH:MM:SS+00:00. All timestamps are in GMT
   */
  asOf?: string | null | undefined;
  category?: UsageRecordEnumCategory | undefined;
  /**
   * The number of usage events, such as the number of calls.
   */
  count?: string | null | undefined;
  /**
   * The units in which `count` is measured, such as `calls` for calls or `messages` for SMS.
   */
  countUnit?: string | null | undefined;
  /**
   * A plain-language description of the usage category.
   */
  description?: string | null | undefined;
  /**
   * The last date for which usage is included in the UsageRecord. The date is specified in GMT and formatted as `YYYY-MM-DD`.
   */
  endDate?: RFCDate | null | undefined;
  /**
   * The total price of the usage in the currency specified in `price_unit` and associated with the account.
   */
  price?: number | null | undefined;
  /**
   * The currency in which `price` is measured, in [ISO 4127](https://www.iso.org/iso/home/standards/currency_codes.htm) format, such as `usd`, `eur`, and `jpy`.
   */
  priceUnit?: string | null | undefined;
  /**
   * The first date for which usage is included in this UsageRecord. The date is specified in GMT and formatted as `YYYY-MM-DD`.
   */
  startDate?: RFCDate | null | undefined;
  /**
   * A list of related resources identified by their URIs. For more information, see [List Subresources](https://www.twilio.com/docs/usage/api/usage-record#list-subresources).
   */
  subresourceUris?:
    | ApiV2010AccountUsageUsageRecordSubresourceUris
    | null
    | undefined;
  /**
   * The URI of the resource, relative to `https://api.twilio.com`.
   */
  uri?: string | null | undefined;
  /**
   * The amount used to bill usage and measured in units described in `usage_unit`.
   */
  usage?: string | null | undefined;
  /**
   * The units in which `usage` is measured, such as `minutes` for calls or `messages` for SMS.
   */
  usageUnit?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountUsageUsageRecordSubresourceUris$inboundSchema:
  z.ZodType<
    ApiV2010AccountUsageUsageRecordSubresourceUris,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type ApiV2010AccountUsageUsageRecordSubresourceUris$Outbound = {};

/** @internal */
export const ApiV2010AccountUsageUsageRecordSubresourceUris$outboundSchema:
  z.ZodType<
    ApiV2010AccountUsageUsageRecordSubresourceUris$Outbound,
    z.ZodTypeDef,
    ApiV2010AccountUsageUsageRecordSubresourceUris
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountUsageUsageRecordSubresourceUris$ {
  /** @deprecated use `ApiV2010AccountUsageUsageRecordSubresourceUris$inboundSchema` instead. */
  export const inboundSchema =
    ApiV2010AccountUsageUsageRecordSubresourceUris$inboundSchema;
  /** @deprecated use `ApiV2010AccountUsageUsageRecordSubresourceUris$outboundSchema` instead. */
  export const outboundSchema =
    ApiV2010AccountUsageUsageRecordSubresourceUris$outboundSchema;
  /** @deprecated use `ApiV2010AccountUsageUsageRecordSubresourceUris$Outbound` instead. */
  export type Outbound =
    ApiV2010AccountUsageUsageRecordSubresourceUris$Outbound;
}

export function apiV2010AccountUsageUsageRecordSubresourceUrisToJSON(
  apiV2010AccountUsageUsageRecordSubresourceUris:
    ApiV2010AccountUsageUsageRecordSubresourceUris,
): string {
  return JSON.stringify(
    ApiV2010AccountUsageUsageRecordSubresourceUris$outboundSchema.parse(
      apiV2010AccountUsageUsageRecordSubresourceUris,
    ),
  );
}

export function apiV2010AccountUsageUsageRecordSubresourceUrisFromJSON(
  jsonString: string,
): SafeParseResult<
  ApiV2010AccountUsageUsageRecordSubresourceUris,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApiV2010AccountUsageUsageRecordSubresourceUris$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApiV2010AccountUsageUsageRecordSubresourceUris' from JSON`,
  );
}

/** @internal */
export const ApiV2010AccountUsageUsageRecord$inboundSchema: z.ZodType<
  ApiV2010AccountUsageUsageRecord,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_sid: z.nullable(z.string()).optional(),
  api_version: z.nullable(z.string()).optional(),
  as_of: z.nullable(z.string()).optional(),
  category: UsageRecordEnumCategory$inboundSchema.optional(),
  count: z.nullable(z.string()).optional(),
  count_unit: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  end_date: z.nullable(z.string().transform(v => new RFCDate(v))).optional(),
  price: z.nullable(z.number()).optional(),
  price_unit: z.nullable(z.string()).optional(),
  start_date: z.nullable(z.string().transform(v => new RFCDate(v))).optional(),
  subresource_uris: z.nullable(
    z.lazy(() => ApiV2010AccountUsageUsageRecordSubresourceUris$inboundSchema),
  ).optional(),
  uri: z.nullable(z.string()).optional(),
  usage: z.nullable(z.string()).optional(),
  usage_unit: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "account_sid": "accountSid",
    "api_version": "apiVersion",
    "as_of": "asOf",
    "count_unit": "countUnit",
    "end_date": "endDate",
    "price_unit": "priceUnit",
    "start_date": "startDate",
    "subresource_uris": "subresourceUris",
    "usage_unit": "usageUnit",
  });
});

/** @internal */
export type ApiV2010AccountUsageUsageRecord$Outbound = {
  account_sid?: string | null | undefined;
  api_version?: string | null | undefined;
  as_of?: string | null | undefined;
  category?: string | undefined;
  count?: string | null | undefined;
  count_unit?: string | null | undefined;
  description?: string | null | undefined;
  end_date?: string | null | undefined;
  price?: number | null | undefined;
  price_unit?: string | null | undefined;
  start_date?: string | null | undefined;
  subresource_uris?:
    | ApiV2010AccountUsageUsageRecordSubresourceUris$Outbound
    | null
    | undefined;
  uri?: string | null | undefined;
  usage?: string | null | undefined;
  usage_unit?: string | null | undefined;
};

/** @internal */
export const ApiV2010AccountUsageUsageRecord$outboundSchema: z.ZodType<
  ApiV2010AccountUsageUsageRecord$Outbound,
  z.ZodTypeDef,
  ApiV2010AccountUsageUsageRecord
> = z.object({
  accountSid: z.nullable(z.string()).optional(),
  apiVersion: z.nullable(z.string()).optional(),
  asOf: z.nullable(z.string()).optional(),
  category: UsageRecordEnumCategory$outboundSchema.optional(),
  count: z.nullable(z.string()).optional(),
  countUnit: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  endDate: z.nullable(z.instanceof(RFCDate).transform(v => v.toString()))
    .optional(),
  price: z.nullable(z.number()).optional(),
  priceUnit: z.nullable(z.string()).optional(),
  startDate: z.nullable(z.instanceof(RFCDate).transform(v => v.toString()))
    .optional(),
  subresourceUris: z.nullable(
    z.lazy(() => ApiV2010AccountUsageUsageRecordSubresourceUris$outboundSchema),
  ).optional(),
  uri: z.nullable(z.string()).optional(),
  usage: z.nullable(z.string()).optional(),
  usageUnit: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "account_sid",
    apiVersion: "api_version",
    asOf: "as_of",
    countUnit: "count_unit",
    endDate: "end_date",
    priceUnit: "price_unit",
    startDate: "start_date",
    subresourceUris: "subresource_uris",
    usageUnit: "usage_unit",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiV2010AccountUsageUsageRecord$ {
  /** @deprecated use `ApiV2010AccountUsageUsageRecord$inboundSchema` instead. */
  export const inboundSchema = ApiV2010AccountUsageUsageRecord$inboundSchema;
  /** @deprecated use `ApiV2010AccountUsageUsageRecord$outboundSchema` instead. */
  export const outboundSchema = ApiV2010AccountUsageUsageRecord$outboundSchema;
  /** @deprecated use `ApiV2010AccountUsageUsageRecord$Outbound` instead. */
  export type Outbound = ApiV2010AccountUsageUsageRecord$Outbound;
}

export function apiV2010AccountUsageUsageRecordToJSON(
  apiV2010AccountUsageUsageRecord: ApiV2010AccountUsageUsageRecord,
): string {
  return JSON.stringify(
    ApiV2010AccountUsageUsageRecord$outboundSchema.parse(
      apiV2010AccountUsageUsageRecord,
    ),
  );
}

export function apiV2010AccountUsageUsageRecordFromJSON(
  jsonString: string,
): SafeParseResult<ApiV2010AccountUsageUsageRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiV2010AccountUsageUsageRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiV2010AccountUsageUsageRecord' from JSON`,
  );
}
