/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const CallEnumUpdateStatus = {
  Canceled: "canceled",
  Completed: "completed",
} as const;
export type CallEnumUpdateStatus = ClosedEnum<typeof CallEnumUpdateStatus>;

/** @internal */
export const CallEnumUpdateStatus$inboundSchema: z.ZodNativeEnum<
  typeof CallEnumUpdateStatus
> = z.nativeEnum(CallEnumUpdateStatus);

/** @internal */
export const CallEnumUpdateStatus$outboundSchema: z.ZodNativeEnum<
  typeof CallEnumUpdateStatus
> = CallEnumUpdateStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CallEnumUpdateStatus$ {
  /** @deprecated use `CallEnumUpdateStatus$inboundSchema` instead. */
  export const inboundSchema = CallEnumUpdateStatus$inboundSchema;
  /** @deprecated use `CallEnumUpdateStatus$outboundSchema` instead. */
  export const outboundSchema = CallEnumUpdateStatus$outboundSchema;
}
