/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const CallEnumStatus = {
  Queued: "queued",
  Ringing: "ringing",
  InProgress: "in-progress",
  Completed: "completed",
  Busy: "busy",
  Failed: "failed",
  NoAnswer: "no-answer",
  Canceled: "canceled",
} as const;
export type CallEnumStatus = ClosedEnum<typeof CallEnumStatus>;

/** @internal */
export const CallEnumStatus$inboundSchema: z.ZodNativeEnum<
  typeof CallEnumStatus
> = z.nativeEnum(CallEnumStatus);

/** @internal */
export const CallEnumStatus$outboundSchema: z.ZodNativeEnum<
  typeof CallEnumStatus
> = CallEnumStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CallEnumStatus$ {
  /** @deprecated use `CallEnumStatus$inboundSchema` instead. */
  export const inboundSchema = CallEnumStatus$inboundSchema;
  /** @deprecated use `CallEnumStatus$outboundSchema` instead. */
  export const outboundSchema = CallEnumStatus$outboundSchema;
}
