/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ConferenceRecordingEnumSource = {
  DialVerb: "DialVerb",
  Conference: "Conference",
  OutboundAPI: "OutboundAPI",
  Trunking: "Trunking",
  RecordVerb: "RecordVerb",
  StartCallRecordingAPI: "StartCallRecordingAPI",
  StartConferenceRecordingAPI: "StartConferenceRecordingAPI",
} as const;
export type ConferenceRecordingEnumSource = ClosedEnum<
  typeof ConferenceRecordingEnumSource
>;

/** @internal */
export const ConferenceRecordingEnumSource$inboundSchema: z.ZodNativeEnum<
  typeof ConferenceRecordingEnumSource
> = z.nativeEnum(ConferenceRecordingEnumSource);

/** @internal */
export const ConferenceRecordingEnumSource$outboundSchema: z.ZodNativeEnum<
  typeof ConferenceRecordingEnumSource
> = ConferenceRecordingEnumSource$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConferenceRecordingEnumSource$ {
  /** @deprecated use `ConferenceRecordingEnumSource$inboundSchema` instead. */
  export const inboundSchema = ConferenceRecordingEnumSource$inboundSchema;
  /** @deprecated use `ConferenceRecordingEnumSource$outboundSchema` instead. */
  export const outboundSchema = ConferenceRecordingEnumSource$outboundSchema;
}
