/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ConferenceEnumReasonConferenceEnded = {
  ConferenceEndedViaApi: "conference-ended-via-api",
  ParticipantWithEndConferenceOnExitLeft:
    "participant-with-end-conference-on-exit-left",
  ParticipantWithEndConferenceOnExitKicked:
    "participant-with-end-conference-on-exit-kicked",
  LastParticipantKicked: "last-participant-kicked",
  LastParticipantLeft: "last-participant-left",
} as const;
export type ConferenceEnumReasonConferenceEnded = ClosedEnum<
  typeof ConferenceEnumReasonConferenceEnded
>;

/** @internal */
export const ConferenceEnumReasonConferenceEnded$inboundSchema: z.ZodNativeEnum<
  typeof ConferenceEnumReasonConferenceEnded
> = z.nativeEnum(ConferenceEnumReasonConferenceEnded);

/** @internal */
export const ConferenceEnumReasonConferenceEnded$outboundSchema:
  z.ZodNativeEnum<typeof ConferenceEnumReasonConferenceEnded> =
    ConferenceEnumReasonConferenceEnded$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConferenceEnumReasonConferenceEnded$ {
  /** @deprecated use `ConferenceEnumReasonConferenceEnded$inboundSchema` instead. */
  export const inboundSchema =
    ConferenceEnumReasonConferenceEnded$inboundSchema;
  /** @deprecated use `ConferenceEnumReasonConferenceEnded$outboundSchema` instead. */
  export const outboundSchema =
    ConferenceEnumReasonConferenceEnded$outboundSchema;
}
