/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const DependentPhoneNumberEnumEmergencyStatus = {
  Active: "Active",
  Inactive: "Inactive",
} as const;
export type DependentPhoneNumberEnumEmergencyStatus = ClosedEnum<
  typeof DependentPhoneNumberEnumEmergencyStatus
>;

/** @internal */
export const DependentPhoneNumberEnumEmergencyStatus$inboundSchema:
  z.ZodNativeEnum<typeof DependentPhoneNumberEnumEmergencyStatus> = z
    .nativeEnum(DependentPhoneNumberEnumEmergencyStatus);

/** @internal */
export const DependentPhoneNumberEnumEmergencyStatus$outboundSchema:
  z.ZodNativeEnum<typeof DependentPhoneNumberEnumEmergencyStatus> =
    DependentPhoneNumberEnumEmergencyStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DependentPhoneNumberEnumEmergencyStatus$ {
  /** @deprecated use `DependentPhoneNumberEnumEmergencyStatus$inboundSchema` instead. */
  export const inboundSchema =
    DependentPhoneNumberEnumEmergencyStatus$inboundSchema;
  /** @deprecated use `DependentPhoneNumberEnumEmergencyStatus$outboundSchema` instead. */
  export const outboundSchema =
    DependentPhoneNumberEnumEmergencyStatus$outboundSchema;
}
