/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const IncomingPhoneNumberTollFreeEnumEmergencyStatus = {
  Active: "Active",
  Inactive: "Inactive",
} as const;
export type IncomingPhoneNumberTollFreeEnumEmergencyStatus = ClosedEnum<
  typeof IncomingPhoneNumberTollFreeEnumEmergencyStatus
>;

/** @internal */
export const IncomingPhoneNumberTollFreeEnumEmergencyStatus$inboundSchema:
  z.ZodNativeEnum<typeof IncomingPhoneNumberTollFreeEnumEmergencyStatus> = z
    .nativeEnum(IncomingPhoneNumberTollFreeEnumEmergencyStatus);

/** @internal */
export const IncomingPhoneNumberTollFreeEnumEmergencyStatus$outboundSchema:
  z.ZodNativeEnum<typeof IncomingPhoneNumberTollFreeEnumEmergencyStatus> =
    IncomingPhoneNumberTollFreeEnumEmergencyStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IncomingPhoneNumberTollFreeEnumEmergencyStatus$ {
  /** @deprecated use `IncomingPhoneNumberTollFreeEnumEmergencyStatus$inboundSchema` instead. */
  export const inboundSchema =
    IncomingPhoneNumberTollFreeEnumEmergencyStatus$inboundSchema;
  /** @deprecated use `IncomingPhoneNumberTollFreeEnumEmergencyStatus$outboundSchema` instead. */
  export const outboundSchema =
    IncomingPhoneNumberTollFreeEnumEmergencyStatus$outboundSchema;
}
