/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const MessageEnumScheduleType = {
  Fixed: "fixed",
} as const;
export type MessageEnumScheduleType = ClosedEnum<
  typeof MessageEnumScheduleType
>;

/** @internal */
export const MessageEnumScheduleType$inboundSchema: z.ZodNativeEnum<
  typeof MessageEnumScheduleType
> = z.nativeEnum(MessageEnumScheduleType);

/** @internal */
export const MessageEnumScheduleType$outboundSchema: z.ZodNativeEnum<
  typeof MessageEnumScheduleType
> = MessageEnumScheduleType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessageEnumScheduleType$ {
  /** @deprecated use `MessageEnumScheduleType$inboundSchema` instead. */
  export const inboundSchema = MessageEnumScheduleType$inboundSchema;
  /** @deprecated use `MessageEnumScheduleType$outboundSchema` instead. */
  export const outboundSchema = MessageEnumScheduleType$outboundSchema;
}
