/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const MessageEnumDirection = {
  Inbound: "inbound",
  OutboundApi: "outbound-api",
  OutboundCall: "outbound-call",
  OutboundReply: "outbound-reply",
} as const;
export type MessageEnumDirection = ClosedEnum<typeof MessageEnumDirection>;

/** @internal */
export const MessageEnumDirection$inboundSchema: z.ZodNativeEnum<
  typeof MessageEnumDirection
> = z.nativeEnum(MessageEnumDirection);

/** @internal */
export const MessageEnumDirection$outboundSchema: z.ZodNativeEnum<
  typeof MessageEnumDirection
> = MessageEnumDirection$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessageEnumDirection$ {
  /** @deprecated use `MessageEnumDirection$inboundSchema` instead. */
  export const inboundSchema = MessageEnumDirection$inboundSchema;
  /** @deprecated use `MessageEnumDirection$outboundSchema` instead. */
  export const outboundSchema = MessageEnumDirection$outboundSchema;
}
