/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const PaymentsEnumTokenType = {
  OneTime: "one-time",
  Reusable: "reusable",
  PaymentMethod: "payment-method",
} as const;
export type PaymentsEnumTokenType = ClosedEnum<typeof PaymentsEnumTokenType>;

/** @internal */
export const PaymentsEnumTokenType$inboundSchema: z.ZodNativeEnum<
  typeof PaymentsEnumTokenType
> = z.nativeEnum(PaymentsEnumTokenType);

/** @internal */
export const PaymentsEnumTokenType$outboundSchema: z.ZodNativeEnum<
  typeof PaymentsEnumTokenType
> = PaymentsEnumTokenType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentsEnumTokenType$ {
  /** @deprecated use `PaymentsEnumTokenType$inboundSchema` instead. */
  export const inboundSchema = PaymentsEnumTokenType$inboundSchema;
  /** @deprecated use `PaymentsEnumTokenType$outboundSchema` instead. */
  export const outboundSchema = PaymentsEnumTokenType$outboundSchema;
}
