/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const RealtimeTranscriptionEnumUpdateStatus = {
  Stopped: "stopped",
} as const;
export type RealtimeTranscriptionEnumUpdateStatus = ClosedEnum<
  typeof RealtimeTranscriptionEnumUpdateStatus
>;

/** @internal */
export const RealtimeTranscriptionEnumUpdateStatus$inboundSchema:
  z.ZodNativeEnum<typeof RealtimeTranscriptionEnumUpdateStatus> = z.nativeEnum(
    RealtimeTranscriptionEnumUpdateStatus,
  );

/** @internal */
export const RealtimeTranscriptionEnumUpdateStatus$outboundSchema:
  z.ZodNativeEnum<typeof RealtimeTranscriptionEnumUpdateStatus> =
    RealtimeTranscriptionEnumUpdateStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RealtimeTranscriptionEnumUpdateStatus$ {
  /** @deprecated use `RealtimeTranscriptionEnumUpdateStatus$inboundSchema` instead. */
  export const inboundSchema =
    RealtimeTranscriptionEnumUpdateStatus$inboundSchema;
  /** @deprecated use `RealtimeTranscriptionEnumUpdateStatus$outboundSchema` instead. */
  export const outboundSchema =
    RealtimeTranscriptionEnumUpdateStatus$outboundSchema;
}
