/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const RecordingTranscriptionEnumStatus = {
  InProgress: "in-progress",
  Completed: "completed",
  Failed: "failed",
} as const;
export type RecordingTranscriptionEnumStatus = ClosedEnum<
  typeof RecordingTranscriptionEnumStatus
>;

/** @internal */
export const RecordingTranscriptionEnumStatus$inboundSchema: z.ZodNativeEnum<
  typeof RecordingTranscriptionEnumStatus
> = z.nativeEnum(RecordingTranscriptionEnumStatus);

/** @internal */
export const RecordingTranscriptionEnumStatus$outboundSchema: z.ZodNativeEnum<
  typeof RecordingTranscriptionEnumStatus
> = RecordingTranscriptionEnumStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RecordingTranscriptionEnumStatus$ {
  /** @deprecated use `RecordingTranscriptionEnumStatus$inboundSchema` instead. */
  export const inboundSchema = RecordingTranscriptionEnumStatus$inboundSchema;
  /** @deprecated use `RecordingTranscriptionEnumStatus$outboundSchema` instead. */
  export const outboundSchema = RecordingTranscriptionEnumStatus$outboundSchema;
}
