/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const RecordingEnumSource = {
  DialVerb: "DialVerb",
  Conference: "Conference",
  OutboundAPI: "OutboundAPI",
  Trunking: "Trunking",
  RecordVerb: "RecordVerb",
  StartCallRecordingAPI: "StartCallRecordingAPI",
  StartConferenceRecordingAPI: "StartConferenceRecordingAPI",
} as const;
export type RecordingEnumSource = ClosedEnum<typeof RecordingEnumSource>;

/** @internal */
export const RecordingEnumSource$inboundSchema: z.ZodNativeEnum<
  typeof RecordingEnumSource
> = z.nativeEnum(RecordingEnumSource);

/** @internal */
export const RecordingEnumSource$outboundSchema: z.ZodNativeEnum<
  typeof RecordingEnumSource
> = RecordingEnumSource$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RecordingEnumSource$ {
  /** @deprecated use `RecordingEnumSource$inboundSchema` instead. */
  export const inboundSchema = RecordingEnumSource$inboundSchema;
  /** @deprecated use `RecordingEnumSource$outboundSchema` instead. */
  export const outboundSchema = RecordingEnumSource$outboundSchema;
}
