/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const UsageTriggerEnumTriggerField = {
  Count: "count",
  Usage: "usage",
  Price: "price",
} as const;
export type UsageTriggerEnumTriggerField = ClosedEnum<
  typeof UsageTriggerEnumTriggerField
>;

/** @internal */
export const UsageTriggerEnumTriggerField$inboundSchema: z.ZodNativeEnum<
  typeof UsageTriggerEnumTriggerField
> = z.nativeEnum(UsageTriggerEnumTriggerField);

/** @internal */
export const UsageTriggerEnumTriggerField$outboundSchema: z.ZodNativeEnum<
  typeof UsageTriggerEnumTriggerField
> = UsageTriggerEnumTriggerField$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UsageTriggerEnumTriggerField$ {
  /** @deprecated use `UsageTriggerEnumTriggerField$inboundSchema` instead. */
  export const inboundSchema = UsageTriggerEnumTriggerField$inboundSchema;
  /** @deprecated use `UsageTriggerEnumTriggerField$outboundSchema` instead. */
  export const outboundSchema = UsageTriggerEnumTriggerField$outboundSchema;
}
